import type { BizSpec, Fonts, Palette, Template } from "./types";
import { businessSample, PERSONAS } from "./samples";

/**
 * Business card designs. Each one is a different physical product — its own
 * stock, print process, layout, and its own way of arriving and turning over.
 */

type Ink = Pick<Palette, "id" | "label" | "paper" | "paper2" | "ink" | "inkSoft" | "accent" | "accent2" | "foil" | "surface" | "surface2">;

/** Business palettes don't use envelope/wax; accent doubles as the gallery swatch. */
const BP = (p: Ink): Palette => ({ ...p, envelope: p.paper, envelope2: p.accent, wax: p.accent });

const F = (display: string, script: string, body: string): Fonts => ({ display: `var(${display})`, script: `var(${script})`, body: `var(${body})` });

function biz(
  id: string,
  name: string,
  tagline: string,
  spec: BizSpec,
  rest: Pick<Template, "paper" | "backdrop" | "fonts" | "palettes" | "styles" | "effects"> & Partial<Pick<Template, "industries" | "photo">>,
): Template {
  return {
    id,
    name,
    category: "business",
    tagline,
    ornament: "deco",
    petals: "gold",
    biz: spec,
    sample: businessSample(rest.palettes[0].id, PERSONAS[spec.design]),
    ...rest,
  };
}

export const BUSINESS_TEMPLATES: Template[] = [
  biz("noir-foil", "Noir Foil", "Triplex black card, hot-foil stamped", { design: "noir", enter: "drop", flip: "classic", thick: 4, radius: 10, edge: "foil" }, {
    paper: "matte",
    backdrop: "slate",
    fonts: F("--f-cinzel", "--f-italiana", "--f-tenor"),
    industries: ["Luxury & Jewellery", "Finance & Legal", "Any business"],
    styles: ["Luxury", "Classic"],
    effects: ["Hot foil", "Painted edge"],
    palettes: [
      BP({ id: "noir", label: "Noir", paper: "#141414", paper2: "#1f1f1f", ink: "#ebe5d6", inkSoft: "#9a9282", accent: "#c9a24a", accent2: "#333", foil: "gold", surface: "#2a2c30", surface2: "#151619" }),
      BP({ id: "navy", label: "Navy", paper: "#10203a", paper2: "#18294a", ink: "#e8edf5", inkSoft: "#93a0b8", accent: "#c0c6d0", accent2: "#223", foil: "silver", surface: "#262a31", surface2: "#14171c" }),
      BP({ id: "forest", label: "Forest", paper: "#132a20", paper2: "#1a3629", ink: "#efe8d5", inkSoft: "#9fae9f", accent: "#c9a24a", accent2: "#0a1a12", foil: "gold", surface: "#2a2c30", surface2: "#151619" }),
    ],
  }),
  biz("ivory-letterpress", "Ivory Letterpress", "Deep-impression letterpress on cotton stock", { design: "letterpress", enter: "press", flip: "lift", thick: 3, radius: 6, edge: "#e9e1cf" }, {
    paper: "cotton",
    backdrop: "wood",
    fonts: F("--f-playfair", "--f-pinyon", "--f-tenor"),
    industries: ["Architecture & Construction", "Creative & Design", "Any business"],
    styles: ["Classic", "Minimal"],
    effects: ["Letterpress"],
    palettes: [
      BP({ id: "ivory", label: "Ivory & Navy", paper: "#f7f3ea", paper2: "#ede6d6", ink: "#1f3a5f", inkSoft: "#5b6f8a", accent: "#1f3a5f", accent2: "#c9a24a", foil: "gold", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "sage", label: "Sage", paper: "#eef0e6", paper2: "#dfe3d2", ink: "#2e4a3a", inkSoft: "#5f7566", accent: "#2e4a3a", accent2: "#b08a3c", foil: "copper", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "terracotta", label: "Terracotta", paper: "#f6ede3", paper2: "#eaddcc", ink: "#9a3f24", inkSoft: "#a87561", accent: "#9a3f24", accent2: "#c9a24a", foil: "gold", surface: "#6b4a2e", surface2: "#3f2a19" }),
    ],
  }),
  biz("holo-prism", "Holo Prism", "Holographic foil that shifts colour as you tilt", { design: "holo", enter: "spin", flip: "spin", thick: 3, radius: 14, edge: "#d9d6e4" }, {
    paper: "matte",
    backdrop: "slate",
    fonts: F("--f-syne", "--f-syne", "--f-manrope"),
    industries: ["Creative & Design", "Tech & Startups"],
    styles: ["Creative", "Modern"],
    effects: ["Holographic", "Glitter"],
    palettes: [
      BP({ id: "pearl", label: "Pearl", paper: "#f4f3f7", paper2: "#e4e2eb", ink: "#17171f", inkSoft: "#65657a", accent: "#8a7dff", accent2: "#ff8ad8", foil: "silver", surface: "#1b1d24", surface2: "#3a3f4d" }),
      BP({ id: "onyx", label: "Onyx", paper: "#121216", paper2: "#1d1d24", ink: "#f2f2f6", inkSoft: "#9b9bab", accent: "#7ef0ff", accent2: "#ff7ad9", foil: "silver", surface: "#0c0d10", surface2: "#272b35" }),
      BP({ id: "lilac", label: "Lilac", paper: "#e7e0f6", paper2: "#d4c9ee", ink: "#261f3d", inkSoft: "#5f5580", accent: "#b39cff", accent2: "#7ad7ff", foil: "silver", surface: "#1d1830", surface2: "#3d3360" }),
    ],
  }),
  biz("titan-metal", "Titan Metal", "Brushed metal card, laser-etched", { design: "metal", enter: "slide", flip: "heavy", thick: 6, radius: 18, edge: "metal" }, {
    paper: "matte",
    backdrop: "felt",
    fonts: F("--f-michroma", "--f-michroma", "--f-manrope"),
    industries: ["Finance & Legal", "Luxury & Jewellery"],
    styles: ["Luxury", "Corporate"],
    effects: ["Metal", "Laser etched"],
    palettes: [
      BP({ id: "steel", label: "Steel", paper: "#c3c7cd", paper2: "#8f949b", ink: "#23262b", inkSoft: "#454951", accent: "#9aa0a8", accent2: "#5b6068", foil: "silver", surface: "#1f2023", surface2: "#3b3c41" }),
      BP({ id: "black", label: "Black Titanium", paper: "#2c2d31", paper2: "#18191c", ink: "#e3e5e9", inkSoft: "#a3a6ad", accent: "#40424a", accent2: "#c9a24a", foil: "silver", surface: "#2a2620", surface2: "#4a4237" }),
      BP({ id: "gold", label: "24K Gold", paper: "#dcb866", paper2: "#a8812e", ink: "#3c2a09", inkSoft: "#5e4516", accent: "#c79b3f", accent2: "#7a5a1c", foil: "gold", surface: "#1d1b22", surface2: "#39343f" }),
      BP({ id: "rose", label: "Rose Gold", paper: "#dfab9c", paper2: "#b37a6d", ink: "#45221d", inkSoft: "#6b3d36", accent: "#cf9383", accent2: "#84463f", foil: "rosegold", surface: "#211c20", surface2: "#40363d" }),
    ],
  }),
  biz("walnut-engrave", "Walnut Engrave", "Real wood veneer, laser-burned by hand", { design: "walnut", enter: "burn", flip: "vertical", thick: 5, radius: 8, edge: "wood" }, {
    paper: "matte",
    backdrop: "linen",
    fonts: F("--f-fraunces", "--f-fraunces", "--f-josefin"),
    industries: ["Architecture & Construction", "Retail & Shops"],
    styles: ["Craft", "Nature"],
    effects: ["Laser engraved", "Wood veneer"],
    palettes: [
      BP({ id: "walnut", label: "Walnut", paper: "#6e4428", paper2: "#472a17", ink: "#231106", inkSoft: "#2d170a", accent: "#e0b787", accent2: "#3a2011", foil: "copper", surface: "#e6ded0", surface2: "#c7baa5" }),
      BP({ id: "maple", label: "Maple", paper: "#e2c393", paper2: "#c9a26c", ink: "#4a2710", inkSoft: "#5c3317", accent: "#8a5a2c", accent2: "#6b3f1c", foil: "copper", surface: "#d9d4ca", surface2: "#aea596" }),
      BP({ id: "teak", label: "Teak", paper: "#a1652f", paper2: "#744419", ink: "#2c1404", inkSoft: "#3a1b07", accent: "#f0c48b", accent2: "#4a2610", foil: "copper", surface: "#e3ddd2", surface2: "#bdb2a0" }),
    ],
  }),
  biz("clear-acrylic", "Clear Acrylic", "See-through acrylic with polished glowing edges", { design: "acrylic", enter: "rise", flip: "float", thick: 5, radius: 16, edge: "glass" }, {
    paper: "matte",
    backdrop: "studio",
    fonts: F("--f-outfit", "--f-outfit", "--f-outfit"),
    industries: ["Tech & Startups", "Creative & Design"],
    styles: ["Modern", "Minimal"],
    effects: ["Transparent", "Glowing edges"],
    palettes: [
      BP({ id: "ice", label: "Ice", paper: "#e8f6ff", paper2: "#c9e6f7", ink: "#0e2a44", inkSoft: "#3f5e78", accent: "#5aa9e6", accent2: "#ff9ec7", foil: "silver", surface: "#ffc7dc", surface2: "#9ecbff" }),
      BP({ id: "smoke", label: "Smoke", paper: "#3a3f47", paper2: "#262a31", ink: "#ffffff", inkSoft: "#c9ced6", accent: "#8ad8ff", accent2: "#c29bff", foil: "silver", surface: "#6f7cff", surface2: "#ff8fb1" }),
      BP({ id: "amber", label: "Amber", paper: "#ffd89a", paper2: "#f4b95a", ink: "#3d2106", inkSoft: "#6d4415", accent: "#ff8a3d", accent2: "#ffd23f", foil: "gold", surface: "#8fd6c9", surface2: "#f7a8c4" }),
    ],
  }),
  biz("neon-sign", "Neon Sign", "Glowing neon tubes on a matte black card", { design: "neon", enter: "neon", flip: "glitch", thick: 3, radius: 12, edge: "#1e1c22" }, {
    paper: "matte",
    backdrop: "concrete",
    fonts: F("--f-tilt-neon", "--f-tilt-neon", "--f-space"),
    industries: ["Food & Café", "Music & Events"],
    styles: ["Creative", "Playful"],
    effects: ["Neon glow", "Glitch"],
    palettes: [
      BP({ id: "pink", label: "Hot Pink", paper: "#141217", paper2: "#1e1b23", ink: "#ff5fd9", inkSoft: "#b6afc2", accent: "#44f2ff", accent2: "#ff5fd9", foil: "silver", surface: "#1b1b1e", surface2: "#34343a" }),
      BP({ id: "amber", label: "Amber", paper: "#151312", paper2: "#201c1a", ink: "#ffb84a", inkSoft: "#bfb3a6", accent: "#ff5a3c", accent2: "#ffb84a", foil: "gold", surface: "#1c1b1a", surface2: "#36332f" }),
      BP({ id: "lime", label: "Acid Lime", paper: "#111413", paper2: "#1a1f1d", ink: "#b8ff47", inkSoft: "#adbab2", accent: "#47d7ff", accent2: "#b8ff47", foil: "silver", surface: "#191b1b", surface2: "#323636" }),
    ],
  }),
  biz("jaipur-block", "Jaipur Block", "Hand block-printed buti border on handmade paper", { design: "block", enter: "block", flip: "hinge", thick: 3, radius: 4, edge: "#e8dcc3" }, {
    paper: "handmade",
    backdrop: "silk",
    fonts: F("--f-rozha", "--f-yatra", "--f-cormorant"),
    industries: ["Fashion & Textiles", "Retail & Shops"],
    styles: ["Traditional", "Craft"],
    effects: ["Block print", "Handmade paper"],
    palettes: [
      BP({ id: "indigo", label: "Indigo Dabu", paper: "#f3ead8", paper2: "#e3d4b6", ink: "#1f2f5c", inkSoft: "#4d5a80", accent: "#1f2f5c", accent2: "#b5452b", foil: "gold", surface: "#23305c", surface2: "#3d4f8a" }),
      BP({ id: "madder", label: "Sanganeri Red", paper: "#f7eedc", paper2: "#e8d7b8", ink: "#7c1d18", inkSoft: "#8a4a3c", accent: "#7c1d18", accent2: "#2b2b2b", foil: "gold", surface: "#5e1414", surface2: "#8f2a22" }),
      BP({ id: "kesari", label: "Kesari", paper: "#f8e6bd", paper2: "#eccf90", ink: "#6a2c0c", inkSoft: "#8a5230", accent: "#c2440f", accent2: "#2f5d3a", foil: "gold", surface: "#6e2a0c", surface2: "#a8481a" }),
    ],
  }),
  biz("paper-layers", "Paper Layers", "Die-cut paper layers with real depth", { design: "layers", enter: "stack", flip: "tumble", thick: 4, radius: 10, edge: "#f4f1ea" }, {
    paper: "matte",
    backdrop: "paper",
    fonts: F("--f-dm-serif", "--f-dm-serif", "--f-manrope"),
    industries: ["Travel & Outdoors", "Creative & Design"],
    styles: ["Creative", "Nature"],
    effects: ["Layered 3D", "Parallax"],
    palettes: [
      BP({ id: "ocean", label: "Ocean", paper: "#eef6f8", paper2: "#d6e9ef", ink: "#0f3140", inkSoft: "#3d6070", accent: "#8fd0e0", accent2: "#0f3a52", foil: "silver", surface: "#dfe8ea", surface2: "#b9cacf" }),
      BP({ id: "sunset", label: "Sunset", paper: "#fff3e8", paper2: "#fbe0cc", ink: "#4a1d1f", inkSoft: "#7a4a47", accent: "#ffc59a", accent2: "#9c2f55", foil: "rosegold", surface: "#f0e2d8", surface2: "#d6bfb0" }),
      BP({ id: "forest", label: "Forest", paper: "#f1f5ea", paper2: "#dde7d0", ink: "#1f3a24", inkSoft: "#4b6650", accent: "#b9dca0", accent2: "#1c4529", foil: "gold", surface: "#e3e8dc", surface2: "#bfcab4" }),
      BP({ id: "dusk", label: "Dusk", paper: "#f1ecf8", paper2: "#ddd3ee", ink: "#2b2245", inkSoft: "#5c5278", accent: "#d4c4f0", accent2: "#2e2560", foil: "silver", surface: "#e4e0ec", surface2: "#c1b9d1" }),
    ],
  }),
  biz("swiss-grid", "Swiss Grid", "Bold typographic grid with spot-gloss accent", { design: "swiss", enter: "typeset", flip: "swap", thick: 3, radius: 4, edge: "#e7e5df" }, {
    paper: "matte",
    backdrop: "paper",
    fonts: F("--f-archivo", "--f-archivo", "--f-archivo"),
    industries: ["Finance & Legal", "Tech & Startups", "Any business"],
    styles: ["Minimal", "Corporate", "Modern"],
    effects: ["Kinetic type", "Spot gloss"],
    palettes: [
      BP({ id: "red", label: "Swiss Red", paper: "#f5f3ee", paper2: "#e9e6de", ink: "#121212", inkSoft: "#5a5a5a", accent: "#e4312b", accent2: "#121212", foil: "silver", surface: "#e2e0dc", surface2: "#bebbb5" }),
      BP({ id: "klein", label: "Klein Blue", paper: "#f4f4f1", paper2: "#e7e7e2", ink: "#101020", inkSoft: "#55556a", accent: "#1f3fd6", accent2: "#101020", foil: "silver", surface: "#dfe0e4", surface2: "#b8bac2" }),
      BP({ id: "lime", label: "Black & Lime", paper: "#151515", paper2: "#0d0d0d", ink: "#f2f2f2", inkSoft: "#9a9a9a", accent: "#c8f542", accent2: "#f2f2f2", foil: "silver", surface: "#d9d9d6", surface2: "#aeaeaa" }),
      BP({ id: "orange", label: "Orange", paper: "#f6f2ea", paper2: "#ebe5d9", ink: "#1b1510", inkSoft: "#5e554c", accent: "#ff6a1a", accent2: "#1b1510", foil: "silver", surface: "#e4dfd6", surface2: "#c0b8ab" }),
    ],
  }),
  biz("carrara-gold", "Carrara Gold", "Marble stock with gilded gold edges", { design: "marble", enter: "gild", flip: "edge", thick: 6, radius: 8, edge: "foil" }, {
    paper: "matte",
    backdrop: "velvet",
    fonts: F("--f-bodoni", "--f-great-vibes", "--f-cormorant"),
    industries: ["Luxury & Jewellery", "Beauty & Wellness"],
    styles: ["Luxury", "Classic"],
    effects: ["Gilded edges", "Hot foil", "Marble"],
    palettes: [
      BP({ id: "carrara", label: "Carrara", paper: "#f3f1ed", paper2: "#dedad2", ink: "#3a3225", inkSoft: "#6f6554", accent: "#c9a24a", accent2: "#8c8478", foil: "gold", surface: "#1e1a24", surface2: "#3b3246" }),
      BP({ id: "nero", label: "Nero Marquina", paper: "#1c1c1e", paper2: "#0d0d0e", ink: "#efe6cf", inkSoft: "#a99f88", accent: "#c9a24a", accent2: "#e8e4dc", foil: "gold", surface: "#2a1c1c", surface2: "#4a2f2f" }),
      BP({ id: "verde", label: "Verde Guatemala", paper: "#1f3d33", paper2: "#10261e", ink: "#f0e6cc", inkSoft: "#b5c2ab", accent: "#c9a24a", accent2: "#dfe8df", foil: "gold", surface: "#1a1a22", surface2: "#34343f" }),
      BP({ id: "rosa", label: "Rosa", paper: "#f0dcd5", paper2: "#dcbdb2", ink: "#5a3431", inkSoft: "#8a615c", accent: "#cf9383", accent2: "#a88a84", foil: "rosegold", surface: "#231c22", surface2: "#46384a" }),
    ],
  }),
  biz("kraft-stamp", "Kraft & Stamp", "Recycled kraft with hand rubber-stamped ink", { design: "kraft", enter: "slam", flip: "toss", thick: 4, radius: 6, edge: "#b58c60" }, {
    paper: "matte",
    backdrop: "wood",
    fonts: F("--f-special-elite", "--f-caveat", "--f-special-elite"),
    industries: ["Food & Café", "Retail & Shops"],
    styles: ["Craft", "Nature", "Playful"],
    effects: ["Rubber stamp", "Recycled paper"],
    palettes: [
      BP({ id: "kraft", label: "Kraft", paper: "#c49b6c", paper2: "#a57c50", ink: "#231a12", inkSoft: "#3b2d1f", accent: "#b3261e", accent2: "#231a12", foil: "copper", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "grey", label: "Recycled Grey", paper: "#d2cdc3", paper2: "#b9b3a6", ink: "#1e2a45", inkSoft: "#3a4560", accent: "#d0482f", accent2: "#1e2a45", foil: "silver", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "olive", label: "Olive", paper: "#cdb98a", paper2: "#b39d6a", ink: "#2d3f1c", inkSoft: "#44552e", accent: "#b8481a", accent2: "#2d3f1c", foil: "copper", surface: "#6b4a2e", surface2: "#3f2a19" }),
    ],
  }),

  /* ============================ trend collection ============================ */
  biz("aurora-mesh", "Aurora Mesh", "Glowing mesh gradient that drifts as you tilt", { design: "aurora", enter: "bloom", flip: "pop", thick: 3, radius: 18, edge: "#1a1c2e" }, {
    paper: "matte",
    backdrop: "slate",
    fonts: F("--f-sora", "--f-sora", "--f-sora"),
    styles: ["Modern", "Creative"],
    effects: ["Mesh gradient", "Tilt-reactive"],
    industries: ["Tech & Startups", "Creative & Design"],
    palettes: [
      BP({ id: "night", label: "Northern Lights", paper: "#0d1020", paper2: "#1b2040", ink: "#ffffff", inkSoft: "#7ef0c6", accent: "#6c5cff", accent2: "#00d4a6", foil: "silver", surface: "#07080f", surface2: "#1c1f33" }),
      BP({ id: "peach", label: "Peach Fuzz", paper: "#2a1320", paper2: "#ffb38a", ink: "#ffffff", inkSoft: "#ffd6c2", accent: "#ff7a59", accent2: "#ff4f9a", foil: "rosegold", surface: "#1a0c12", surface2: "#3a1d2a" }),
      BP({ id: "ocean", label: "Deep Ocean", paper: "#051a2b", paper2: "#0b3b5c", ink: "#ffffff", inkSoft: "#8fe3ff", accent: "#0077ff", accent2: "#00e0ff", foil: "silver", surface: "#030d16", surface2: "#0c2233" }),
    ],
  }),
  biz("sunset-glow", "Sunset Glow", "Vertical card in warm golden-hour gradients", { design: "sunset", enter: "draw", flip: "vertical", thick: 3, radius: 14, edge: "#f3c7a8", shape: "portrait" }, {
    paper: "matte",
    backdrop: "paper",
    fonts: F("--f-fraunces", "--f-fraunces", "--f-jost"),
    styles: ["Modern", "Creative"],
    effects: ["Gradient", "Vertical card"],
    industries: ["Creative & Design", "Beauty & Wellness", "Travel & Outdoors"],
    palettes: [
      BP({ id: "golden", label: "Golden Hour", paper: "#ffcf9e", paper2: "#c2416b", ink: "#3a1020", inkSoft: "#7a3a4a", accent: "#ff8a5b", accent2: "#7b2cbf", foil: "rosegold", surface: "#ece3da", surface2: "#cbbcae" }),
      BP({ id: "lavender", label: "Lavender Dusk", paper: "#e7d7ff", paper2: "#4b3b8f", ink: "#1f1640", inkSoft: "#5a4b8a", accent: "#b983ff", accent2: "#3d5afe", foil: "silver", surface: "#e4e0ec", surface2: "#c1b9d1" }),
      BP({ id: "tropic", label: "Tropic", paper: "#fff1b8", paper2: "#0e7c7b", ink: "#0b3030", inkSoft: "#2f6b6a", accent: "#ffb703", accent2: "#06d6a0", foil: "gold", surface: "#e3eee6", surface2: "#bcd3c6" }),
    ],
  }),
  biz("glass-orbit", "Glass Orbit", "Glassmorphism panel over glossy 3D orbs", { design: "glass", enter: "bloom", flip: "float", thick: 3, radius: 22, edge: "rgba(255,255,255,.6)" }, {
    paper: "matte",
    backdrop: "studio",
    fonts: F("--f-outfit", "--f-outfit", "--f-outfit"),
    styles: ["Modern", "Playful"],
    effects: ["Glassmorphism", "3D orbs", "Parallax"],
    industries: ["Tech & Startups", "Finance & Legal"],
    palettes: [
      BP({ id: "violet", label: "Violet", paper: "#c8b6ff", paper2: "#7b5cff", ink: "#1a1036", inkSoft: "#4a3d78", accent: "#8f6bff", accent2: "#ff6fb5", foil: "silver", surface: "#e7dcff", surface2: "#ffd1e8" }),
      BP({ id: "mint", label: "Mint", paper: "#b8f2e6", paper2: "#3ab7a4", ink: "#0d2b27", inkSoft: "#35665f", accent: "#2ec4b6", accent2: "#ffbf69", foil: "silver", surface: "#d9f7f1", surface2: "#fde4c4" }),
      BP({ id: "sky", label: "Sky", paper: "#bfe3ff", paper2: "#4a8dff", ink: "#0c1f3d", inkSoft: "#3b5680", accent: "#4a8dff", accent2: "#ffd166", foil: "silver", surface: "#dbeeff", surface2: "#fff0c9" }),
    ],
  }),
  biz("bento-grid", "Bento Grid", "Rounded tiles: brand, services, QR and more on the front", { design: "bento", enter: "cascade", flip: "pop", thick: 3, radius: 22, edge: "#d9d9de" }, {
    paper: "matte",
    backdrop: "paper",
    fonts: F("--f-jakarta", "--f-jakarta", "--f-jakarta"),
    styles: ["Modern", "Minimal"],
    effects: ["Bento layout", "More info on front"],
    industries: ["Creative & Design", "Tech & Startups", "Any business"],
    palettes: [
      BP({ id: "cobalt", label: "Cobalt", paper: "#ffffff", paper2: "#eceef3", ink: "#14161c", inkSoft: "#6a6f7c", accent: "#2f5bff", accent2: "#14161c", foil: "silver", surface: "#e4e6ea", surface2: "#c4c8cf" }),
      BP({ id: "tangerine", label: "Tangerine", paper: "#fffdf8", paper2: "#f1ebe1", ink: "#1f1a14", inkSoft: "#7a6f60", accent: "#ff6b2c", accent2: "#1f1a14", foil: "silver", surface: "#ece6dc", surface2: "#cfc6b8" }),
      BP({ id: "forest", label: "Forest", paper: "#fbfcf8", paper2: "#e5eadf", ink: "#17231a", inkSoft: "#5d6b5f", accent: "#1f7a4d", accent2: "#17231a", foil: "silver", surface: "#e3e8dc", surface2: "#bfcab4" }),
    ],
  }),
  biz("neo-brutal", "Neo Brutal", "Thick outlines, hard shadows, loud colour", { design: "brutal", enter: "zoom", flip: "swap", thick: 3, radius: 8, edge: "#111" }, {
    paper: "matte",
    backdrop: "paper",
    fonts: F("--f-archivo", "--f-archivo", "--f-space-mono"),
    styles: ["Playful", "Creative"],
    effects: ["Neo-brutalism", "Sticker"],
    industries: ["Creative & Design", "Food & Café", "Retail & Shops"],
    palettes: [
      BP({ id: "lemon", label: "Lemon", paper: "#fffdf5", paper2: "#fff4c7", ink: "#111111", inkSoft: "#444444", accent: "#ffd23f", accent2: "#ff6b9a", foil: "silver", surface: "#e9e6de", surface2: "#c8c3b8" }),
      BP({ id: "bubblegum", label: "Bubblegum", paper: "#ffffff", paper2: "#ffe3ef", ink: "#111111", inkSoft: "#444444", accent: "#ff90c2", accent2: "#7df9c3", foil: "silver", surface: "#ece6ea", surface2: "#cdc3c9" }),
      BP({ id: "electric", label: "Electric", paper: "#ffffff", paper2: "#e3ecff", ink: "#111111", inkSoft: "#444444", accent: "#5b8cff", accent2: "#ffd23f", foil: "silver", surface: "#e3e6ee", surface2: "#c0c6d4" }),
    ],
  }),
  biz("chrome-y2k", "Chrome Y2K", "Liquid chrome and sparkles, straight from 2000", { design: "chrome", enter: "zoom", flip: "spin", thick: 3, radius: 16, edge: "metal" }, {
    paper: "matte",
    backdrop: "slate",
    fonts: F("--f-unbounded", "--f-unbounded", "--f-jakarta"),
    styles: ["Creative", "Playful"],
    effects: ["Chrome", "Sparkle"],
    industries: ["Music & Events", "Fashion & Textiles", "Creative & Design"],
    palettes: [
      BP({ id: "void", label: "Void", paper: "#0b0b12", paper2: "#c0c6d4", ink: "#e9ecf5", inkSoft: "#9aa3b8", accent: "#8a5cff", accent2: "#00e5ff", foil: "silver", surface: "#07070b", surface2: "#1d1d2b" }),
      BP({ id: "candy", label: "Candy", paper: "#1a0b1f", paper2: "#e8c6ff", ink: "#f7ecff", inkSoft: "#d3a6ff", accent: "#ff4fd8", accent2: "#7d5cff", foil: "silver", surface: "#0e0612", surface2: "#2b1233" }),
    ],
  }),
  biz("groovy-70s", "Groovy 70s", "Retro rainbow arcs and wavy lines", { design: "groovy", enter: "draw", flip: "toss", thick: 4, radius: 12, edge: "#e8d6b0" }, {
    paper: "matte",
    backdrop: "wood",
    fonts: F("--f-shrikhand", "--f-shrikhand", "--f-jost"),
    styles: ["Playful", "Retro"],
    effects: ["Retro", "Line drawing"],
    industries: ["Retail & Shops", "Food & Café", "Music & Events"],
    palettes: [
      BP({ id: "sunny", label: "Sunny", paper: "#f6e7c8", paper2: "#e9d3a8", ink: "#5a2e16", inkSoft: "#8a5a3a", accent: "#e8583b", accent2: "#f2a93b", foil: "copper", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "avocado", label: "Avocado", paper: "#efe6cc", paper2: "#dcd0ae", ink: "#3b3a16", inkSoft: "#6d6a3c", accent: "#8a9a3b", accent2: "#e3a72f", foil: "gold", surface: "#6b4a2e", surface2: "#3f2a19" }),
    ],
  }),
  biz("gatsby-deco", "Gatsby Deco", "Vertical Art Deco with a gold sunburst", { design: "deco", enter: "gild", flip: "edge", thick: 5, radius: 6, edge: "foil", shape: "portrait" }, {
    paper: "matte",
    backdrop: "velvet",
    fonts: F("--f-limelight", "--f-limelight", "--f-poiret"),
    styles: ["Luxury", "Classic"],
    effects: ["Hot foil", "Gilded edges", "Vertical card"],
    industries: ["Food & Café", "Luxury & Jewellery", "Music & Events"],
    palettes: [
      BP({ id: "onyx", label: "Onyx & Gold", paper: "#101010", paper2: "#1d1d1d", ink: "#f1e6c8", inkSoft: "#b8a77f", accent: "#c9a24a", accent2: "#333", foil: "gold", surface: "#1a1410", surface2: "#3a2c20" }),
      BP({ id: "emerald", label: "Emerald", paper: "#0b3a2e", paper2: "#0f4d3d", ink: "#f1e6c8", inkSoft: "#bcb08a", accent: "#c9a24a", accent2: "#052018", foil: "gold", surface: "#061a14", surface2: "#12342a" }),
    ],
  }),
  biz("zen-enso", "Zen Ensō", "Square card with a sumi brush circle and red hanko", { design: "enso", enter: "draw", flip: "classic", thick: 3, radius: 6, edge: "#e9e1d0", shape: "square" }, {
    paper: "matte",
    backdrop: "linen",
    fonts: F("--f-shippori", "--f-shippori", "--f-jost"),
    styles: ["Minimal", "Nature"],
    effects: ["Brush ink", "Square card"],
    industries: ["Beauty & Wellness", "Creative & Design"],
    palettes: [
      BP({ id: "washi", label: "Washi", paper: "#f4eee2", paper2: "#e5dcc8", ink: "#1b1b1b", inkSoft: "#5a564d", accent: "#c0392b", accent2: "#1b1b1b", foil: "gold", surface: "#e6ded0", surface2: "#c7baa5" }),
      BP({ id: "sumi", label: "Sumi", paper: "#1d1c1a", paper2: "#2a2926", ink: "#f1ece2", inkSoft: "#b5ad9e", accent: "#d64533", accent2: "#f1ece2", foil: "gold", surface: "#e6ded0", surface2: "#c7baa5" }),
    ],
  }),
  biz("mono-minimal", "Mono Minimal", "Vertical, quiet, mostly white space", { design: "mono", enter: "wipe", flip: "deal", thick: 3, radius: 4, edge: "#e6e4df", shape: "portrait" }, {
    paper: "matte",
    backdrop: "paper",
    fonts: F("--f-jost", "--f-jost", "--f-jost"),
    styles: ["Minimal"],
    effects: ["Vertical card", "Whitespace"],
    industries: ["Architecture & Construction", "Creative & Design", "Any business"],
    palettes: [
      BP({ id: "white", label: "Paper White", paper: "#fbfaf7", paper2: "#f0eee8", ink: "#161616", inkSoft: "#7a7a7a", accent: "#161616", accent2: "#161616", foil: "silver", surface: "#e4e2dd", surface2: "#bfbcb5" }),
      BP({ id: "charcoal", label: "Charcoal", paper: "#1c1c1c", paper2: "#262626", ink: "#f2f2f2", inkSoft: "#9b9b9b", accent: "#f2f2f2", accent2: "#f2f2f2", foil: "silver", surface: "#e4e2dd", surface2: "#bfbcb5" }),
      BP({ id: "clay", label: "Clay", paper: "#efe4d8", paper2: "#e5d7c7", ink: "#3b2a20", inkSoft: "#8a7362", accent: "#b5623e", accent2: "#3b2a20", foil: "copper", surface: "#e4dcd2", surface2: "#c4b6a6" }),
    ],
  }),
  biz("topo-lines", "Topo Lines", "Real contour lines, drawn as the card arrives", { design: "topo", enter: "draw", flip: "lift", thick: 4, radius: 10, edge: "#243a2e" }, {
    paper: "matte",
    backdrop: "linen",
    fonts: F("--f-space", "--f-space", "--f-space"),
    styles: ["Nature", "Modern"],
    effects: ["Contour lines", "Line drawing"],
    industries: ["Travel & Outdoors", "Architecture & Construction"],
    palettes: [
      BP({ id: "forest", label: "Forest", paper: "#1d2b24", paper2: "#26382e", ink: "#eef3ea", inkSoft: "#a9bba9", accent: "#c7e37b", accent2: "#eef3ea", foil: "silver", surface: "#e3e8dc", surface2: "#bfcab4" }),
      BP({ id: "sand", label: "Sand", paper: "#efe5d2", paper2: "#e3d5bb", ink: "#2d2419", inkSoft: "#7a6a52", accent: "#b5623e", accent2: "#2d2419", foil: "copper", surface: "#e6ded0", surface2: "#c7baa5" }),
      BP({ id: "glacier", label: "Glacier", paper: "#0f2233", paper2: "#163247", ink: "#eaf5ff", inkSoft: "#94b6cf", accent: "#6fd3ff", accent2: "#eaf5ff", foil: "silver", surface: "#dfe8ea", surface2: "#b9cacf" }),
    ],
  }),
  biz("terrazzo", "Terrazzo", "Speckled stone chips around a soft label", { design: "terrazzo", enter: "bloom", flip: "pop", thick: 4, radius: 12, edge: "#e9e2d6" }, {
    paper: "matte",
    backdrop: "paper",
    fonts: F("--f-dm-serif", "--f-dm-serif", "--f-jost"),
    styles: ["Playful", "Modern"],
    effects: ["Terrazzo", "Pattern"],
    industries: ["Architecture & Construction", "Food & Café", "Creative & Design"],
    palettes: [
      BP({ id: "classic", label: "Classic", paper: "#f3ece1", paper2: "#e8dfd1", ink: "#2b2622", inkSoft: "#7a6f64", accent: "#e07a5f", accent2: "#3d8b7d", foil: "silver", surface: "#e6dfd4", surface2: "#c4bbad" }),
      BP({ id: "pastel", label: "Pastel", paper: "#fbf6f0", paper2: "#efe6dc", ink: "#2d2a40", inkSoft: "#7a7690", accent: "#f4a6b8", accent2: "#8ec5e8", foil: "silver", surface: "#ece6e1", surface2: "#cbc3bd" }),
    ],
  }),
  biz("memphis-pop", "Memphis Pop", "80s squiggles, dots and confetti", { design: "memphis", enter: "bloom", flip: "toss", thick: 3, radius: 10, edge: "#f1f1f1" }, {
    paper: "matte",
    backdrop: "paper",
    fonts: F("--f-righteous", "--f-righteous", "--f-jakarta"),
    styles: ["Playful", "Retro"],
    effects: ["Memphis", "Pattern"],
    industries: ["Creative & Design", "Education", "Music & Events"],
    palettes: [
      BP({ id: "classic", label: "Classic", paper: "#fffdf7", paper2: "#fff4e0", ink: "#1b1b2b", inkSoft: "#555", accent: "#ff5c8a", accent2: "#2ec4f1", foil: "silver", surface: "#ece8df", surface2: "#cbc5b8" }),
      BP({ id: "mint", label: "Mint Pop", paper: "#e9fbf4", paper2: "#d4f5e8", ink: "#1b1b2b", inkSoft: "#555", accent: "#ff7a3d", accent2: "#7a5cff", foil: "silver", surface: "#e0ece6", surface2: "#bccbc3" }),
    ],
  }),
  biz("duotone-photo", "Duotone Photo", "Full-bleed photo in two bold colours", { design: "duotone", enter: "wipe", flip: "deal", thick: 3, radius: 10, edge: "#222" }, {
    paper: "matte",
    backdrop: "slate",
    photo: true,
    fonts: F("--f-anton", "--f-anton", "--f-jakarta"),
    styles: ["Creative", "Modern"],
    effects: ["Duotone photo", "Photo"],
    industries: ["Creative & Design", "Music & Events", "Fashion & Textiles"],
    palettes: [
      BP({ id: "berry", label: "Berry & Navy", paper: "#fff5f8", paper2: "#ffe0ea", ink: "#1b1033", inkSoft: "#6a5a86", accent: "#ff4d8d", accent2: "#1b1033", foil: "silver", surface: "#10101a", surface2: "#2a2a3a" }),
      BP({ id: "acid", label: "Acid & Ink", paper: "#fbffe8", paper2: "#f0ffc2", ink: "#0f1a2b", inkSoft: "#4f5d70", accent: "#d4ff3a", accent2: "#233a8f", foil: "silver", surface: "#10101a", surface2: "#2a2a3a" }),
      BP({ id: "sunset", label: "Orange & Plum", paper: "#fff6ee", paper2: "#ffe4cc", ink: "#2b0f24", inkSoft: "#7a5068", accent: "#ff8a3d", accent2: "#4b1248", foil: "silver", surface: "#10101a", surface2: "#2a2a3a" }),
    ],
  }),

  /* ============================ Indian heritage ============================ */
  biz("warli-village", "Warli Village", "Warli tarpa dance on red-ochre mud wall", { design: "warli", enter: "draw", flip: "vertical", thick: 4, radius: 8, edge: "#7a2e18" }, {
    paper: "matte",
    backdrop: "linen",
    fonts: F("--f-rozha", "--f-kalam", "--f-kalam"),
    styles: ["Traditional", "Craft"],
    effects: ["Folk art", "Line drawing"],
    industries: ["Fashion & Textiles", "Retail & Shops", "Food & Café", "Creative & Design"],
    palettes: [
      BP({ id: "geru", label: "Geru Red", paper: "#9c3f22", paper2: "#7a2e18", ink: "#f6efe2", inkSoft: "#f0d9c0", accent: "#f6efe2", accent2: "#f6efe2", foil: "gold", surface: "#e6ded0", surface2: "#c7baa5" }),
      BP({ id: "mud", label: "Mud Brown", paper: "#5d4032", paper2: "#3f2a20", ink: "#f6efe2", inkSoft: "#e3d3bd", accent: "#f6efe2", accent2: "#f6efe2", foil: "gold", surface: "#e6ded0", surface2: "#c7baa5" }),
      BP({ id: "indigo", label: "Night Indigo", paper: "#232f55", paper2: "#18213f", ink: "#f6efe2", inkSoft: "#cfd6ea", accent: "#f6efe2", accent2: "#f6efe2", foil: "gold", surface: "#e6ded0", surface2: "#c7baa5" }),
    ],
  }),
  biz("mughal-jaali", "Mughal Jaali", "Pierced sandstone lattice with a pointed arch", { design: "jaali", enter: "draw", flip: "lift", thick: 5, radius: 4, edge: "#b88660" }, {
    paper: "matte",
    backdrop: "silk",
    fonts: F("--f-cinzel", "--f-cinzel", "--f-cormorant"),
    styles: ["Traditional", "Luxury"],
    effects: ["Lattice", "Line drawing"],
    industries: ["Luxury & Jewellery", "Food & Café", "Retail & Shops"],
    palettes: [
      BP({ id: "sandstone", label: "Red Sandstone", paper: "#c47a52", paper2: "#6e3420", ink: "#4a1d12", inkSoft: "#8a5a44", accent: "#6e3420", accent2: "#c9a24a", foil: "gold", surface: "#4a1d12", surface2: "#7a3520" }),
      BP({ id: "marble", label: "Makrana Marble", paper: "#efe9df", paper2: "#b8ab95", ink: "#3b3226", inkSoft: "#7a6d5a", accent: "#8a6d3b", accent2: "#c9a24a", foil: "gold", surface: "#2a2320", surface2: "#4a3d33" }),
    ],
  }),
  biz("bandhani", "Bandhani", "Tie-dye dot clusters from Kutch and Jamnagar", { design: "bandhani", enter: "bloom", flip: "classic", thick: 3, radius: 6, edge: "#8a1024" }, {
    paper: "matte",
    backdrop: "silk",
    fonts: F("--f-yeseva", "--f-yeseva", "--f-cormorant"),
    styles: ["Traditional", "Festive"],
    effects: ["Tie-dye dots", "Pattern"],
    industries: ["Fashion & Textiles", "Retail & Shops", "Events & Weddings"],
    palettes: [
      BP({ id: "red", label: "Laal", paper: "#b01c33", paper2: "#7c0f22", ink: "#5c0f1a", inkSoft: "#8a3a44", accent: "#ffd23f", accent2: "#fff4dc", foil: "gold", surface: "#5c0f1a", surface2: "#8a1a2a" }),
      BP({ id: "green", label: "Hara", paper: "#1e6b43", paper2: "#12462b", ink: "#12462b", inkSoft: "#3f6b52", accent: "#ffcf3f", accent2: "#fff6dc", foil: "gold", surface: "#0e2b1c", surface2: "#1e4a33" }),
      BP({ id: "pink", label: "Rani", paper: "#d6246e", paper2: "#9c1250", ink: "#7a0f3f", inkSoft: "#a3456f", accent: "#ffe066", accent2: "#fff1f6", foil: "gold", surface: "#4a0a26", surface2: "#7a1a44" }),
    ],
  }),
  biz("ajrakh", "Ajrakh", "Indigo and madder star tiles, block printed", { design: "ajrakh", enter: "block", flip: "hinge", thick: 3, radius: 4, edge: "#1c2340" }, {
    paper: "matte",
    backdrop: "linen",
    fonts: F("--f-rozha", "--f-rozha", "--f-cormorant"),
    styles: ["Traditional", "Craft"],
    effects: ["Block print", "Geometric"],
    industries: ["Fashion & Textiles", "Retail & Shops"],
    palettes: [
      BP({ id: "indigo", label: "Indigo & Madder", paper: "#1c2340", paper2: "#2b3560", ink: "#f4ecdc", inkSoft: "#cfc4ad", accent: "#a4262c", accent2: "#f4ecdc", foil: "gold", surface: "#e6ded0", surface2: "#c7baa5" }),
      BP({ id: "madder", label: "Madder & Black", paper: "#7a1a1e", paper2: "#94252a", ink: "#f4ecdc", inkSoft: "#e3cdb5", accent: "#161616", accent2: "#f4ecdc", foil: "gold", surface: "#e6ded0", surface2: "#c7baa5" }),
    ],
  }),
  biz("kanjivaram-zari", "Kanjivaram Zari", "Silk sari with gold temple border, vertical", { design: "kanjivaram", enter: "gild", flip: "edge", thick: 4, radius: 6, edge: "foil", shape: "portrait" }, {
    paper: "matte",
    backdrop: "velvet",
    fonts: F("--f-cinzel", "--f-cinzel", "--f-cormorant"),
    styles: ["Traditional", "Luxury"],
    effects: ["Silk", "Hot foil", "Vertical card"],
    industries: ["Fashion & Textiles", "Luxury & Jewellery", "Events & Weddings"],
    palettes: [
      BP({ id: "magenta", label: "Magenta & Green", paper: "#8a1538", paper2: "#5c0c25", ink: "#fbead0", inkSoft: "#f1c9a8", accent: "#c9a24a", accent2: "#1f5e3a", foil: "gold", surface: "#2a0612", surface2: "#5a1428" }),
      BP({ id: "peacock", label: "Peacock & Mustard", paper: "#0f4c5c", paper2: "#08323d", ink: "#fbead0", inkSoft: "#d8c89e", accent: "#c9a24a", accent2: "#b8860b", foil: "gold", surface: "#061c22", surface2: "#12404c" }),
      BP({ id: "red", label: "Arakku Red", paper: "#9b1b1b", paper2: "#6a1010", ink: "#fbead0", inkSoft: "#f1c9a8", accent: "#c9a24a", accent2: "#2b2b6b", foil: "gold", surface: "#2a0808", surface2: "#5a1414" }),
    ],
  }),
  biz("kolam", "Kolam", "Rice-flour kolam woven around a dot grid", { design: "kolam", enter: "draw", flip: "vertical", thick: 3, radius: 8, edge: "#2a2d31" }, {
    paper: "matte",
    backdrop: "slate",
    fonts: F("--f-marcellus", "--f-marcellus", "--f-cormorant"),
    styles: ["Traditional", "Minimal"],
    effects: ["Line drawing", "Folk art"],
    industries: ["Food & Café", "Beauty & Wellness", "Retail & Shops"],
    palettes: [
      BP({ id: "slate", label: "Temple Floor", paper: "#1f2226", paper2: "#2c3036", ink: "#f7f3ea", inkSoft: "#cfc8ba", accent: "#f2a93b", accent2: "#f7f3ea", foil: "gold", surface: "#101215", surface2: "#2a2e33" }),
      BP({ id: "oxide", label: "Red Oxide", paper: "#7a2a1f", paper2: "#94352a", ink: "#f7f3ea", inkSoft: "#efd9c8", accent: "#ffd166", accent2: "#f7f3ea", foil: "gold", surface: "#2a0e0a", surface2: "#4a1c14" }),
      BP({ id: "cowdung", label: "Earth Green", paper: "#3d4a2f", paper2: "#4a5a38", ink: "#f7f3ea", inkSoft: "#dfe3cf", accent: "#ffb4a2", accent2: "#f7f3ea", foil: "gold", surface: "#161c10", surface2: "#2c3620" }),
    ],
  }),
  biz("madhubani", "Madhubani", "Mithila fish pair with a sawtooth border", { design: "madhubani", enter: "draw", flip: "hinge", thick: 3, radius: 4, edge: "#e9dcc0" }, {
    paper: "handmade",
    backdrop: "wood",
    fonts: F("--f-rozha", "--f-kalam", "--f-cormorant"),
    styles: ["Traditional", "Craft"],
    effects: ["Folk art", "Handmade paper"],
    industries: ["Creative & Design", "Fashion & Textiles", "Education"],
    palettes: [
      BP({ id: "classic", label: "Classic", paper: "#f3e7c9", paper2: "#e5d3a8", ink: "#1b1b1b", inkSoft: "#5a4a30", accent: "#c8102e", accent2: "#f2b705", foil: "gold", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "green", label: "Leaf & Pink", paper: "#f6ecd6", paper2: "#e8d8b4", ink: "#1b1b1b", inkSoft: "#5a4a30", accent: "#e0457b", accent2: "#3f8f4a", foil: "gold", surface: "#6b4a2e", surface2: "#3f2a19" }),
    ],
  }),
  biz("ribbon-seal", "Ribbon & Seal", "Satin ribbon and a pressed wax seal", { design: "seal", enter: "bloom", flip: "lift", thick: 4, radius: 6, edge: "#eadfcb" }, {
    paper: "cotton",
    backdrop: "velvet",
    fonts: F("--f-bodoni", "--f-great-vibes", "--f-cormorant"),
    styles: ["Luxury", "Classic"],
    effects: ["Wax seal", "Hot foil"],
    industries: ["Luxury & Jewellery", "Fashion & Textiles", "Events & Weddings"],
    palettes: [
      BP({ id: "ivory", label: "Ivory & Burgundy", paper: "#f7f1e6", paper2: "#ece2d0", ink: "#3a2a22", inkSoft: "#7a6554", accent: "#7d1020", accent2: "#a01830", foil: "gold", surface: "#2b090f", surface2: "#5a1320" }),
      BP({ id: "sage", label: "Sage & Forest", paper: "#eef0e6", paper2: "#dfe3d2", ink: "#2e3a2c", inkSoft: "#65705f", accent: "#2f5d3a", accent2: "#8fa382", foil: "gold", surface: "#16241a", surface2: "#2c4232" }),
      BP({ id: "blush", label: "Blush & Navy", paper: "#f8ebe6", paper2: "#eed5cd", ink: "#2b2f4a", inkSoft: "#6d6f86", accent: "#1f2a55", accent2: "#d8a7a0", foil: "rosegold", surface: "#161a30", surface2: "#2c3354" }),
    ],
  }),

  /* ============================ professions ============================ */
  biz("clinic-care", "Clinic Care", "For doctors: name first, heartbeat line, clinic hours", { design: "clinic", enter: "draw", flip: "classic", thick: 3, radius: 12, edge: "#e3eef0" }, {
    paper: "matte",
    backdrop: "paper",
    fonts: F("--f-dm-sans", "--f-dm-sans", "--f-dm-sans"),
    styles: ["Minimal", "Corporate"],
    effects: ["Line drawing"],
    industries: ["Doctors & Clinics", "Beauty & Wellness"],
    palettes: [
      BP({ id: "teal", label: "Teal", paper: "#ffffff", paper2: "#f1f7f7", ink: "#0f2a33", inkSoft: "#5b727a", accent: "#0f9b9b", accent2: "#0b6e8a", foil: "silver", surface: "#dfe8ea", surface2: "#b9cacf" }),
      BP({ id: "blue", label: "Hospital Blue", paper: "#ffffff", paper2: "#f0f4fb", ink: "#0f1f3d", inkSoft: "#5b6a86", accent: "#2d6cdf", accent2: "#153e8a", foil: "silver", surface: "#dfe4ee", surface2: "#b8c1d4" }),
      BP({ id: "green", label: "Care Green", paper: "#ffffff", paper2: "#f1f8f3", ink: "#12301f", inkSoft: "#5b7666", accent: "#2e9e5b", accent2: "#1c6b3d", foil: "silver", surface: "#e0ebe3", surface2: "#bccfc2" }),
    ],
  }),
  biz("advocate", "Advocate", "Black & white with the scales of justice", { design: "advocate", enter: "draw", flip: "vertical", thick: 3, radius: 4, edge: "#e6e6e6" }, {
    paper: "matte",
    backdrop: "slate",
    fonts: F("--f-garamond", "--f-garamond", "--f-montserrat"),
    styles: ["Classic", "Corporate"],
    effects: ["Line drawing"],
    industries: ["Finance & Legal"],
    palettes: [
      BP({ id: "white", label: "Court White", paper: "#fbfbf9", paper2: "#f0f0ec", ink: "#141414", inkSoft: "#5c5c5c", accent: "#141414", accent2: "#141414", foil: "silver", surface: "#1d1d1f", surface2: "#3a3a3e" }),
      BP({ id: "black", label: "Robe Black", paper: "#141414", paper2: "#1c1c1c", ink: "#f2f2ef", inkSoft: "#a3a3a0", accent: "#f2f2ef", accent2: "#f2f2ef", foil: "silver", surface: "#2a2c30", surface2: "#151619" }),
      BP({ id: "navy", label: "Navy & Gold", paper: "#121c33", paper2: "#1a2644", ink: "#f2ead8", inkSoft: "#b5ab93", accent: "#c9a24a", accent2: "#f2ead8", foil: "gold", surface: "#2a2c30", surface2: "#151619" }),
    ],
  }),
  biz("skyline-realty", "Skyline Realty", "City skyline where the windows light up", { design: "skyline", enter: "bloom", flip: "lift", thick: 4, radius: 10, edge: "#0f1b33" }, {
    paper: "matte",
    backdrop: "slate",
    fonts: F("--f-montserrat", "--f-montserrat", "--f-montserrat"),
    styles: ["Corporate", "Modern"],
    effects: ["Skyline", "Light-up windows"],
    industries: ["Real Estate", "Architecture & Construction"],
    palettes: [
      BP({ id: "night", label: "Night Gold", paper: "#0f1b33", paper2: "#24365e", ink: "#ffffff", inkSoft: "#c9d3e8", accent: "#f4c95d", accent2: "#ffffff", foil: "gold", surface: "#0a1122", surface2: "#1d2b4a" }),
      BP({ id: "dusk", label: "Dusk", paper: "#2b1d3a", paper2: "#e06c75", ink: "#ffffff", inkSoft: "#f3d0d6", accent: "#ffd28a", accent2: "#ffffff", foil: "gold", surface: "#150d1e", surface2: "#34233f" }),
      BP({ id: "teal", label: "Teal Night", paper: "#0c2a2e", paper2: "#18555c", ink: "#ffffff", inkSoft: "#bfe3e3", accent: "#7ef0d0", accent2: "#ffffff", foil: "silver", surface: "#061618", surface2: "#12363a" }),
    ],
  }),
  biz("salon-luxe", "Salon Luxe", "Blush, rose-gold script and a salon arch", { design: "salon", enter: "draw", flip: "float", thick: 3, radius: 14, edge: "#ecd3cb" }, {
    paper: "matte",
    backdrop: "marble",
    fonts: F("--f-allura", "--f-allura", "--f-montserrat"),
    styles: ["Luxury", "Minimal"],
    effects: ["Hot foil", "Line drawing"],
    industries: ["Beauty & Wellness", "Fashion & Textiles"],
    palettes: [
      BP({ id: "blush", label: "Blush", paper: "#f7e4e0", paper2: "#ecc9c1", ink: "#4a2a2c", inkSoft: "#8a6064", accent: "#c9867a", accent2: "#4a2a2c", foil: "rosegold", surface: "#ece0db", surface2: "#d9c5be" }),
      BP({ id: "noir", label: "Noir Rose", paper: "#1b1416", paper2: "#2a1f22", ink: "#f6e1dc", inkSoft: "#c2a19c", accent: "#dca597", accent2: "#f6e1dc", foil: "rosegold", surface: "#231c22", surface2: "#46384a" }),
      BP({ id: "nude", label: "Nude", paper: "#efe2d3", paper2: "#e0cdb7", ink: "#3a2b20", inkSoft: "#7d6a58", accent: "#b08a5a", accent2: "#3a2b20", foil: "gold", surface: "#ebe2d4", surface2: "#d6c7b0" }),
    ],
  }),
  biz("iron-pulse", "Iron Pulse", "Bold slashes and huge italic type for gyms", { design: "fitness", enter: "zoom", flip: "swap", thick: 4, radius: 8, edge: "#111" }, {
    paper: "matte",
    backdrop: "slate",
    fonts: F("--f-anton", "--f-anton", "--f-montserrat"),
    styles: ["Playful", "Modern"],
    effects: ["Bold type", "Motion slashes"],
    industries: ["Fitness & Sports"],
    palettes: [
      BP({ id: "lime", label: "Lime", paper: "#121212", paper2: "#1f1f1f", ink: "#ffffff", inkSoft: "#a3a3a3", accent: "#c6ff00", accent2: "#ffffff", foil: "silver", surface: "#0a0a0a", surface2: "#222" }),
      BP({ id: "red", label: "Fire", paper: "#121212", paper2: "#1f1f1f", ink: "#ffffff", inkSoft: "#a3a3a3", accent: "#ff3b30", accent2: "#ffffff", foil: "silver", surface: "#0a0a0a", surface2: "#222" }),
      BP({ id: "orange", label: "Blaze", paper: "#141414", paper2: "#222", ink: "#ffffff", inkSoft: "#a3a3a3", accent: "#ff8a00", accent2: "#ffffff", foil: "silver", surface: "#0a0a0a", surface2: "#222" }),
    ],
  }),
  biz("chalk-cafe", "Chalk Café", "Hand-lettered chalkboard in a wooden frame", { design: "chalk", enter: "draw", flip: "toss", thick: 6, radius: 6, edge: "#6b4a2e" }, {
    paper: "matte",
    backdrop: "wood",
    fonts: F("--f-fredericka", "--f-caveat", "--f-caveat"),
    styles: ["Playful", "Craft"],
    effects: ["Chalk", "Line drawing"],
    industries: ["Food & Café", "Retail & Shops"],
    palettes: [
      BP({ id: "green", label: "Green Board", paper: "#2b3a33", paper2: "#1f2a24", ink: "#f4f1e8", inkSoft: "#cfd8d0", accent: "#ffd166", accent2: "#7a5230", foil: "gold", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "black", label: "Blackboard", paper: "#23262a", paper2: "#1a1c1f", ink: "#f4f1e8", inkSoft: "#cfcfcf", accent: "#ff9fb2", accent2: "#5a3b22", foil: "gold", surface: "#6b4a2e", surface2: "#3f2a19" }),
    ],
  }),
  biz("dev-terminal", "Dev Terminal", "A terminal window that types itself out", { design: "terminal", enter: "type", flip: "glitch", thick: 3, radius: 12, edge: "#1f2430" }, {
    paper: "matte",
    backdrop: "slate",
    fonts: F("--f-jetbrains", "--f-jetbrains", "--f-jetbrains"),
    styles: ["Modern", "Creative"],
    effects: ["Typing", "Glitch"],
    industries: ["Tech & Startups"],
    palettes: [
      BP({ id: "night", label: "Night Owl", paper: "#0d1117", paper2: "#161b22", ink: "#e6edf3", inkSoft: "#8b949e", accent: "#7ee787", accent2: "#79c0ff", foil: "silver", surface: "#05070a", surface2: "#1b2029" }),
      BP({ id: "dracula", label: "Dracula", paper: "#1e1f29", paper2: "#282a36", ink: "#f8f8f2", inkSoft: "#9ea3c0", accent: "#ff79c6", accent2: "#8be9fd", foil: "silver", surface: "#0e0f14", surface2: "#282a36" }),
      BP({ id: "solar", label: "Solarized", paper: "#002b36", paper2: "#073642", ink: "#eee8d5", inkSoft: "#93a1a1", accent: "#b58900", accent2: "#2aa198", foil: "gold", surface: "#001a21", surface2: "#0a3a46" }),
    ],
  }),
  biz("blueprint", "Blueprint", "Technical drawing with a title block", { design: "blueprint", enter: "draw", flip: "vertical", thick: 3, radius: 4, edge: "#123a6b" }, {
    paper: "matte",
    backdrop: "wood",
    fonts: F("--f-space-mono", "--f-space-mono", "--f-space-mono"),
    styles: ["Corporate", "Modern"],
    effects: ["Line drawing", "Grid"],
    industries: ["Architecture & Construction", "Real Estate"],
    palettes: [
      BP({ id: "blue", label: "Blueprint", paper: "#1c4f8f", paper2: "#2a63a8", ink: "#eaf2ff", inkSoft: "#b7cbe8", accent: "#ffd166", accent2: "#eaf2ff", foil: "silver", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "white", label: "White Print", paper: "#f6f5f0", paper2: "#e8e6dd", ink: "#1c3f73", inkSoft: "#5a6e8f", accent: "#e4572e", accent2: "#1c3f73", foil: "silver", surface: "#6b4a2e", surface2: "#3f2a19" }),
    ],
  }),
  biz("aperture", "Aperture", "Camera iris that spins open, viewfinder marks", { design: "aperture", enter: "bloom", flip: "pop", thick: 4, radius: 10, edge: "#1a1a1c" }, {
    paper: "matte",
    backdrop: "slate",
    fonts: F("--f-bebas", "--f-bebas", "--f-jakarta"),
    styles: ["Creative", "Modern"],
    effects: ["Camera iris", "Spin"],
    industries: ["Photography & Film", "Creative & Design"],
    palettes: [
      BP({ id: "graphite", label: "Graphite", paper: "#141416", paper2: "#26262a", ink: "#ffffff", inkSoft: "#9d9da3", accent: "#ffcc00", accent2: "#ffffff", foil: "silver", surface: "#0a0a0b", surface2: "#1f1f22" }),
      BP({ id: "film", label: "Film Red", paper: "#161214", paper2: "#2a2023", ink: "#ffffff", inkSoft: "#a39a9d", accent: "#ff4d4d", accent2: "#ffffff", foil: "silver", surface: "#0a0a0b", surface2: "#1f1f22" }),
    ],
  }),
  biz("notebook", "Notebook", "Ruled page, handwriting and a sticky note", { design: "notebook", enter: "type", flip: "toss", thick: 3, radius: 6, edge: "#f1efe6" }, {
    paper: "matte",
    backdrop: "wood",
    fonts: F("--f-kalam", "--f-kalam", "--f-kalam"),
    styles: ["Playful", "Craft"],
    effects: ["Handwriting", "Typing"],
    industries: ["Education"],
    palettes: [
      BP({ id: "classic", label: "School Blue", paper: "#fdfcf6", paper2: "#f3f0e4", ink: "#1f3b8c", inkSoft: "#4a5e9e", accent: "#6ea8e0", accent2: "#e05a5a", foil: "silver", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "graph", label: "Pencil", paper: "#fbfaf4", paper2: "#efece0", ink: "#2d2d2d", inkSoft: "#5c5c5c", accent: "#8fb3c9", accent2: "#e0a05a", foil: "silver", surface: "#6b4a2e", surface2: "#3f2a19" }),
    ],
  }),
  biz("jyotish-stars", "Jyotish Stars", "Gold zodiac wheel turning in a night sky", { design: "jyotish", enter: "bloom", flip: "spin", thick: 4, radius: 10, edge: "foil" }, {
    paper: "matte",
    backdrop: "velvet",
    fonts: F("--f-cinzel", "--f-cinzel", "--f-cormorant"),
    styles: ["Traditional", "Luxury"],
    effects: ["Zodiac", "Hot foil", "Spin"],
    industries: ["Spiritual & Astrology"],
    palettes: [
      BP({ id: "indigo", label: "Midnight", paper: "#141436", paper2: "#262a66", ink: "#f4e8c8", inkSoft: "#c9bd9a", accent: "#c9a24a", accent2: "#f4e8c8", foil: "gold", surface: "#0a0a1e", surface2: "#1c1c44" }),
      BP({ id: "saffron", label: "Bhagwa", paper: "#5a1a08", paper2: "#8a2c0c", ink: "#fff0d0", inkSoft: "#f1c99a", accent: "#ffb703", accent2: "#fff0d0", foil: "gold", surface: "#2a0c04", surface2: "#4a1808" }),
    ],
  }),
  biz("dukaan", "Dukaan", "Shop awning, signboard and everything on the front", { design: "dukaan", enter: "cascade", flip: "deal", thick: 3, radius: 8, edge: "#e8dcc6" }, {
    paper: "cotton",
    backdrop: "wood",
    fonts: F("--f-yatra", "--f-yatra", "--f-jakarta"),
    styles: ["Festive", "Traditional"],
    effects: ["Awning", "More info on front"],
    industries: ["Retail & Shops", "Food & Café"],
    palettes: [
      BP({ id: "saffron", label: "Kesari", paper: "#fff8ea", paper2: "#fbe9c6", ink: "#3a1d0a", inkSoft: "#7a5030", accent: "#f28c0f", accent2: "#a8201a", foil: "gold", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "green", label: "Hara Bhara", paper: "#f6fbef", paper2: "#e5f2d6", ink: "#17301c", inkSoft: "#4f6b54", accent: "#2e9e5b", accent2: "#0f5132", foil: "gold", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "blue", label: "Neela", paper: "#f3f7ff", paper2: "#dfe9fb", ink: "#0f1f3d", inkSoft: "#4f5f80", accent: "#2d6cdf", accent2: "#c8102e", foil: "gold", surface: "#6b4a2e", surface2: "#3f2a19" }),
    ],
  }),
  biz("boarding-pass", "Boarding Pass", "Ticket with a tear-off stub and barcode", { design: "boarding", enter: "cascade", flip: "swap", thick: 3, radius: 16, edge: "#e8e8e8" }, {
    paper: "matte",
    backdrop: "paper",
    fonts: F("--f-jakarta", "--f-jakarta", "--f-space-mono"),
    styles: ["Creative", "Playful"],
    effects: ["Ticket", "Barcode"],
    industries: ["Travel & Outdoors", "Music & Events"],
    palettes: [
      BP({ id: "sky", label: "Sky Blue", paper: "#ffffff", paper2: "#f3f6fb", ink: "#0f1f3d", inkSoft: "#6a7690", accent: "#2d6cdf", accent2: "#0f1f3d", foil: "silver", surface: "#dfe4ee", surface2: "#b8c1d4" }),
      BP({ id: "coral", label: "Coral", paper: "#fffaf6", paper2: "#fbeee6", ink: "#2b1a14", inkSoft: "#8a6f64", accent: "#ff6f59", accent2: "#2b1a14", foil: "silver", surface: "#ece3dc", surface2: "#cbbcb0" }),
    ],
  }),
  biz("vinyl-record", "Vinyl Record", "Square card with a spinning record", { design: "vinyl", enter: "zoom", flip: "spin", thick: 3, radius: 12, edge: "#1a1a1a", shape: "square" }, {
    paper: "matte",
    backdrop: "concrete",
    fonts: F("--f-bebas", "--f-bebas", "--f-jakarta"),
    styles: ["Creative", "Retro"],
    effects: ["Spin", "Square card"],
    industries: ["Music & Events"],
    palettes: [
      BP({ id: "red", label: "Red Label", paper: "#18181a", paper2: "#2a2a2e", ink: "#ffffff", inkSoft: "#a3a3a8", accent: "#e63946", accent2: "#ffffff", foil: "silver", surface: "#121214", surface2: "#2a2a2e" }),
      BP({ id: "yellow", label: "Yellow Label", paper: "#18181a", paper2: "#2a2a2e", ink: "#ffffff", inkSoft: "#a3a3a8", accent: "#f4b400", accent2: "#ffffff", foil: "silver", surface: "#121214", surface2: "#2a2a2e" }),
      BP({ id: "blue", label: "Blue Note", paper: "#141824", paper2: "#232a3d", ink: "#ffffff", inkSoft: "#a3a9bd", accent: "#3a86ff", accent2: "#ffffff", foil: "silver", surface: "#0c0f17", surface2: "#232a3d" }),
    ],
  }),
  biz("loyalty-cafe", "Loyalty Café", "Café card with a stamp-card back", { design: "loyalty", enter: "bloom", flip: "pop", thick: 3, radius: 14, edge: "#e6d6c0" }, {
    paper: "matte",
    backdrop: "wood",
    fonts: F("--f-fredoka", "--f-fredoka", "--f-fredoka"),
    styles: ["Playful", "Nature"],
    effects: ["Loyalty stamps", "Pop"],
    industries: ["Food & Café", "Retail & Shops", "Beauty & Wellness"],
    palettes: [
      BP({ id: "latte", label: "Latte", paper: "#f6ecdf", paper2: "#e9d6bf", ink: "#3b2416", inkSoft: "#7a5a44", accent: "#8b5a3c", accent2: "#5a3825", foil: "copper", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "matcha", label: "Matcha", paper: "#eef4e4", paper2: "#dae7c8", ink: "#243420", inkSoft: "#5a6e52", accent: "#6a994e", accent2: "#386641", foil: "gold", surface: "#6b4a2e", surface2: "#3f2a19" }),
      BP({ id: "berry", label: "Berry", paper: "#fbeef2", paper2: "#f3d6df", ink: "#3a1422", inkSoft: "#85566a", accent: "#c2185b", accent2: "#7a1040", foil: "rosegold", surface: "#6b4a2e", surface2: "#3f2a19" }),
    ],
  }),
  biz("circuit-board", "Circuit Board", "PCB traces that light up to a central chip", { design: "circuit", enter: "draw", flip: "glitch", thick: 4, radius: 8, edge: "#0b2a20" }, {
    paper: "matte",
    backdrop: "slate",
    fonts: F("--f-orbitron", "--f-orbitron", "--f-jakarta"),
    styles: ["Modern", "Creative"],
    effects: ["Circuit", "Line drawing", "Glow"],
    industries: ["Tech & Startups"],
    palettes: [
      BP({ id: "green", label: "PCB Green", paper: "#0f3d2e", paper2: "#17563f", ink: "#eaf5ef", inkSoft: "#a9cbbb", accent: "#e8b04a", accent2: "#eaf5ef", foil: "gold", surface: "#061a13", surface2: "#12382b" }),
      BP({ id: "black", label: "Matte Black", paper: "#111316", paper2: "#1c2026", ink: "#eaf0f5", inkSoft: "#9aa5b1", accent: "#00e5ff", accent2: "#eaf0f5", foil: "silver", surface: "#08090b", surface2: "#1c2026" }),
    ],
  }),
  biz("botanical", "Botanical", "Leafy sprigs drawn in fine line", { design: "botanical", enter: "draw", flip: "float", thick: 3, radius: 8, edge: "#e9e4d6" }, {
    paper: "cotton",
    backdrop: "linen",
    fonts: F("--f-garamond", "--f-garamond", "--f-jost"),
    styles: ["Nature", "Minimal"],
    effects: ["Line drawing", "Botanical"],
    industries: ["Beauty & Wellness", "Doctors & Clinics", "Food & Café"],
    palettes: [
      BP({ id: "sage", label: "Sage", paper: "#f4f1e8", paper2: "#e8e3d2", ink: "#26352a", inkSoft: "#66735f", accent: "#4f7a4a", accent2: "#26352a", foil: "gold", surface: "#e6ded0", surface2: "#c7baa5" }),
      BP({ id: "olive", label: "Olive & Cream", paper: "#fbf6ea", paper2: "#efe6cf", ink: "#3a3a1f", inkSoft: "#75714f", accent: "#7b8a3a", accent2: "#3a3a1f", foil: "gold", surface: "#e6ded0", surface2: "#c7baa5" }),
      BP({ id: "forest", label: "Deep Forest", paper: "#1f3326", paper2: "#284231", ink: "#f1ede0", inkSoft: "#bcc6b4", accent: "#b7d69a", accent2: "#f1ede0", foil: "gold", surface: "#e6ded0", surface2: "#c7baa5" }),
    ],
  }),
  biz("carbon-racing", "Carbon Racing", "Carbon-fibre weave with racing stripes", { design: "carbon", enter: "slide", flip: "heavy", thick: 5, radius: 12, edge: "#111" }, {
    paper: "matte",
    backdrop: "felt",
    fonts: F("--f-russo", "--f-russo", "--f-montserrat"),
    styles: ["Modern", "Playful"],
    effects: ["Carbon fibre", "Clear-coat shine"],
    industries: ["Automobile", "Fitness & Sports"],
    palettes: [
      BP({ id: "red", label: "Rosso", paper: "#131313", paper2: "#222", ink: "#eef0f3", inkSoft: "#9a9ea6", accent: "#e10600", accent2: "#eef0f3", foil: "silver", surface: "#1f2023", surface2: "#3b3c41" }),
      BP({ id: "blue", label: "Gulf", paper: "#131313", paper2: "#222", ink: "#eef0f3", inkSoft: "#9a9ea6", accent: "#6fb7e0", accent2: "#eef0f3", foil: "silver", surface: "#1f2023", surface2: "#3b3c41" }),
      BP({ id: "yellow", label: "Giallo", paper: "#131313", paper2: "#222", ink: "#eef0f3", inkSoft: "#9a9ea6", accent: "#ffcc00", accent2: "#eef0f3", foil: "silver", surface: "#1f2023", surface2: "#3b3c41" }),
    ],
  }),
  biz("portrait-pro", "Portrait Pro", "Your photo in a ring, name and contact on the front", { design: "portrait", enter: "cascade", flip: "classic", thick: 3, radius: 14, edge: "#e9e9ee" }, {
    paper: "matte",
    backdrop: "paper",
    photo: true,
    fonts: F("--f-jakarta", "--f-jakarta", "--f-jakarta"),
    styles: ["Corporate", "Modern"],
    effects: ["Photo", "More info on front"],
    industries: ["Real Estate", "Finance & Legal", "Education", "Doctors & Clinics", "Any business"],
    palettes: [
      BP({ id: "indigo", label: "Indigo", paper: "#ffffff", paper2: "#f3f4f8", ink: "#16192b", inkSoft: "#646a82", accent: "#4f46e5", accent2: "#06b6d4", foil: "silver", surface: "#e4e6ee", surface2: "#c0c4d4" }),
      BP({ id: "coral", label: "Coral", paper: "#ffffff", paper2: "#fbf3f0", ink: "#2b1a17", inkSoft: "#806a64", accent: "#f0643c", accent2: "#f5b041", foil: "silver", surface: "#ece4e0", surface2: "#cbbdb8" }),
      BP({ id: "emerald", label: "Emerald", paper: "#ffffff", paper2: "#f1f7f4", ink: "#12291f", inkSoft: "#5f786b", accent: "#10a37f", accent2: "#0e7490", foil: "silver", surface: "#e0ebe6", surface2: "#bcccc4" }),
    ],
  }),
  biz("photo-split", "Photo Split", "Half photo, half colour, cut on a diagonal", { design: "split", enter: "wipe", flip: "deal", thick: 3, radius: 12, edge: "#e9e9ee" }, {
    paper: "matte",
    backdrop: "slate",
    photo: true,
    fonts: F("--f-montserrat", "--f-montserrat", "--f-montserrat"),
    styles: ["Modern", "Creative"],
    effects: ["Photo", "Diagonal split"],
    industries: ["Fashion & Textiles", "Beauty & Wellness", "Real Estate", "Photography & Film"],
    palettes: [
      BP({ id: "plum", label: "Plum", paper: "#ffffff", paper2: "#f5f0f6", ink: "#231428", inkSoft: "#6f5c76", accent: "#8e2de2", accent2: "#e2366f", foil: "silver", surface: "#12101a", surface2: "#2a2536" }),
      BP({ id: "ocean", label: "Ocean", paper: "#ffffff", paper2: "#f0f6f9", ink: "#0f2430", inkSoft: "#5c7482", accent: "#0077b6", accent2: "#00b4d8", foil: "silver", surface: "#12101a", surface2: "#2a2536" }),
      BP({ id: "noir", label: "Noir", paper: "#ffffff", paper2: "#f3f3f3", ink: "#141414", inkSoft: "#666", accent: "#232323", accent2: "#6b6b6b", foil: "silver", surface: "#12101a", surface2: "#2a2536" }),
    ],
  }),
  biz("trust-shield", "Trust Shield", "Shield emblem for insurance, finance and security", { design: "shield", enter: "draw", flip: "lift", thick: 3, radius: 10, edge: "#0f2a52" }, {
    paper: "matte",
    backdrop: "slate",
    fonts: F("--f-montserrat", "--f-montserrat", "--f-montserrat"),
    styles: ["Corporate"],
    effects: ["Line drawing"],
    industries: ["Finance & Legal", "Any business"],
    palettes: [
      BP({ id: "blue", label: "Trust Blue", paper: "#0f2a52", paper2: "#1d4a8a", ink: "#ffffff", inkSoft: "#c7d6ec", accent: "#3ec1ff", accent2: "#ffffff", foil: "silver", surface: "#07152a", surface2: "#16305a" }),
      BP({ id: "green", label: "Growth Green", paper: "#0e3326", paper2: "#1b5e45", ink: "#ffffff", inkSoft: "#c2e0d2", accent: "#4ade80", accent2: "#ffffff", foil: "silver", surface: "#061a13", surface2: "#12382b" }),
      BP({ id: "maroon", label: "Heritage", paper: "#4a0f1c", paper2: "#7a1f32", ink: "#ffffff", inkSoft: "#efc9d1", accent: "#f5c451", accent2: "#ffffff", foil: "gold", surface: "#20060c", surface2: "#3d0e18" }),
    ],
  }),
];
