import type { Palette, Template } from "./types";
import { festivalSample } from "./festival";

/** Festival Greetings: all Signature designs (Dhanteras, Diwali, New Year). */

const P = (p: Palette) => p;

export const FESTIVAL_TEMPLATES: Template[] = [
  {
    id: "roshni",
    name: "Roshni",
    category: "festival",
    signature: true,
    tagline: "An old-city rooftop on Diwali night. Tap the sky for fireworks",
    paper: "matte",
    ornament: "none",
    backdrop: "slate",
    petals: "marigold",
    fonts: { display: "var(--f-cinzel)", script: "var(--f-great-vibes)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "indigo", label: "Indigo Night", paper: "#0d1033", paper2: "#2e2163", ink: "#fff3dc", inkSoft: "#d8c9ee", accent: "#ff6b9a", accent2: "#ff5fa2", foil: "gold", surface: "#05061a", surface2: "#14183f", envelope: "#f6ecd9", envelope2: "#0d1033", wax: "#ffc35a" }),
      P({ id: "plum", label: "Plum", paper: "#1a0b26", paper2: "#4a1e5a", ink: "#fff1e6", inkSoft: "#e2c3e0", accent: "#ff9e5e", accent2: "#c77dff", foil: "gold", surface: "#0a0410", surface2: "#2a1236", envelope: "#f6eadc", envelope2: "#1a0b26", wax: "#ffcf6b" }),
      P({ id: "teal", label: "Midnight Teal", paper: "#04161e", paper2: "#0f3f4f", ink: "#f4f1e6", inkSoft: "#b6d4d2", accent: "#ff7b54", accent2: "#5ee6c8", foil: "gold", surface: "#020a0e", surface2: "#0a2a33", envelope: "#f0ece0", envelope2: "#04161e", wax: "#ffd27a" }),
      P({ id: "maroon", label: "Maroon", paper: "#1e0710", paper2: "#5a1530", ink: "#fff1e0", inkSoft: "#efc6c6", accent: "#ffb347", accent2: "#ff5f7e", foil: "gold", surface: "#0e0306", surface2: "#3a0c1c", envelope: "#f7eadb", envelope2: "#1e0710", wax: "#ffd27a" }),
    ],
    styles: ["Signature", "Diwali", "Night"],
    effects: ["Live fireworks", "Tap for fireworks", "Lights-up intro", "Launch turn"],
    wed: { design: "roshni", intro: "lightsup", turn: "launch", reveal: "spark" },
    sample: festivalSample("indigo", "diwali"),
  },
  {
    id: "rangoli-utsav",
    name: "Rangoli",
    category: "festival",
    signature: true,
    tagline: "A powder rangoli drawn ring by ring, ringed with glowing diyas",
    paper: "matte",
    ornament: "none",
    backdrop: "wood",
    petals: "marigold",
    fonts: { display: "var(--f-yatra)", script: "var(--f-parisienne)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "terracotta", label: "Terracotta Floor", paper: "#5a1e12", paper2: "#3e130a", ink: "#fff4e0", inkSoft: "#f2cfae", accent: "#ff3d7f", accent2: "#ff9f1c", foil: "gold", surface: "#1e0805", surface2: "#3e130a", envelope: "#f7e8d6", envelope2: "#5a1e12", wax: "#00b3a4" }),
      P({ id: "slate", label: "Slate Floor", paper: "#16182a", paper2: "#0c0d18", ink: "#fff4e6", inkSoft: "#c9c7de", accent: "#ff4d9d", accent2: "#ffb703", foil: "gold", surface: "#05060c", surface2: "#16182a", envelope: "#f3eee6", envelope2: "#16182a", wax: "#2ec4b6" }),
      P({ id: "marble", label: "White Marble", paper: "#efe7d9", paper2: "#e2d6c2", ink: "#4a1f12", inkSoft: "#8a5a40", accent: "#e5096f", accent2: "#ff8800", foil: "gold", surface: "#d6ccbb", surface2: "#bcb09b", envelope: "#f6f0e6", envelope2: "#e5096f", wax: "#0096a8" }),
      P({ id: "emerald", label: "Emerald Floor", paper: "#0f3b2e", paper2: "#082a20", ink: "#fff6e0", inkSoft: "#cfe3d4", accent: "#ff5c8a", accent2: "#ffc300", foil: "gold", surface: "#03140e", surface2: "#0f3b2e", envelope: "#f2ede0", envelope2: "#0f3b2e", wax: "#4cc9f0" }),
    ],
    styles: ["Signature", "Diwali", "Colourful"],
    effects: ["Powder rangoli", "Rangoli drawing intro", "Petal shower", "Mandala turn"],
    wed: { design: "rangoli", intro: "drawrangoli", turn: "mandala", reveal: "powder" },
    sample: festivalSample("terracotta", "diwali", {
      primary: { name: "The Iyer Family", subtitle: "Ramesh, Lakshmi, Karthik & Meera" },
      closing: { title: "With love and light", names: ["The Iyer Family"] },
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  {
    id: "swarna",
    name: "Swarna",
    category: "festival",
    signature: true,
    tagline: "Dhanteras gold: a kalash of coins, Lakshmi's footprints, Shubh–Labh",
    paper: "silk",
    ornament: "none",
    backdrop: "velvet",
    petals: "gold",
    fonts: { display: "var(--f-cinzel-deco)", script: "var(--f-pinyon)", body: "var(--f-garamond)" },
    palettes: [
      P({ id: "maroon", label: "Maroon Velvet", paper: "#4a0d14", paper2: "#2a060b", ink: "#fbe8c6", inkSoft: "#e2b77a", accent: "#e01e37", accent2: "#0f5132", foil: "gold", surface: "#16030a", surface2: "#3a0a12", envelope: "#f6e6c9", envelope2: "#4a0d14", wax: "#c8102e" }),
      P({ id: "emerald", label: "Emerald Velvet", paper: "#0b3a2a", paper2: "#05241a", ink: "#fbecc8", inkSoft: "#d9c48e", accent: "#e01e37", accent2: "#7a1c1c", foil: "gold", surface: "#02130d", surface2: "#0b3a2a", envelope: "#f3e9cf", envelope2: "#0b3a2a", wax: "#c8102e" }),
      P({ id: "royal", label: "Royal Blue", paper: "#14204a", paper2: "#0a1230", ink: "#fbecc8", inkSoft: "#cbbf9c", accent: "#e01e37", accent2: "#3a4c8c", foil: "gold", surface: "#050918", surface2: "#14204a", envelope: "#f1e9d6", envelope2: "#14204a", wax: "#c8102e" }),
      P({ id: "ivory", label: "Ivory Silk", paper: "#f6eedc", paper2: "#eadcbe", ink: "#4a2a10", inkSoft: "#8a6a40", accent: "#c8102e", accent2: "#b8860b", foil: "gold", surface: "#d9ccb1", surface2: "#bfae8e", envelope: "#f8f2e6", envelope2: "#c8102e", wax: "#c8102e" }),
    ],
    styles: ["Signature", "Dhanteras", "Business"],
    effects: ["Coin shower", "Tap for gold coins", "Logo slot", "Coin turn"],
    wed: { design: "swarna", intro: "coinrain", turn: "coin", reveal: "gleam" },
    sample: festivalSample("maroon", "dhanteras", {
      primary: { name: "Shah Jewellers", subtitle: "Since 1962 · C.G. Road, Ahmedabad" },
      closing: { title: "With best wishes", names: ["The Shah Family & Team"] },
      events: [
        { id: "f1", kind: "other", name: "Dhanteras Muhurat Shopping", date: "2026-11-06", time: "10:00", venue: "Shah Jewellers", address: "C.G. Road, Navrangpura, Ahmedabad", note: "Special Dhanteras collection · open till 11 PM" },
      ],
      rsvp: { enabled: true, contacts: [{ name: "Store", phone: "+91 79 2640 1234" }] },
    }),
  },
  {
    id: "pehla-diya",
    name: "Pehla Diya",
    category: "festival",
    signature: true,
    tagline: "One brass diya in the dark. Light it, and the greeting appears",
    paper: "matte",
    ornament: "none",
    backdrop: "felt",
    petals: "gold",
    fonts: { display: "var(--f-cormorant)", script: "var(--f-great-vibes)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "ember", label: "Ember", paper: "#0c0705", paper2: "#2a1408", ink: "#fff1d6", inkSoft: "#d9b98a", accent: "#ff9a2e", accent2: "#ffd27a", foil: "gold", surface: "#040201", surface2: "#1a0d05", envelope: "#f3e6cf", envelope2: "#0c0705", wax: "#ff9a2e" }),
      P({ id: "midnight", label: "Midnight Blue", paper: "#05070f", paper2: "#141a33", ink: "#f6efe0", inkSoft: "#c2bfd6", accent: "#ffa33a", accent2: "#ffd88a", foil: "gold", surface: "#020308", surface2: "#0c1024", envelope: "#efeae0", envelope2: "#05070f", wax: "#ffa33a" }),
      P({ id: "plum", label: "Deep Plum", paper: "#0d0510", paper2: "#2b1030", ink: "#fbeef0", inkSoft: "#d8b6d0", accent: "#ff9a4a", accent2: "#ffd09a", foil: "rosegold", surface: "#050206", surface2: "#1c0a20", envelope: "#f4e8ec", envelope2: "#0d0510", wax: "#ff9a4a" }),
      P({ id: "charcoal", label: "Charcoal", paper: "#0b0b0b", paper2: "#262626", ink: "#f7f2e8", inkSoft: "#bdb6aa", accent: "#ff9d2e", accent2: "#ffd27a", foil: "gold", surface: "#000", surface2: "#151515", envelope: "#f0ebe2", envelope2: "#0b0b0b", wax: "#ff9d2e" }),
    ],
    styles: ["Signature", "Diwali", "Minimal"],
    effects: ["Living flame", "Light the diyas", "Kindle intro", "Snuff turn"],
    wed: { design: "pehladiya", intro: "kindle", turn: "snuff", reveal: "kindle" },
    sample: festivalSample("ember", "diwali", {
      primary: { name: "Ananya & Rohan", subtitle: "and little Kiaan" },
      closing: { title: "With love and light", names: ["Ananya, Rohan & Kiaan"] },
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  {
    id: "naya-saal",
    name: "Naya Saal",
    category: "festival",
    signature: true,
    tagline: "Tear off the old year: a sunrise calendar for Saal Mubarak or 1 January",
    paper: "cotton",
    ornament: "none",
    backdrop: "paper",
    petals: "marigold",
    fonts: { display: "var(--f-fraunces)", script: "var(--f-great-vibes)", body: "var(--f-jost)" },
    palettes: [
      P({ id: "sunrise", label: "Sunrise", paper: "#fffaf0", paper2: "#efe3cc", ink: "#3a2416", inkSoft: "#8a6a50", accent: "#e4572e", accent2: "#2a9d8f", foil: "gold", surface: "#e6dccb", surface2: "#cdbfa8", envelope: "#fffaf0", envelope2: "#e4572e", wax: "#f2a541" }),
      P({ id: "marigold", label: "Marigold", paper: "#fff6e6", paper2: "#f6e2bf", ink: "#4a2a0c", inkSoft: "#9a6a3a", accent: "#f08a24", accent2: "#6a994e", foil: "gold", surface: "#eadcc2", surface2: "#d2c09d", envelope: "#fff6e6", envelope2: "#f08a24", wax: "#ffbe0b" }),
      P({ id: "rose", label: "Rose Dawn", paper: "#fff4f2", paper2: "#f6dcd6", ink: "#4a1f2a", inkSoft: "#9a6670", accent: "#d6456b", accent2: "#5a8a8a", foil: "rosegold", surface: "#ecdcd8", surface2: "#d6c0bb", envelope: "#fff4f2", envelope2: "#d6456b", wax: "#f4a261" }),
      P({ id: "indigo", label: "Indigo Morning", paper: "#f3f1fa", paper2: "#dcd8ee", ink: "#1f1d4a", inkSoft: "#6a6894", accent: "#5a4fcf", accent2: "#e07a5f", foil: "gold", surface: "#dedbe9", surface2: "#c2bed6", envelope: "#f3f1fa", envelope2: "#5a4fcf", wax: "#f2cc8f" }),
    ],
    styles: ["Signature", "New Year", "Cheerful"],
    effects: ["Tear-off calendar", "Sunrise", "Confetti", "Tear turn"],
    wed: { design: "nayasaal", intro: "tearoff", turn: "tear", reveal: "dawn" },
    sample: festivalSample("sunrise", "nutanvarsh", {
      primary: { name: "The Patel Family", subtitle: "Nilesh, Hetal, Parth & Khushi" },
      closing: { title: "Warm wishes", names: ["The Patel Family"] },
      events: [
        { id: "f1", kind: "other", name: "Sneh Milan", date: "2026-11-10", time: "10:00", venue: "Patel Niwas", address: "Satellite Road, Ahmedabad", note: "Come for chai, mathiya & new-year blessings" },
      ],
      rsvp: { enabled: true, contacts: [{ name: "Nilesh Patel", phone: "+91 98250 55555" }] },
    }),
  },
  /* ---------------- Diwali collection, chunk 1 ---------------- */
  {
    id: "phuljhadi",
    name: "Phuljhadi",
    category: "festival",
    signature: true,
    tagline: "A sparkler writes your Diwali wish in light. Draw with your own",
    paper: "matte",
    ornament: "none",
    backdrop: "slate",
    petals: "gold",
    fonts: { display: "var(--f-cinzel)", script: "var(--f-allura)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "smoke", label: "Night Smoke", paper: "#0a0705", paper2: "#1f140b", ink: "#fff1d6", inkSoft: "#c9b08a", accent: "#ff9a2e", accent2: "#ffd27a", foil: "gold", surface: "#030201", surface2: "#140c06", envelope: "#f3e6cf", envelope2: "#0a0705", wax: "#ff9a2e" }),
      P({ id: "bluehour", label: "Blue Hour", paper: "#070b18", paper2: "#18213f", ink: "#fff3dc", inkSoft: "#b8c0da", accent: "#ffa94d", accent2: "#ffd8a0", foil: "gold", surface: "#020409", surface2: "#0e1428", envelope: "#efeae0", envelope2: "#070b18", wax: "#ffa94d" }),
      P({ id: "plum", label: "Plum Night", paper: "#110812", paper2: "#2c1332", ink: "#fff0ea", inkSoft: "#d4b6cf", accent: "#ff9e6b", accent2: "#ffd0a8", foil: "rosegold", surface: "#060307", surface2: "#1c0b20", envelope: "#f4e8ec", envelope2: "#110812", wax: "#ff9e6b" }),
      P({ id: "ember", label: "Ember Red", paper: "#120505", paper2: "#320c0c", ink: "#fff0e0", inkSoft: "#e2b6a0", accent: "#ff8c3a", accent2: "#ffd27a", foil: "gold", surface: "#060101", surface2: "#200606", envelope: "#f6e6da", envelope2: "#120505", wax: "#ff8c3a" }),
    ],
    styles: ["Signature", "Diwali", "Night"],
    effects: ["Sparkler writing", "Draw with light", "Long exposure", "Smoke turn"],
    wed: { design: "phuljhadi", intro: "sparkwrite", turn: "smoke", reveal: "write" },
    sample: festivalSample("smoke", "diwali", {
      primary: { name: "The Sharma Family", subtitle: "Vivek, Neha, Ishaan & Aanya" },
      closing: { title: "With love and light", names: ["The Sharma Family"] },
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  {
    id: "pataka",
    name: "Pataka",
    category: "festival",
    signature: true,
    tagline: "Cracker night in the courtyard: anaar, chakri and rockets. Tap to light",
    paper: "matte",
    ornament: "none",
    backdrop: "concrete",
    petals: "marigold",
    fonts: { display: "var(--f-shrikhand)", script: "var(--f-great-vibes)", body: "var(--f-jost)" },
    palettes: [
      P({ id: "night", label: "Courtyard Night", paper: "#120c18", paper2: "#2e2240", ink: "#fff3e0", inkSoft: "#d6c6e0", accent: "#ff4f79", accent2: "#ffc23a", foil: "gold", surface: "#06040a", surface2: "#1c1428", envelope: "#f3ece0", envelope2: "#120c18", wax: "#ffc23a" }),
      P({ id: "red", label: "Festive Red", paper: "#1a0909", paper2: "#3e1414", ink: "#fff1e2", inkSoft: "#efc4b4", accent: "#ff6b35", accent2: "#3ec1d3", foil: "gold", surface: "#080202", surface2: "#2a0a0a", envelope: "#f6e8da", envelope2: "#1a0909", wax: "#ffd166" }),
      P({ id: "indigo", label: "Indigo", paper: "#0b0f2a", paper2: "#212a5c", ink: "#f4f1ff", inkSoft: "#c2c6e8", accent: "#f72585", accent2: "#4cc9f0", foil: "silver", surface: "#03050f", surface2: "#141a3e", envelope: "#eeeef6", envelope2: "#0b0f2a", wax: "#ffd166" }),
    ],
    styles: ["Signature", "Diwali", "Fun"],
    effects: ["Live crackers", "Tap to light", "Fuse intro", "Blast turn"],
    wed: { design: "pataka", intro: "fuse", turn: "blast", reveal: "crackle" },
    sample: festivalSample("night", "diwali", {
      primary: { name: "The Agarwal Family", subtitle: "Sanjay, Meenu, Kabir & Tanvi" },
      closing: { title: "Have a blast!", names: ["The Agarwal Family"] },
      events: [{ id: "f1", kind: "other", name: "Cracker Night on the Terrace", date: "2026-11-08", time: "20:30", venue: "Agarwal House", address: "Sector 15, Noida", note: "Green crackers only · bring the kids!" }],
      rsvp: { enabled: true, contacts: [{ name: "Sanjay Agarwal", phone: "+91 98111 22334" }] },
    }),
  },
  {
    id: "mithai-box",
    name: "Mithai Box",
    category: "festival",
    signature: true,
    tagline: "A luxury box of Diwali sweets opens in 3D. Tap to have one",
    paper: "linen",
    ornament: "none",
    backdrop: "linen",
    petals: "rose",
    fonts: { display: "var(--f-playfair)", script: "var(--f-great-vibes)", body: "var(--f-montserrat)" },
    palettes: [
      P({ id: "rani", label: "Rani Pink Box", paper: "#f3e6d8", paper2: "#e6d2bc", ink: "#4a1a28", inkSoft: "#8a5a66", accent: "#d4a72c", accent2: "#f6c9d6", foil: "gold", surface: "#d8c8b4", surface2: "#bba78f", envelope: "#fff6ea", envelope2: "#a8104f", wax: "#fff1c9" }),
      P({ id: "royal", label: "Royal Blue Box", paper: "#ece6dc", paper2: "#dcd2c2", ink: "#16244a", inkSoft: "#56658a", accent: "#d4a72c", accent2: "#c9d8f6", foil: "gold", surface: "#cfc6b8", surface2: "#b3a895", envelope: "#f7f3ec", envelope2: "#1d3a8a", wax: "#fff1c9" }),
      P({ id: "emerald", label: "Emerald Box", paper: "#efe8da", paper2: "#e0d4bd", ink: "#173a2a", inkSoft: "#5a7a66", accent: "#d4a72c", accent2: "#cfe8d6", foil: "gold", surface: "#d2c8b4", surface2: "#b6a991", envelope: "#f8f4ea", envelope2: "#0f5a3c", wax: "#fff1c9" }),
      P({ id: "saffron", label: "Saffron Box", paper: "#f6ecdc", paper2: "#ead8bd", ink: "#4a2410", inkSoft: "#8a5e40", accent: "#7a1c1c", accent2: "#ffe0b8", foil: "gold", surface: "#dcccb4", surface2: "#bfab8e", envelope: "#fff7ec", envelope2: "#d9631e", wax: "#fff1c9" }),
    ],
    styles: ["Signature", "Diwali", "Playful"],
    effects: ["3D gift box", "Tap to eat", "Silver varq", "Cube turn"],
    wed: { design: "mithai", intro: "unbox", turn: "cube", reveal: "sweet" },
    sample: festivalSample("rani", "diwali", {
      primary: { name: "The Joshi Family", subtitle: "Prakash, Anita, Rohan & Diya" },
      closing: { title: "Sweet wishes", names: ["The Joshi Family"] },
      blessingLine: "May your Diwali be as sweet as these mithais",
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  {
    id: "pooja-mandir",
    name: "Pooja Mandir",
    category: "festival",
    signature: true,
    tagline: "A carved home mandir with aarti, bells and incense. Tap to ring the bell",
    paper: "silk",
    ornament: "none",
    backdrop: "wood",
    petals: "marigold",
    fonts: { display: "var(--f-rozha)", script: "var(--f-great-vibes)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "maroon", label: "Maroon Wall", paper: "#3e0c12", paper2: "#5e1a20", ink: "#fbecd2", inkSoft: "#e4bf92", accent: "#a8102e", accent2: "#f3c64a", foil: "gold", surface: "#16040a", surface2: "#3e0c12", envelope: "#f6e8d0", envelope2: "#3e0c12", wax: "#c8102e" }),
      P({ id: "sandal", label: "Sandalwood", paper: "#efe0c4", paper2: "#e2cba3", ink: "#4a2410", inkSoft: "#8a5e3a", accent: "#7a1020", accent2: "#c98a1a", foil: "gold", surface: "#d4c19f", surface2: "#b8a07a", envelope: "#f8f0e0", envelope2: "#7a1020", wax: "#7a1020" }),
      P({ id: "peacock", label: "Peacock Blue", paper: "#0e3b4a", paper2: "#145a6a", ink: "#fbf0d8", inkSoft: "#cbe0d6", accent: "#5a1030", accent2: "#f3c64a", foil: "gold", surface: "#041820", surface2: "#0e3b4a", envelope: "#f3ecd8", envelope2: "#0e3b4a", wax: "#c8102e" }),
    ],
    styles: ["Signature", "Diwali", "Traditional"],
    effects: ["Live aarti", "Ring the bell", "Incense smoke", "Swing turn"],
    wed: { design: "mandir", intro: "aarti", turn: "swing", reveal: "bless" },
    sample: festivalSample("maroon", "diwali", {
      symbol: "ganesha-riddhi",
      primary: { name: "The Trivedi Family", subtitle: "Manoj, Kavita, Harsh & Nidhi" },
      closing: { title: "With blessings", names: ["The Trivedi Family"] },
      blessingLine: "May Maa Lakshmi and Shri Ganesh bless your home with joy and prosperity",
      events: [{ id: "f1", kind: "puja", name: "Lakshmi Puja", date: "2026-11-08", time: "19:15", venue: "Trivedi Residence", address: "Vastrapur, Ahmedabad", note: "Shubh muhurat 7:15 PM · prasad to follow" }],
      rsvp: { enabled: true, contacts: [{ name: "Manoj Trivedi", phone: "+91 98250 77889" }] },
    }),
  },
  {
    id: "diwali-ghar",
    name: "Diwali Ghar",
    category: "festival",
    signature: true,
    tagline: "A 3D house dressed in Diwali lights that turns slowly. Tap to change the lights",
    paper: "matte",
    ornament: "none",
    backdrop: "slate",
    petals: "marigold",
    fonts: { display: "var(--f-dm-serif)", script: "var(--f-allura)", body: "var(--f-jost)" },
    palettes: [
      P({ id: "night", label: "Starry Night", paper: "#0b1230", paper2: "#26336e", ink: "#fff3dc", inkSoft: "#c6cbe6", accent: "#ff6b9a", accent2: "#5ee6c8", foil: "gold", surface: "#03061a", surface2: "#121a42", envelope: "#f1e3c8", envelope2: "#0b1230", wax: "#ffc35a" }),
      P({ id: "twilight", label: "Twilight", paper: "#1e1033", paper2: "#5c2d70", ink: "#fff0f0", inkSoft: "#e2c4e2", accent: "#ff9e5e", accent2: "#ffd1f0", foil: "rosegold", surface: "#0a0414", surface2: "#2c1442", envelope: "#f6dcc8", envelope2: "#1e1033", wax: "#ffd27a" }),
      P({ id: "teal", label: "Teal Night", paper: "#06202a", paper2: "#145060", ink: "#f4f1e6", inkSoft: "#bfdcd8", accent: "#ff7b54", accent2: "#ffe08a", foil: "gold", surface: "#020c10", surface2: "#0a3440", envelope: "#efe6d0", envelope2: "#06202a", wax: "#ffd27a" }),
    ],
    styles: ["Signature", "Diwali", "3D"],
    effects: ["3D house", "Chasing lights", "Tap to change lights", "Dolly turn"],
    wed: { design: "ghar", intro: "switchon", turn: "dolly", reveal: "lights" },
    sample: festivalSample("night", "diwali", {
      primary: { name: "The Nair Family", subtitle: "Arjun, Lakshmi, Dev & Meera" },
      closing: { title: "From our home to yours", names: ["The Nair Family"] },
      events: [{ id: "f1", kind: "other", name: "Diwali at Home", date: "2026-11-08", time: "19:30", venue: "The Nair Home", address: "Indiranagar, Bengaluru", note: "Dinner, diyas and lots of mithai" }],
      rsvp: { enabled: true, contacts: [{ name: "Arjun Nair", phone: "+91 98450 66778" }] },
    }),
  },
  /* ---------------- Diwali collection, chunk 2 ---------------- */
  {
    id: "akash-kandil",
    name: "Akash Kandil",
    category: "festival",
    signature: true,
    tagline: "Sky lanterns rise over a still lake. Tap to release your own wish",
    paper: "matte",
    ornament: "none",
    backdrop: "slate",
    petals: "gold",
    fonts: { display: "var(--f-italiana)", script: "var(--f-great-vibes)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "dusk", label: "Dusk Violet", paper: "#120b2a", paper2: "#3c2c6c", ink: "#fff3e4", inkSoft: "#d7c9ee", accent: "#ff8a5c", accent2: "#ffd27a", foil: "gold", surface: "#05030f", surface2: "#1c1440", envelope: "#f3ece2", envelope2: "#120b2a", wax: "#ffb347" }),
      P({ id: "teal", label: "Twilight Teal", paper: "#06161f", paper2: "#1f4e5f", ink: "#f4f1e6", inkSoft: "#bcd6d6", accent: "#ff9e6b", accent2: "#ffe08a", foil: "gold", surface: "#020a0e", surface2: "#0e2f3a", envelope: "#efece2", envelope2: "#06161f", wax: "#ffb347" }),
      P({ id: "rose", label: "Rose Dusk", paper: "#1c0d1e", paper2: "#5c2c4c", ink: "#fff0ee", inkSoft: "#e6c4d2", accent: "#ffb38a", accent2: "#ffe0b0", foil: "rosegold", surface: "#0a040b", surface2: "#2e1530", envelope: "#f6e9ec", envelope2: "#1c0d1e", wax: "#ffb38a" }),
    ],
    styles: ["Signature", "Diwali", "Dreamy"],
    effects: ["Live sky lanterns", "Release a wish", "Lake reflections", "Glide turn"],
    wed: { design: "kandil", intro: "release", turn: "glide", reveal: "warmth" },
    sample: festivalSample("dusk", "diwali", {
      primary: { name: "The Kulkarni Family", subtitle: "Sachin, Rupali, Aditi & Om" },
      fromPrefix: "warm wishes from",
      closing: { title: "With love and light", names: ["The Kulkarni Family"] },
      blessingLine: "May every lantern carry your wishes to the stars",
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  {
    id: "deep-daan",
    name: "Deep Daan",
    category: "festival",
    signature: true,
    tagline: "Leaf-boat diyas drift down a river at night. Tap the water to float one",
    paper: "matte",
    ornament: "none",
    backdrop: "slate",
    petals: "marigold",
    fonts: { display: "var(--f-marcellus)", script: "var(--f-pinyon)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "river", label: "Night River", paper: "#06111a", paper2: "#143650", ink: "#fff4e2", inkSoft: "#c2d2dc", accent: "#ffb347", accent2: "#ffd88a", foil: "gold", surface: "#02070b", surface2: "#0b2234", envelope: "#f0ece2", envelope2: "#06111a", wax: "#ffb347" }),
      P({ id: "dusk", label: "Ghat Dusk", paper: "#140c1e", paper2: "#3c2c54", ink: "#fff1e8", inkSoft: "#d4c4dc", accent: "#ff9e5e", accent2: "#ffd4a0", foil: "gold", surface: "#06030a", surface2: "#241a34", envelope: "#f2ece6", envelope2: "#140c1e", wax: "#ff9e5e" }),
      P({ id: "emerald", label: "Emerald Night", paper: "#04140f", paper2: "#124034", ink: "#f4f2e4", inkSoft: "#bed6c8", accent: "#ffc04d", accent2: "#ffe39a", foil: "gold", surface: "#010806", surface2: "#0a2a20", envelope: "#eef0e4", envelope2: "#04140f", wax: "#ffc04d" }),
    ],
    styles: ["Signature", "Diwali", "Serene"],
    effects: ["Floating diyas", "Tap for ripples", "River reflections", "Current turn"],
    wed: { design: "deepdaan", intro: "ripple", turn: "current", reveal: "wave" },
    sample: festivalSample("river", "diwali", {
      primary: { name: "The Pandey Family", subtitle: "Alok, Shalini, Aryan & Pihu" },
      fromPrefix: "with love from",
      closing: { title: "With love and light", names: ["The Pandey Family"] },
      blessingLine: "May a thousand little lights float your way this Diwali",
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  {
    id: "sivakasi",
    name: "Sivakasi",
    category: "festival",
    signature: true,
    tagline: "Retro cracker-box label art with your family as the brand. Tap the fuse",
    paper: "matte",
    ornament: "none",
    backdrop: "wood",
    petals: "marigold",
    fonts: { display: "var(--f-anton)", script: "var(--f-righteous)", body: "var(--f-jost)" },
    palettes: [
      P({ id: "yellow", label: "Yellow Label", paper: "#ffd400", paper2: "#ffb300", ink: "#1a1410", inkSoft: "#5a3a10", accent: "#e10600", accent2: "#0a8f3c", foil: "gold", surface: "#3a2414", surface2: "#5a3a20", envelope: "#fff3c4", envelope2: "#e10600", wax: "#e10600" }),
      P({ id: "red", label: "Red Label", paper: "#e8342a", paper2: "#c21d14", ink: "#fff8e6", inkSoft: "#ffe1a0", accent: "#ffd400", accent2: "#0a8f3c", foil: "gold", surface: "#2a1410", surface2: "#4a2418", envelope: "#ffe8d0", envelope2: "#c21d14", wax: "#ffd400" }),
      P({ id: "blue", label: "Blue Label", paper: "#1f6fd6", paper2: "#1557b0", ink: "#fff8e6", inkSoft: "#d6e6ff", accent: "#ffd400", accent2: "#ff3d3d", foil: "gold", surface: "#14202e", surface2: "#20344a", envelope: "#e8f0ff", envelope2: "#1557b0", wax: "#ffd400" }),
    ],
    styles: ["Signature", "Diwali", "Retro"],
    effects: ["Retro label art", "Tap the fuse", "BOOM intro", "Fallback turn"],
    wed: { design: "sivakasi", intro: "boom", turn: "fallback", reveal: "slap" },
    sample: festivalSample("yellow", "diwali", {
      primary: { name: "The Bansal Family", subtitle: "Rakesh, Seema, Yash & Kavya" },
      fromPrefix: "with wishes from",
      closing: { title: "Have a blast!", names: ["The Bansal Family"] },
      blessingLine: "Wishing you a Diwali that's loud with laughter and bright with love",
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  {
    id: "shree-yantra",
    name: "Shree Yantra",
    category: "festival",
    signature: true,
    tagline: "Dhanteras blessings in sacred geometry, with a stream of gold",
    paper: "silk",
    ornament: "none",
    backdrop: "velvet",
    petals: "gold",
    fonts: { display: "var(--f-cinzel-deco)", script: "var(--f-pinyon)", body: "var(--f-garamond)" },
    palettes: [
      P({ id: "kumkum", label: "Kumkum Red", paper: "#3a070c", paper2: "#62101a", ink: "#fbe8c6", inkSoft: "#e4b98a", accent: "#e01e37", accent2: "#f3c64a", foil: "gold", surface: "#140205", surface2: "#3a070c", envelope: "#f6e6c9", envelope2: "#3a070c", wax: "#c8102e" }),
      P({ id: "midnight", label: "Midnight", paper: "#0a0f2a", paper2: "#1c2556", ink: "#f8ecd0", inkSoft: "#c8c0a0", accent: "#e8546a", accent2: "#f3c64a", foil: "gold", surface: "#03050f", surface2: "#0f1640", envelope: "#efe9db", envelope2: "#0a0f2a", wax: "#c8102e" }),
      P({ id: "emerald", label: "Emerald", paper: "#062a1e", paper2: "#0e4a34", ink: "#fbecc8", inkSoft: "#d6c48e", accent: "#e01e37", accent2: "#f3c64a", foil: "gold", surface: "#010e09", surface2: "#062a1e", envelope: "#f2e9cf", envelope2: "#062a1e", wax: "#c8102e" }),
      P({ id: "ivory", label: "Ivory & Gold", paper: "#f5ecd8", paper2: "#e8d9b8", ink: "#4a1a0c", inkSoft: "#8a5a3a", accent: "#c8102e", accent2: "#b8860b", foil: "gold", surface: "#d8cab0", surface2: "#bba98a", envelope: "#f8f2e6", envelope2: "#c8102e", wax: "#c8102e" }),
    ],
    styles: ["Signature", "Dhanteras", "Sacred"],
    effects: ["Shree Yantra", "Gold stream", "Tap for blessings", "Gilded turn"],
    wed: { design: "yantra", intro: "yantradraw", turn: "gilded", reveal: "radiate" },
    sample: festivalSample("kumkum", "dhanteras", {
      primary: { name: "The Goenka Family", subtitle: "Vinod, Sarita, Ankit & Riya" },
      fromPrefix: "with blessings from",
      closing: { title: "With blessings", names: ["The Goenka Family"] },
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  {
    id: "aatishbazi",
    name: "Aatishbazi",
    category: "festival",
    signature: true,
    tagline: "Rockets burst and their sparks spell your greeting and family name in the sky",
    paper: "matte",
    ornament: "none",
    backdrop: "slate",
    petals: "gold",
    fonts: { display: "var(--f-cinzel)", script: "var(--f-great-vibes)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "midnight", label: "Midnight", paper: "#05081a", paper2: "#1a2250", ink: "#fff4e4", inkSoft: "#c8cce6", accent: "#ff5fa2", accent2: "#ffd27a", foil: "gold", surface: "#020309", surface2: "#0f1434", envelope: "#f1ede4", envelope2: "#05081a", wax: "#9be7ff" }),
      P({ id: "purple", label: "Deep Purple", paper: "#0d0520", paper2: "#33185a", ink: "#fff0f6", inkSoft: "#d9c6ec", accent: "#ff9e5e", accent2: "#ffd6f0", foil: "rosegold", surface: "#05020c", surface2: "#1c0c34", envelope: "#f3ecf6", envelope2: "#0d0520", wax: "#ffe08a" }),
      P({ id: "blackgold", label: "Black & Gold", paper: "#050505", paper2: "#1d1a14", ink: "#fff3d6", inkSoft: "#c9b98a", accent: "#ff6b35", accent2: "#ffd27a", foil: "gold", surface: "#000", surface2: "#14120e", envelope: "#f3ecdc", envelope2: "#050505", wax: "#fff3c4" }),
    ],
    styles: ["Signature", "Diwali", "Spectacle"],
    effects: ["Firework lettering", "Your name in the sky", "Tap for fireworks", "Fizzle turn"],
    wed: { design: "aatish", intro: "launchname", turn: "fizzle", reveal: "sparkle" },
    sample: festivalSample("midnight", "diwali", {
      primary: { name: "The Kapoor Family", subtitle: "Rajiv, Simran, Arjun & Zoya" },
      closing: { title: "With love and light", names: ["The Kapoor Family"] },
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  /* ---------------- Diwali collection, chunk 3 ---------------- */
  {
    id: "chopda-pujan",
    name: "Chopda Pujan",
    category: "festival",
    signature: true,
    tagline: "The new year's bahi-khata: kumkum swastik, Shubh Labh, and blessings as the first entries",
    paper: "matte",
    ornament: "none",
    backdrop: "wood",
    petals: "marigold",
    fonts: { display: "var(--f-kalam)", script: "var(--f-kalam)", body: "var(--f-kalam)" },
    palettes: [
      P({ id: "laal", label: "Laal Bahi", paper: "#f6ecd2", paper2: "#efe1bf", ink: "#1d2b4f", inkSoft: "#5a6280", accent: "#c8102e", accent2: "#e2b13c", foil: "gold", surface: "#3a1f12", surface2: "#5a3420", envelope: "#f6ecd2", envelope2: "#a3161c", wax: "#a3161c" }),
      P({ id: "kesar", label: "Kesar", paper: "#f8eed6", paper2: "#f0e0bc", ink: "#2a1e14", inkSoft: "#6a5440", accent: "#d1361b", accent2: "#f3c64a", foil: "gold", surface: "#3a2414", surface2: "#5a3a20", envelope: "#f8eed6", envelope2: "#e0751b", wax: "#d9661a" }),
      P({ id: "hara", label: "Hara Bahi", paper: "#f4ecd6", paper2: "#e8dcbc", ink: "#13284a", inkSoft: "#4a5a70", accent: "#c8102e", accent2: "#d9b25a", foil: "gold", surface: "#1e2a1c", surface2: "#2e4030", envelope: "#f4ecd6", envelope2: "#1f5a3a", wax: "#1f5a3a" }),
    ],
    styles: ["Signature", "Diwali", "Business"],
    effects: ["Red bahi-khata", "Handwritten entries", "Rubber stamp", "Flip-up turn"],
    wed: { design: "chopda", intro: "khata", turn: "flipup", reveal: "ledger" },
    sample: festivalSample("laal", "nutanvarsh", {
      primary: { name: "Shah & Sons", subtitle: "Rasiklal, Hemant & Nirav Shah" },
      mantra: "|| Shree Ganeshay Namah ||",
      eyebrow: "Saal Mubarak",
      fromPrefix: "with best wishes from",
      blessingLine: "May your accounts overflow with joy and every entry this year be a profitable one",
      closing: { title: "With best wishes", names: ["Shah & Sons"] },
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  {
    id: "chitthi",
    name: "Chitthi",
    category: "festival",
    signature: true,
    tagline: "A handwritten Diwali letter on a blue inland letter, torn open and unfolded",
    paper: "matte",
    ornament: "none",
    backdrop: "wood",
    petals: "marigold",
    fonts: { display: "var(--f-kalam)", script: "var(--f-caveat)", body: "var(--f-kalam)" },
    palettes: [
      P({ id: "inland", label: "Inland Blue", paper: "#cfe0ee", paper2: "#b9cfe2", ink: "#1b3a8a", inkSoft: "#4a6aa8", accent: "#2c4a7a", accent2: "#c2410c", foil: "gold", surface: "#3a2414", surface2: "#5c321a", envelope: "#cfe0ee", envelope2: "#2c4a7a", wax: "#1f1f2a" }),
      P({ id: "aerogram", label: "Aerogramme", paper: "#dbe9f6", paper2: "#c6dbef", ink: "#14306e", inkSoft: "#3e5c9a", accent: "#b91c1c", accent2: "#1d4ed8", foil: "gold", surface: "#3a2414", surface2: "#5c321a", envelope: "#dbe9f6", envelope2: "#b91c1c", wax: "#26262e" }),
      P({ id: "postcard", label: "Old Postcard", paper: "#f1e6cc", paper2: "#e6d6b0", ink: "#20306a", inkSoft: "#5a5a7a", accent: "#7a3b1a", accent2: "#9d174d", foil: "gold", surface: "#3a2414", surface2: "#5c321a", envelope: "#f1e6cc", envelope2: "#7a3b1a", wax: "#2a1e14" }),
    ],
    styles: ["Signature", "Diwali", "Nostalgic"],
    effects: ["Inland letter", "Tears open & unfolds", "Your own postmark", "Dear (guest name)"],
    wed: { design: "chitthi", intro: "inland", turn: "fold", reveal: "pen" },
    sample: festivalSample("inland", "diwali", {
      primary: { name: "The Joshi Family", subtitle: "Mummy, Papa, Neha & Rohan" },
      fromPrefix: "With lots of love,",
      blessingLine: "May this Diwali fill your home with light, laughter and everything sweet",
      closing: { title: "With love and light", names: ["The Joshi Family"] },
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  {
    id: "diwali-times",
    name: "Diwali Times",
    category: "festival",
    signature: true,
    tagline: "Your greeting makes the front page: a vintage newspaper that spins in, with very local news",
    paper: "matte",
    ornament: "none",
    backdrop: "slate",
    petals: "gold",
    fonts: { display: "var(--f-oldstd)", script: "var(--f-fraktur)", body: "var(--f-oldstd)" },
    palettes: [
      P({ id: "newsprint", label: "Newsprint", paper: "#efe5cc", paper2: "#e4d6b4", ink: "#1c1a17", inkSoft: "#4a4436", accent: "#1c1a17", accent2: "#8a1c1c", foil: "gold", surface: "#121010", surface2: "#2a2420", envelope: "#efe5cc", envelope2: "#1c1a17", wax: "#8a1c1c" }),
      P({ id: "redbanner", label: "Red Banner", paper: "#f1e7cf", paper2: "#e6d8b6", ink: "#1c1a17", inkSoft: "#4a4436", accent: "#a3161c", accent2: "#a3161c", foil: "gold", surface: "#121010", surface2: "#2a2420", envelope: "#f1e7cf", envelope2: "#a3161c", wax: "#a3161c" }),
      P({ id: "sepia", label: "Sepia 1947", paper: "#e8d7b0", paper2: "#dcc79a", ink: "#3a2412", inkSoft: "#6a5034", accent: "#3a2412", accent2: "#7a3b1a", foil: "gold", surface: "#140d08", surface2: "#2e2014", envelope: "#e8d7b0", envelope2: "#3a2412", wax: "#7a3b1a" }),
    ],
    styles: ["Signature", "Diwali", "Fun"],
    effects: ["Spinning newspaper", "Halftone photo", "Funny local news", "Spin-out turn"],
    wed: { design: "akhbaar", intro: "newsspin", turn: "spinout", reveal: "press" },
    sample: festivalSample("redbanner", "diwali", {
      primary: { name: "The Agarwal Family", subtitle: "Manoj, Pooja, Kabir & Tara" },
      fromPrefix: "with warm wishes from",
      closing: { title: "With love and light", names: ["The Agarwal Family"] },
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  {
    id: "kaagaz",
    name: "Kaagaz",
    category: "festival",
    signature: true,
    tagline: "A paper-cut lightbox lit from inside. Move or tilt to look into the layers",
    paper: "matte",
    ornament: "none",
    backdrop: "velvet",
    petals: "marigold",
    fonts: { display: "var(--f-yeseva)", script: "var(--f-great-vibes)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "maroon", label: "Maroon Glow", paper: "#5a1424", paper2: "#3a0c16", ink: "#3a1208", inkSoft: "#6a3a20", accent: "#e8742a", accent2: "#ffcf7a", foil: "gold", surface: "#120406", surface2: "#2a0a10", envelope: "#f6e6c9", envelope2: "#5a1424", wax: "#ffcf7a" }),
      P({ id: "indigo", label: "Indigo Night", paper: "#1f2456", paper2: "#12163a", ink: "#1c1a3a", inkSoft: "#4a4870", accent: "#e8546a", accent2: "#ffd38a", foil: "gold", surface: "#05061a", surface2: "#12163a", envelope: "#efe9db", envelope2: "#1f2456", wax: "#ffd38a" }),
      P({ id: "teal", label: "Peacock", paper: "#0c4a4e", paper2: "#08303a", ink: "#0c2a2e", inkSoft: "#3a5a5a", accent: "#f08a3c", accent2: "#ffe08a", foil: "gold", surface: "#021012", surface2: "#08303a", envelope: "#eef0e4", envelope2: "#0c4a4e", wax: "#ffe08a" }),
    ],
    styles: ["Signature", "Diwali", "Paper art"],
    effects: ["Paper-cut layers", "Lit from inside", "Tilt parallax", "Dive turn"],
    wed: { design: "kaagaz", intro: "lightbox", turn: "dive", reveal: "papercut" },
    sample: festivalSample("maroon", "diwali", {
      primary: { name: "The Iyer Family", subtitle: "Venkat, Lakshmi, Arjun & Meera" },
      fromPrefix: "warm wishes from",
      closing: { title: "With love and light", names: ["The Iyer Family"] },
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
  {
    id: "shubh-tv",
    name: "Shubh TV",
    category: "festival",
    signature: true,
    tagline: "An 80s TV warms up and tunes in to your family's own Diwali Special. Turn the knob",
    paper: "matte",
    ornament: "none",
    backdrop: "wood",
    petals: "marigold",
    fonts: { display: "var(--f-shrikhand)", script: "var(--f-yeseva)", body: "var(--f-jost)" },
    palettes: [
      P({ id: "mustard", label: "Mustard 80s", paper: "#d9a441", paper2: "#c18a2a", ink: "#3a1a0a", inkSoft: "#6a4a2a", accent: "#8a3b12", accent2: "#c2185b", foil: "gold", surface: "#2a1608", surface2: "#4a2a10", envelope: "#fbf6ea", envelope2: "#8a3b12", wax: "#c2185b" }),
      P({ id: "teal", label: "Teal Room", paper: "#3f8a86", paper2: "#2f6e6a", ink: "#1d2a2a", inkSoft: "#4a5a5a", accent: "#e0b04a", accent2: "#c2185b", foil: "gold", surface: "#0e2422", surface2: "#1d3a38", envelope: "#fbf6ea", envelope2: "#2f6e6a", wax: "#e0b04a" }),
      P({ id: "pista", label: "Pista Green", paper: "#b3c98a", paper2: "#99b26e", ink: "#2a2a14", inkSoft: "#5a5a3a", accent: "#b44a2a", accent2: "#c2185b", foil: "gold", surface: "#262a14", surface2: "#3a4020", envelope: "#fbf6ea", envelope2: "#5a6e3a", wax: "#b44a2a" }),
    ],
    styles: ["Signature", "Diwali", "Retro"],
    effects: ["CRT power-on", "3 channels", "Turn the knob", "Switch-off turn"],
    wed: { design: "tv", intro: "tvon", turn: "crtoff", reveal: "tune" },
    sample: festivalSample("mustard", "diwali", {
      primary: { name: "The Malhotra Family", subtitle: "Ashok, Neeru, Varun & Ishita" },
      fromPrefix: "from",
      closing: { title: "Stay tuned for more love", names: ["The Malhotra Family"] },
      events: [],
      rsvp: { enabled: false, contacts: [] },
    }),
  },
];
