import type { BusinessData, InviteData } from "./types";

const base = {
  kind: "invite" as const,
  music: "santoor" as const,
  effects: { petals: true },
};

export const weddingSample = (palette: string): InviteData => ({
  ...base,
  palette,
  tradition: "hindu",
  hostSide: "groom",
  hashtag: "#RoAnTogether",
  info: [
    { label: "Stay", value: "Rooms are reserved for outstation guests at Hotel Rivera, Ashram Road" },
    { label: "Gifts", value: "Your blessings are our greatest gift" },
  ],
  symbol: "ganesha",
  mantra: "|| Shri Ganeshaya Namah ||",
  blessingLine: "With the divine blessings of Lord Ganesha and the grace of our elders",
  eyebrow: "Wedding Invitation",
  hosts: "Mr. Rajesh Mehta & Mrs. Sunita Mehta",
  inviteText: "request the honour of your presence at the wedding of their son",
  primary: {
    name: "Rohan",
    subtitle: "Son of Mr. Rajesh & Mrs. Sunita Mehta",
    parents: "Grandson of Late Shri Harilal Mehta",
  },
  secondary: {
    name: "Ananya",
    subtitle: "Daughter of Mr. Vikram & Mrs. Kavita Shah",
    parents: "Granddaughter of Shri Mohanlal Shah",
  },
  joiner: "weds",
  quote: "Two souls, one journey, and a lifetime of togetherness.",
  mainDateTime: "2026-12-12T19:30",
  mainEventId: "e5",
  events: [
    { id: "e1", kind: "ganesh", name: "Ganesh Sthapana", date: "2026-12-10", time: "09:00", venue: "Mehta Niwas", address: "14, Shanti Park Society, Paldi, Ahmedabad", audience: "family" },
    { id: "e2", kind: "haldi", name: "Haldi", date: "2026-12-10", time: "16:00", venue: "Mehta Niwas", address: "14, Shanti Park Society, Paldi, Ahmedabad", dressCode: "Shades of yellow" },
    { id: "e3", kind: "mehendi", name: "Mehendi", date: "2026-12-11", time: "11:00", venue: "The Courtyard, Hotel Rivera", address: "Ashram Road, Ahmedabad", dressCode: "Greens & florals" },
    { id: "e4", kind: "sangeet", name: "Sangeet Sandhya", date: "2026-12-11", time: "19:30", venue: "Grand Ballroom, Hotel Rivera", address: "Ashram Road, Ahmedabad" },
    { id: "e5", kind: "wedding", name: "Shubh Vivah", date: "2026-12-12", time: "19:30", venue: "Rajmahal Lawns", address: "SG Highway, Near Sola Bridge, Ahmedabad", note: "Hast Melap at 8:15 PM" },
    { id: "e6", kind: "reception", name: "Reception", date: "2026-12-13", time: "19:00", venue: "Rajmahal Lawns", address: "SG Highway, Near Sola Bridge, Ahmedabad", dressCode: "Formal / festive" },
  ],
  family: {
    enabled: true,
    title: "With Warm Regards",
    names: [
      "Smt. Kamla Mehta",
      "Mr. Suresh & Mrs. Neeta Mehta",
      "Mr. Anil & Mrs. Rekha Mehta",
      "Mr. Deepak & Mrs. Pooja Joshi",
    ],
    kidsTitle: "Eagerly Awaiting",
    kids: ["Aarav", "Myra", "Vihaan", "Kiara"],
    kidsLine: "Do come to our Chachu's wedding — we'll be waiting to dance with you!",
  },
  rsvp: {
    enabled: true,
    deadline: "2026-11-30",
    contacts: [
      { name: "Rajesh Mehta", phone: "+91 98250 12345" },
      { name: "Suresh Mehta", phone: "+91 98790 67890" },
    ],
  },
  closing: {
    title: "With Best Compliments From",
    names: ["The Mehta & Shah Families", "Friends & Well-wishers"],
  },
});

export const engagementSample = (palette: string): InviteData => ({
  ...base,
  palette,
  symbol: "none",
  mantra: "",
  blessingLine: "With the blessings of our families",
  eyebrow: "Engagement Ceremony",
  hosts: "The Kapoor & Iyer Families",
  inviteText: "joyfully invite you to celebrate the ring ceremony of",
  primary: { name: "Kabir", subtitle: "Son of Mr. Arun & Mrs. Meera Kapoor" },
  secondary: { name: "Tara", subtitle: "Daughter of Mr. Ravi & Mrs. Lakshmi Iyer" },
  joiner: "&",
  quote: "A promise, a ring, and forever.",
  mainDateTime: "2026-11-22T18:30",
  mainEventId: "e1",
  events: [
    { id: "e1", name: "Ring Ceremony", date: "2026-11-22", time: "18:30", venue: "The Leela Ambience", address: "Gurugram, Haryana", note: "Followed by dinner" },
  ],
  family: { enabled: false, title: "", names: [], kidsTitle: "", kids: [] },
  rsvp: {
    enabled: true,
    deadline: "2026-11-15",
    contacts: [{ name: "Arun Kapoor", phone: "+91 98110 45678" }],
  },
  closing: { title: "With Love", names: ["The Kapoor & Iyer Families"] },
});

export const shopSample = (palette: string): InviteData => ({
  ...base,
  palette,
  symbol: "ganesha",
  mantra: "|| Shree Ganeshaya Namah ||",
  blessingLine: "With the blessings of Lord Ganesha & Maa Lakshmi",
  eyebrow: "Grand Opening",
  hosts: "Patel Family",
  inviteText: "cordially invites you to the auspicious opening of",
  primary: { name: "Shree Krishna Jewellers", subtitle: "Gold · Diamond · Silver" },
  joiner: "",
  quote: "Your presence will make our new beginning truly auspicious.",
  mainDateTime: "2026-11-20T10:30",
  mainEventId: "e2",
  events: [
    { id: "e1", name: "Lakshmi Pujan", date: "2026-11-20", time: "08:30", venue: "Shree Krishna Jewellers", address: "Shop 4, Rajhans Complex, Ring Road, Surat" },
    { id: "e2", name: "Ribbon Cutting", date: "2026-11-20", time: "10:30", venue: "Shree Krishna Jewellers", address: "Shop 4, Rajhans Complex, Ring Road, Surat", note: "Opening offers for the first 100 guests" },
  ],
  family: { enabled: false, title: "", names: [], kidsTitle: "", kids: [] },
  rsvp: {
    enabled: true,
    contacts: [{ name: "Mahesh Patel", phone: "+91 99090 11223" }],
  },
  closing: { title: "Awaiting Your Gracious Presence", names: ["Mahesh Patel & Family"] },
});

export const grihaSample = (palette: string): InviteData => ({
  ...base,
  palette,
  symbol: "kalash",
  mantra: "|| Shubh Griha Pravesh ||",
  blessingLine: "With the blessings of Lord Ganesha and our ancestors",
  eyebrow: "Griha Pravesh",
  hosts: "Mr. Amit & Mrs. Priya Deshmukh",
  inviteText: "invite you to bless our new home on the occasion of the Griha Pravesh Puja of",
  primary: { name: "Shubh Aangan", subtitle: "B-702, Green Meadows, Baner, Pune" },
  joiner: "",
  quote: "A house becomes a home with the blessings of loved ones.",
  mainDateTime: "2026-12-06T09:00",
  mainEventId: "e1",
  events: [
    { id: "e1", name: "Vastu Shanti & Griha Pravesh Puja", date: "2026-12-06", time: "09:00", venue: "Shubh Aangan", address: "B-702, Green Meadows, Baner, Pune" },
    { id: "e2", name: "Mahaprasad (Lunch)", date: "2026-12-06", time: "12:30", venue: "Clubhouse, Green Meadows", address: "Baner, Pune" },
  ],
  family: {
    enabled: true,
    title: "With Warm Regards",
    names: ["Smt. Shalini Deshmukh", "Mr. Nitin & Mrs. Asha Deshmukh"],
    kidsTitle: "Eagerly Awaiting",
    kids: ["Ira", "Advait"],
    kidsLine: "Come see our new home!",
  },
  rsvp: {
    enabled: true,
    contacts: [{ name: "Amit Deshmukh", phone: "+91 98220 33445" }],
  },
  closing: { title: "Awaiting Your Blessings", names: ["The Deshmukh Family"] },
});

export const businessSample = (palette: string, persona: Partial<BusinessData> = {}): BusinessData => ({
  kind: "business",
  palette,
  name: "Aditi Sharma",
  title: "Founder & Principal Architect",
  company: "Studio Aangan",
  tagline: "Architecture · Interiors · Landscape",
  phone: "+91 98765 43210",
  whatsapp: "+91 98765 43210",
  email: "aditi@studioaangan.in",
  website: "studioaangan.in",
  address: "402, Iscon Elegance, Prahlad Nagar, Ahmedabad",
  services: ["Residential", "Commercial", "Interior Design", "Landscape"],
  socials: { instagram: "studioaangan", linkedin: "aditi-sharma" },
  ...persona,
});

/** A believable persona per business design, so each preview reads like a real card. */
export const PERSONAS: Record<string, Partial<BusinessData>> = {
  holo: {
    name: "Riya Kapoor",
    title: "Creative Director",
    company: "Pixel Mantra",
    tagline: "Brand · Motion · Digital",
    phone: "+91 99200 11874",
    whatsapp: "+91 99200 11874",
    email: "riya@pixelmantra.in",
    website: "pixelmantra.in",
    address: "12, Pali Hill, Bandra West, Mumbai",
    services: ["Branding", "Motion Design", "Web", "Social"],
    socials: { instagram: "pixelmantra", linkedin: "riya-kapoor" },
  },
  metal: {
    name: "Vikram Malhotra",
    title: "Managing Partner",
    company: "Malhotra Capital",
    tagline: "Private Equity · Advisory",
    phone: "+91 98100 45210",
    whatsapp: "+91 98100 45210",
    email: "vikram@malhotracapital.in",
    website: "malhotracapital.in",
    address: "DLF Cyber City, Tower C, Gurugram",
    services: ["Growth Equity", "M&A Advisory", "Family Office"],
    socials: { linkedin: "vikram-malhotra" },
  },
  walnut: {
    name: "Arjun Mehta",
    title: "Master Craftsman",
    company: "Mehta Woodworks",
    tagline: "Handcrafted furniture since 1978",
    phone: "+91 97240 88113",
    whatsapp: "+91 97240 88113",
    email: "arjun@mehtawoodworks.in",
    website: "mehtawoodworks.in",
    address: "Plot 18, GIDC Estate, Vadodara",
    services: ["Custom Furniture", "Restoration", "Joinery"],
    socials: { instagram: "mehtawoodworks" },
  },
  acrylic: {
    name: "Neha Iyer",
    title: "Lead Product Designer",
    company: "Lumen Labs",
    tagline: "Design · Research · Product",
    phone: "+91 90080 27364",
    whatsapp: "+91 90080 27364",
    email: "neha@lumenlabs.io",
    website: "lumenlabs.io",
    address: "HSR Layout, Sector 2, Bengaluru",
    services: ["Product Design", "UX Research", "Design Systems"],
    socials: { linkedin: "neha-iyer" },
  },
  neon: {
    name: "Zoya Khan",
    title: "Owner & Head Barista",
    company: "Brew Theory",
    tagline: "Coffee · Vinyl · Late nights",
    phone: "+91 98330 61925",
    whatsapp: "+91 98330 61925",
    email: "hello@brewtheory.cafe",
    website: "brewtheory.cafe",
    address: "Koregaon Park, Lane 6, Pune",
    services: ["Specialty Coffee", "Live Music", "Events"],
    socials: { instagram: "brewtheory" },
  },
  block: {
    name: "Meera Rathore",
    title: "Founder & Designer",
    company: "Rangrez",
    tagline: "Hand block-printed textiles · Jaipur",
    phone: "+91 94140 55218",
    whatsapp: "+91 94140 55218",
    email: "meera@rangrez.in",
    website: "rangrez.in",
    address: "Sanganer, Tonk Road, Jaipur",
    services: ["Sarees", "Dupattas", "Home Linen", "Custom Prints"],
    socials: { instagram: "rangrez.jaipur" },
  },
  layers: {
    name: "Ananya Rao",
    title: "Founder · Trip Curator",
    company: "Wanderwild",
    tagline: "Himalayan treks & slow travel",
    phone: "+91 98450 70331",
    whatsapp: "+91 98450 70331",
    email: "ananya@wanderwild.in",
    website: "wanderwild.in",
    address: "Old Manali Road, Manali, Himachal Pradesh",
    services: ["Treks", "Homestays", "Group Trips"],
    socials: { instagram: "wanderwild.in" },
  },
  swiss: {
    name: "Rohan Desai",
    title: "Chartered Accountant",
    company: "Desai & Associates",
    tagline: "Tax · Audit · Advisory",
    phone: "+91 98251 30490",
    whatsapp: "+91 98251 30490",
    email: "rohan@desaica.in",
    website: "desaica.in",
    address: "305, Shivalik Plaza, Ambawadi, Ahmedabad",
    services: ["GST", "Income Tax", "Audit", "Startup Advisory"],
    socials: { linkedin: "rohan-desai-ca" },
  },
  marble: {
    name: "Kavya Jhaveri",
    title: "Director",
    company: "Jhaveri Jewels",
    tagline: "Diamonds & polki · Since 1952",
    phone: "+91 98200 71145",
    whatsapp: "+91 98200 71145",
    email: "kavya@jhaverijewels.in",
    website: "jhaverijewels.in",
    address: "Opera House, Charni Road, Mumbai",
    services: ["Bridal", "Polki", "Solitaires", "Bespoke"],
    socials: { instagram: "jhaverijewels" },
  },
  kraft: {
    name: "Sahil Verma",
    title: "Founder & Head Baker",
    company: "Crumb & Co.",
    tagline: "Sourdough · Bakes · Organic",
    phone: "+91 98110 92376",
    whatsapp: "+91 98110 92376",
    email: "bake@crumbandco.in",
    website: "crumbandco.in",
    address: "Shahpur Jat, New Delhi",
    services: ["Sourdough", "Cakes", "Wholesale", "Workshops"],
    socials: { instagram: "crumbandco" },
  },
  aurora: { name: "Kabir Anand", title: "Co-founder & CEO", company: "Nimbus AI", tagline: "Automation for growing Indian businesses", phone: "+91 98860 44120", whatsapp: "+91 98860 44120", email: "kabir@nimbusai.in", website: "nimbusai.in", address: "Indiranagar, Bengaluru", services: ["AI Agents", "Workflow Automation", "Analytics"], socials: { linkedin: "kabiranand", x: "kabir_builds" } },
  sunset: { name: "Tara Menon", title: "Founder & Lead Photographer", company: "Golden Hour Studio", tagline: "Portraits · Weddings · Brands", phone: "+91 94470 21836", whatsapp: "+91 94470 21836", email: "tara@goldenhour.studio", website: "goldenhour.studio", address: "Fort Kochi, Kerala", services: ["Portraits", "Weddings", "Brand shoots"], socials: { instagram: "goldenhour.studio" } },
  glass: { name: "Ishaan Gupta", title: "Head of Product", company: "Orbit Pay", tagline: "Payments that simply work", phone: "+91 98111 60427", whatsapp: "+91 98111 60427", email: "ishaan@orbitpay.in", website: "orbitpay.in", address: "Sector 44, Gurugram", services: ["UPI", "Cards", "Payouts"], socials: { linkedin: "ishaangupta" } },
  bento: { name: "Sneha Kulkarni", title: "Brand Strategist", company: "Fold Studio", tagline: "Brands people remember", phone: "+91 98220 71456", whatsapp: "+91 98220 71456", email: "sneha@foldstudio.in", website: "foldstudio.in", address: "Baner, Pune", services: ["Branding", "Websites", "Content", "Packaging"], socials: { instagram: "fold.studio", linkedin: "snehakulkarni" } },
  brutal: { name: "Aryan Shah", title: "Founder & Creative Lead", company: "Loud Lab", tagline: "Ideas that refuse to whisper", phone: "+91 99300 18264", whatsapp: "+91 99300 18264", email: "aryan@loudlab.co", website: "loudlab.co", address: "Lower Parel, Mumbai", services: ["Campaigns", "Social", "Merch"], socials: { instagram: "loudlab.co" } },
  chrome: { name: "Myra D'Souza", title: "DJ · Producer", company: "Myra Wave", tagline: "Electronic · Live sets", phone: "+91 98230 55402", whatsapp: "+91 98230 55402", email: "book@myrawave.com", website: "myrawave.com", address: "Anjuna, Goa", services: ["Club nights", "Festivals", "Private"], socials: { instagram: "myrawave", youtube: "myrawave" } },
  groovy: { name: "Rhea Bose", title: "Owner & Curator", company: "Funky Thrift", tagline: "Vintage clothing & records", phone: "+91 98300 62718", whatsapp: "+91 98300 62718", email: "hello@funkythrift.in", website: "funkythrift.in", address: "Park Street, Kolkata", services: ["Vintage", "Vinyl", "Upcycled"], socials: { instagram: "funkythrift" } },
  deco: { name: "Arjun Kapoor", title: "Proprietor", company: "The Gatsby Lounge", tagline: "Cocktails & Jazz", phone: "+91 98201 33090", whatsapp: "+91 98201 33090", email: "reserve@gatsbylounge.in", website: "gatsbylounge.in", address: "Colaba, Mumbai", services: ["Cocktails", "Live Jazz", "Private events"], socials: { instagram: "gatsbylounge" } },
  enso: { name: "Meenakshi Iyer", title: "Yoga & Meditation Teacher", company: "Stillwater Yoga", tagline: "Breathe · Move · Rest", phone: "+91 97600 12538", whatsapp: "+91 97600 12538", email: "om@stillwater.yoga", website: "stillwater.yoga", address: "Tapovan, Rishikesh", services: ["Hatha", "Meditation", "Retreats"], socials: { instagram: "stillwater.yoga" } },
  mono: { name: "Dev Malhotra", title: "Architect", company: "Studio Dev", tagline: "Architecture", phone: "+91 98100 77231", whatsapp: "+91 98100 77231", email: "dev@studiodev.in", website: "studiodev.in", address: "Hauz Khas Village, New Delhi", services: ["Residences", "Retail"], socials: {} },
  topo: { name: "Karan Thakur", title: "Founder & Lead Guide", company: "High Trails", tagline: "Himalayan expeditions", phone: "+91 94180 36529", whatsapp: "+91 94180 36529", email: "karan@hightrails.in", website: "hightrails.in", address: "McLeod Ganj, Dharamshala", services: ["Treks", "Summits", "Camps"], socials: { instagram: "hightrails.in" } },
  terrazzo: { name: "Pooja Nair", title: "Principal Interior Designer", company: "Casa Pooja", tagline: "Homes with character", phone: "+91 99860 24173", whatsapp: "+91 99860 24173", email: "pooja@casapooja.in", website: "casapooja.in", address: "Koramangala, Bengaluru", services: ["Homes", "Cafés", "Styling"], socials: { instagram: "casapooja" } },
  memphis: { name: "Anika Joshi", title: "Illustrator", company: "Anika Draws", tagline: "Illustration · Murals · Picture books", phone: "+91 98905 63218", whatsapp: "+91 98905 63218", email: "hi@anikadraws.com", website: "anikadraws.com", address: "Kothrud, Pune", services: ["Illustration", "Murals", "Books"], socials: { instagram: "anikadraws" } },
  duotone: { name: "Vivaan Rao", title: "Director & Cinematographer", company: "Rao Visuals", tagline: "Films · Ads · Music videos", phone: "+91 90000 58214", whatsapp: "+91 90000 58214", email: "vivaan@raovisuals.in", website: "raovisuals.in", address: "Jubilee Hills, Hyderabad", services: ["Ad films", "Music videos", "Documentary"], socials: { instagram: "raovisuals", youtube: "raovisuals" } },
  warli: { name: "Sunita Patil", title: "Founder", company: "Warli Crafts Co.", tagline: "Tribal art from Dahanu", phone: "+91 95520 18347", whatsapp: "+91 95520 18347", email: "sunita@warlicrafts.in", website: "warlicrafts.in", address: "Dahanu, Palghar, Maharashtra", services: ["Wall art", "Home décor", "Workshops"], socials: { instagram: "warlicrafts" }, nameLocal: "सुनीता पाटील" },
  jaali: { name: "Faizan Qureshi", title: "Fourth-generation Perfumer", company: "Qureshi Attars", tagline: "Perfumers since 1911", phone: "+91 94150 27381", whatsapp: "+91 94150 27381", email: "faizan@qureshiattars.in", website: "qureshiattars.in", address: "Chowk, Lucknow", services: ["Attars", "Oudh", "Gift boxes"], socials: { instagram: "qureshiattars" } },
  bandhani: { name: "Hetal Parmar", title: "Designer & Founder", company: "Bandhej House", tagline: "Bandhani sarees & dupattas", phone: "+91 98250 43716", whatsapp: "+91 98250 43716", email: "hetal@bandhejhouse.in", website: "bandhejhouse.in", address: "Chandni Chowk, Jamnagar", services: ["Sarees", "Dupattas", "Bridal"], socials: { instagram: "bandhejhouse" }, nameLocal: "હેતલ પરમાર" },
  ajrakh: { name: "Ismail Khatri", title: "Master Craftsman", company: "Khatri Ajrakh", tagline: "Hand block ajrakh from Kutch", phone: "+91 94262 15038", whatsapp: "+91 94262 15038", email: "ismail@khatriajrakh.in", website: "khatriajrakh.in", address: "Ajrakhpur, Kutch", services: ["Stoles", "Yardage", "Bedding"], socials: { instagram: "khatriajrakh" } },
  kanjivaram: { name: "Lakshmi Sundaram", title: "Proprietor", company: "Sri Lakshmi Silks", tagline: "Pure Kanjivaram silks", phone: "+91 94440 26185", whatsapp: "+91 94440 26185", email: "lakshmi@srilakshmisilks.in", website: "srilakshmisilks.in", address: "Gandhi Road, Kanchipuram", services: ["Bridal silks", "Pattu", "Custom weaving"], socials: { instagram: "srilakshmisilks" } },
  kolam: { name: "Anand Krishnan", title: "Founder & Head Cook", company: "Kolam Kitchen", tagline: "South Indian home food", phone: "+91 98410 52763", whatsapp: "+91 98410 52763", email: "orders@kolamkitchen.in", website: "kolamkitchen.in", address: "Mylapore, Chennai", services: ["Tiffin", "Meals", "Catering"], socials: { instagram: "kolamkitchen" } },
  madhubani: { name: "Pallavi Jha", title: "Artist", company: "Mithila Art House", tagline: "Madhubani paintings & workshops", phone: "+91 94310 68245", whatsapp: "+91 94310 68245", email: "pallavi@mithilaart.in", website: "mithilaart.in", address: "Jitwarpur, Madhubani, Bihar", services: ["Paintings", "Commissions", "Workshops"], socials: { instagram: "mithilaarthouse" }, nameLocal: "पल्लवी झा" },
  seal: { name: "Aanya Oberoi", title: "Founder & Creative Director", company: "Maison Aanya", tagline: "Couture · Bridal · Bespoke", phone: "+91 98110 90345", whatsapp: "+91 98110 90345", email: "atelier@maisonaanya.com", website: "maisonaanya.com", address: "Mehrauli, New Delhi", services: ["Couture", "Bridal", "Bespoke"], socials: { instagram: "maisonaanya" } },
  clinic: { name: "Dr. Priya Sharma", title: "MBBS, MD (Paediatrics)", company: "Little Steps Child Clinic", tagline: "Care for every little step", phone: "+91 98250 11408", whatsapp: "+91 98250 11408", email: "care@littlesteps.clinic", website: "littlesteps.clinic", address: "Satellite Road, Ahmedabad", services: ["Vaccination", "Newborn care", "Nutrition"], socials: {}, nameLocal: "डॉ. प्रिया शर्मा", extras: [{ label: "Reg. No.", value: "G-38412" }, { label: "Timings", value: "Mon–Sat · 10–1, 5–8" }] },
  advocate: { name: "Adv. Rajiv Menon", title: "Advocate, High Court of Bombay", company: "Menon & Associates", tagline: "Civil · Corporate · Property", phone: "+91 98200 47813", whatsapp: "+91 98200 47813", email: "rajiv@menonlaw.in", website: "menonlaw.in", address: "Fort, Mumbai", services: ["Civil", "Corporate", "Property"], socials: { linkedin: "rajivmenon-law" }, extras: [{ label: "Enrol. No.", value: "MAH/1234/2008" }] },
  skyline: { name: "Nikhil Agarwal", title: "Senior Property Consultant", company: "Skyline Realty", tagline: "Homes · Commercial · Investments", phone: "+91 98921 33607", whatsapp: "+91 98921 33607", email: "nikhil@skylinerealty.in", website: "skylinerealty.in", address: "Powai, Mumbai", services: ["Buy", "Sell", "Lease"], socials: { instagram: "skylinerealty" }, extras: [{ label: "RERA", value: "A51800012345" }] },
  salon: { name: "Simran Kaur", title: "Founder & Senior Stylist", company: "Velvet Salon", tagline: "Hair · Skin · Bridal", phone: "+91 98140 72619", whatsapp: "+91 98140 72619", email: "book@velvetsalon.in", website: "velvetsalon.in", address: "Sector 17, Chandigarh", services: ["Hair", "Skin", "Bridal"], socials: { instagram: "velvetsalon" } },
  fitness: { name: "Rahul Yadav", title: "Head Coach", company: "Iron Pulse", tagline: "Strength · Conditioning · Nutrition", phone: "+91 99990 26314", whatsapp: "+91 99990 26314", email: "coach@ironpulse.in", website: "ironpulse.in", address: "Sector 18, Noida", services: ["Personal training", "Group classes", "Diet plans"], socials: { instagram: "ironpulse.gym" } },
  chalk: { name: "Farhan Ali", title: "Owner & Chef", company: "Chai Chalk", tagline: "Chai, snacks & good vibes", phone: "+91 90300 45827", whatsapp: "+91 90300 45827", email: "hello@chaichalk.in", website: "chaichalk.in", address: "Banjara Hills, Hyderabad", services: ["Chai", "Snacks", "Catering"], socials: { instagram: "chaichalk" }, extras: [{ label: "Open", value: "8am – 11pm, all days" }] },
  terminal: { name: "Aditya Verma", title: "Full-stack Developer", company: "adityaverma.dev", tagline: "I build fast, friendly web apps.", phone: "+91 98450 81236", whatsapp: "+91 98450 81236", email: "hi@adityaverma.dev", website: "adityaverma.dev", address: "HSR Layout, Bengaluru", services: ["React", "Node", "Cloud"], socials: { linkedin: "adityaverma", x: "adi_codes" } },
  blueprint: { name: "Vikas Patel", title: "Civil Engineer & Contractor", company: "Patel Constructions", tagline: "Design · Build · Renovate", phone: "+91 98795 30614", whatsapp: "+91 98795 30614", email: "vikas@patelconstructions.in", website: "patelconstructions.in", address: "Adajan, Surat", services: ["Residential", "Commercial", "Renovation"], socials: {} },
  aperture: { name: "Nisha Reddy", title: "Photographer & Filmmaker", company: "Frame by Nisha", tagline: "Weddings · Fashion · Films", phone: "+91 99490 71253", whatsapp: "+91 99490 71253", email: "nisha@framebynisha.in", website: "framebynisha.in", address: "Gachibowli, Hyderabad", services: ["Weddings", "Fashion", "Films"], socials: { instagram: "framebynisha", youtube: "framebynisha" } },
  notebook: { name: "Kavita Deshpande", title: "Maths & Science Tutor", company: "Bright Minds Classes", tagline: "Classes 6–12 · CBSE / ICSE", phone: "+91 98230 64519", whatsapp: "+91 98230 64519", email: "kavita@brightminds.in", website: "brightminds.in", address: "Dharampeth, Nagpur", services: ["Maths", "Science", "Board prep", "Olympiad"], socials: {} },
  jyotish: { name: "Pt. Shivkumar Shastri", title: "Vedic Astrologer", company: "Shastri Jyotish Kendra", tagline: "Kundli · Vastu · Muhurat", phone: "+91 94150 63027", whatsapp: "+91 94150 63027", email: "shastri@jyotishkendra.in", website: "jyotishkendra.in", address: "Assi Ghat, Varanasi", services: ["Kundli", "Vastu", "Muhurat"], socials: { youtube: "shastrijyotish" }, nameLocal: "पं. शिवकुमार शास्त्री" },
  dukaan: { name: "Ramesh Gupta", title: "Proprietor", company: "Gupta General Store", tagline: "Groceries · Dairy · Home needs", phone: "+91 98260 41372", whatsapp: "+91 98260 41372", email: "", website: "", address: "Rajwada, Indore", services: ["Free home delivery", "UPI accepted", "Bulk orders"], socials: {}, nameLocal: "रमेश गुप्ता", extras: [{ label: "GSTIN", value: "23ABCDE1234F1Z5" }, { label: "Open", value: "7am – 10pm, all days" }] },
  boarding: { name: "Neel Joshi", title: "Travel Consultant", company: "Jetset Holidays", tagline: "Flights · Visas · Tours", phone: "+91 98224 58013", whatsapp: "+91 98224 58013", email: "neel@jetsetholidays.in", website: "jetsetholidays.in", address: "FC Road, Pune", services: ["Flights", "Visas", "Tours"], socials: { instagram: "jetsetholidays" } },
  vinyl: { name: "Arjun Sethi", title: "DJ & Producer", company: "Bassline", tagline: "Weddings · Clubs · Private", phone: "+91 98700 32516", whatsapp: "+91 98700 32516", email: "book@bassline.in", website: "bassline.in", address: "Bandra, Mumbai", services: ["Weddings", "Clubs", "Private"], socials: { instagram: "bassline.dj" } },
  loyalty: { name: "Maya Fernandes", title: "Owner", company: "Bean There", tagline: "Coffee · Bakes · Wi-Fi", phone: "+91 98221 70536", whatsapp: "+91 98221 70536", email: "hello@beanthere.cafe", website: "beanthere.cafe", address: "Panjim, Goa", services: ["Coffee", "Bakes"], socials: { instagram: "beanthere.goa" } },
  circuit: { name: "Sameer Khan", title: "Founder & Hardware Engineer", company: "VoltEdge", tagline: "IoT · PCB design · Repairs", phone: "+91 99001 63528", whatsapp: "+91 99001 63528", email: "sameer@voltedge.in", website: "voltedge.in", address: "SP Road, Bengaluru", services: ["IoT", "PCB design", "Repairs"], socials: { linkedin: "sameerkhan-hw" } },
  botanical: { name: "Dr. Anjali Vaidya", title: "Ayurvedic Physician (BAMS)", company: "Prakriti Ayurveda", tagline: "Natural healing & wellness", phone: "+91 94470 83216", whatsapp: "+91 94470 83216", email: "care@prakritiayurveda.in", website: "prakritiayurveda.in", address: "Kottakkal, Kerala", services: ["Panchakarma", "Consultation", "Herbal care"], socials: { instagram: "prakritiayurveda" } },
  carbon: { name: "Harpreet Singh", title: "Owner", company: "Singh Motors", tagline: "Service · Detailing · Performance", phone: "+91 98150 27394", whatsapp: "+91 98150 27394", email: "service@singhmotors.in", website: "singhmotors.in", address: "Ferozepur Road, Ludhiana", services: ["Service", "Detailing", "Tuning"], socials: { instagram: "singhmotors" } },
  portrait: { name: "Amit Sinha", title: "Life Coach & Speaker", company: "Amit Sinha Coaching", tagline: "Clarity · Confidence · Growth", phone: "+91 98310 46527", whatsapp: "+91 98310 46527", email: "amit@amitsinha.coach", website: "amitsinha.coach", address: "Salt Lake, Kolkata", services: ["1:1 coaching", "Workshops", "Keynotes"], socials: { linkedin: "amitsinhacoach", youtube: "amitsinha" } },
  split: { name: "Kriti Arora", title: "Fashion Stylist", company: "Kriti Styles", tagline: "Personal styling · Shoots", phone: "+91 98111 52730", whatsapp: "+91 98111 52730", email: "kriti@kritistyles.in", website: "kritistyles.in", address: "Greater Kailash, New Delhi", services: ["Wardrobe", "Shoots", "Weddings"], socials: { instagram: "kritistyles" } },
  shield: { name: "Suresh Iyer", title: "Insurance & Investment Advisor", company: "SecureLife Advisors", tagline: "Protect what matters most", phone: "+91 94440 71829", whatsapp: "+91 94440 71829", email: "suresh@securelife.in", website: "securelife.in", address: "T. Nagar, Chennai", services: ["Life", "Health", "Mutual funds"], socials: {}, extras: [{ label: "IRDAI Lic.", value: "1234567" }] },
};
