import type { EventItem, InviteData, Palette, Template } from "./types";
import { weddingSample } from "./samples";

/**
 * The Signature collection: premium, non-religious wedding designs, each with
 * bespoke art, its own intro, page turn and reveal, and (some) custom pages.
 */

const P = (p: Palette) => p;
const ev = (id: string, kind: EventItem["kind"], name: string, date: string, time: string, venue: string, address: string, extra: Partial<EventItem> = {}): EventItem => ({ id, kind, name, date, time, venue, address, ...extra });
const sample = (palette: string, over: Partial<InviteData>): InviteData => ({ ...weddingSample(palette), symbol: "none", mantra: "", tradition: "civil", joiner: "&", ...over });

export const SIGNATURE_TEMPLATES: Template[] = [
  {
    id: "stargazer",
    name: "Stargazer",
    category: "wedding",
    signature: true,
    tagline: "The real night sky over your venue, at the hour you say yes",
    paper: "matte",
    ornament: "none",
    backdrop: "slate",
    petals: "gold",
    fonts: { display: "var(--f-tenor)", script: "var(--f-great-vibes)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "midnight", label: "Midnight", paper: "#0b1026", paper2: "#1b2452", ink: "#f3ead6", inkSoft: "#a9b0d0", accent: "#7c6cf0", accent2: "#2bb3c0", foil: "gold", surface: "#03050d", surface2: "#0e1430", envelope: "#f2ead8", envelope2: "#0b1026", wax: "#c9a24a" }),
      P({ id: "aurora", label: "Aurora", paper: "#061a1d", paper2: "#0d3438", ink: "#eef6f1", inkSoft: "#9cc4bd", accent: "#3be8b0", accent2: "#7b5cff", foil: "silver", surface: "#020a0b", surface2: "#0a2a2d", envelope: "#eef2ee", envelope2: "#061a1d", wax: "#3be8b0" }),
      P({ id: "dusk", label: "Desert Dusk", paper: "#24102c", paper2: "#43204f", ink: "#fbe9dd", inkSoft: "#d3aebf", accent: "#ff7aa8", accent2: "#ffb86b", foil: "rosegold", surface: "#0e0611", surface2: "#2e1438", envelope: "#f6e6dc", envelope2: "#24102c", wax: "#ff7aa8" }),
      P({ id: "chart", label: "Ivory Chart", paper: "#f5f0e4", paper2: "#e8dfcb", ink: "#1b2340", inkSoft: "#6a6f86", accent: "#c9a24a", accent2: "#8aa0c8", foil: "gold", surface: "#d9d2c3", surface2: "#bfb6a3", envelope: "#f5f0e4", envelope2: "#1b2340", wax: "#1b2340" }),
    ],
    styles: ["Signature", "Celestial", "Modern"],
    effects: ["Real star map", "Moon phase", "Warp intro", "Orbit turn"],
    wed: { design: "stargazer", intro: "warp", turn: "orbit", reveal: "twinkle" },
    sample: sample("midnight", {
      eyebrow: "Written in the stars",
      blessingLine: "Under the same sky that brought us together",
      hosts: "The Bhatia & Kapadia Families",
      hostSide: "both",
      inviteText: "invite you to a night under the stars for the wedding of",
      primary: { name: "Aarav", subtitle: "Son of Mr. Nikhil & Mrs. Ruchi Bhatia" },
      secondary: { name: "Diya", subtitle: "Daughter of Mr. Paresh & Mrs. Sejal Kapadia" },
      quote: "Of all the stars in the sky, we found each other.",
      effects: { petals: false },
      mainDateTime: "2026-12-12T21:30",
      mainEventId: "sg3",
      events: [
        ev("sg1", "mehendi", "Mehendi on the Dunes", "2026-12-11", "15:00", "Suryagarh", "Kahala Phata, Jaisalmer", { dressCode: "Desert pastels" }),
        ev("sg2", "sangeet", "Sangeet by the Fire", "2026-12-11", "20:00", "Suryagarh Desert Camp", "Sam Sand Dunes, Jaisalmer", { dressCode: "Starry night sparkle" }),
        ev("sg3", "wedding", "Vows Under the Stars", "2026-12-12", "21:30", "Suryagarh", "Kahala Phata, Jaisalmer", { note: "The sky on this card is the sky you'll see that night" }),
        ev("sg4", "other", "Sunrise Breakfast", "2026-12-13", "07:00", "Suryagarh", "Kahala Phata, Jaisalmer", { dressCode: "Cosy & comfy" }),
      ],
      family: { enabled: true, title: "With Love", names: ["Mrs. Kusum Bhatia", "Mr. Rohit & Mrs. Neha Bhatia", "Mr. Jatin & Mrs. Hetal Kapadia"], kidsTitle: "Little Stars", kids: ["Anaya", "Vivaan", "Kiaan"], kidsLine: "Come count stars with us at Chachu's wedding!" },
      rsvp: { enabled: true, deadline: "2026-11-20", contacts: [{ name: "Diya", phone: "+91 98250 44556" }, { name: "Aarav", phone: "+91 98110 77889" }] },
      closing: { title: "See You Under the Stars", names: ["Aarav & Diya", "The Bhatia & Kapadia Families"] },
      hashtag: "#AaravDiyaStarstruck",
      info: [
        { label: "Stay", value: "Rooms at Suryagarh for all outstation guests" },
        { label: "Weather", value: "Desert nights are cold: bring a shawl" },
        { label: "Travel", value: "Cars from Jaisalmer airport on 10 & 11 Dec" },
      ],
    }),
  },
  {
    id: "monsoon",
    name: "Monsoon",
    category: "wedding",
    signature: true,
    tagline: "Rain on the window, city lights, and a red umbrella built for two",
    paper: "matte",
    ornament: "none",
    backdrop: "concrete",
    petals: "rose",
    fonts: { display: "var(--f-montserrat)", script: "var(--f-parisienne)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "dusk", label: "Dusk Blue", paper: "#16243a", paper2: "#0b1424", ink: "#f4efe6", inkSoft: "#b9c4d6", accent: "#d7263d", accent2: "#3fb6c9", foil: "silver", surface: "#05080e", surface2: "#14202f", envelope: "#ecf0f4", envelope2: "#16243a", wax: "#ff9e5e" }),
      P({ id: "plum", label: "Plum Evening", paper: "#26192f", paper2: "#140c1b", ink: "#f6eef4", inkSoft: "#c9b6cc", accent: "#ffb703", accent2: "#c77dff", foil: "gold", surface: "#08040b", surface2: "#1d1224", envelope: "#f3ecf3", envelope2: "#26192f", wax: "#ff6b9a" }),
      P({ id: "slate", label: "Grey Rain", paper: "#262b31", paper2: "#14171b", ink: "#f1f3f5", inkSoft: "#adb5bd", accent: "#e63946", accent2: "#8ecae6", foil: "silver", surface: "#07080a", surface2: "#1b1f24", envelope: "#eef0f2", envelope2: "#262b31", wax: "#ffd166" }),
    ],
    styles: ["Signature", "Romantic", "Cinematic"],
    effects: ["Live rain", "Windshield wiper", "Bokeh lights", "Pour turn"],
    wed: { design: "monsoon", intro: "wiper", turn: "pour", reveal: "drip" },
    sample: sample("dusk", {
      eyebrow: "Some love stories begin in the rain",
      blessingLine: "With love, and a little bit of rain",
      hosts: "The Rao & Fernandes Families",
      hostSide: "both",
      inviteText: "invite you to celebrate the wedding of",
      primary: { name: "Ishaan", subtitle: "Son of Mr. Kiran & Mrs. Sunita Rao" },
      secondary: { name: "Mira", subtitle: "Daughter of Mr. Allan & Mrs. Jennifer Fernandes" },
      quote: "We met under one umbrella. We're staying under it forever.",
      effects: { petals: false },
      mainDateTime: "2027-07-17T19:00",
      mainEventId: "mn3",
      events: [
        ev("mn1", "haldi", "Haldi & Chai", "2027-07-16", "11:00", "The Verandah", "Bandra West, Mumbai", { dressCode: "Yellow & rainproof" }),
        ev("mn2", "sangeet", "Sangeet Night", "2027-07-16", "20:00", "The Bombay Canteen Terrace", "Lower Parel, Mumbai", { dressCode: "Monsoon glam" }),
        ev("mn3", "wedding", "The Wedding", "2027-07-17", "19:00", "The Sea Lounge", "Colaba, Mumbai", { note: "Umbrellas on us" }),
      ],
      family: { enabled: true, title: "With Love", names: ["Mrs. Kamala Rao", "Mr. Vinay & Mrs. Priya Rao", "Mr. Joseph & Mrs. Linda Fernandes"], kidsTitle: "Puddle Jumpers", kids: ["Aadi", "Zoe", "Reyan"], kidsLine: "Bring your gumboots to our Mama's wedding!" },
      rsvp: { enabled: true, deadline: "2027-07-01", contacts: [{ name: "Mira", phone: "+91 98200 13579" }, { name: "Ishaan", phone: "+91 98670 24680" }] },
      closing: { title: "Come Rain or Shine", names: ["Ishaan & Mira", "The Rao & Fernandes Families"] },
      hashtag: "#IshaanMiraMonsoon",
      info: [
        { label: "Weather", value: "It's July in Mumbai: expect rain and romance" },
        { label: "Parking", value: "Valet at all venues" },
      ],
    }),
  },
  {
    id: "premiere",
    name: "Premiere",
    category: "wedding",
    signature: true,
    tagline: "Your wedding as a film premiere: poster, showtimes and credits",
    paper: "matte",
    ornament: "none",
    backdrop: "velvet",
    petals: "gold",
    fonts: { display: "var(--f-bebas)", script: "var(--f-bebas)", body: "var(--f-archivo)" },
    palettes: [
      P({ id: "noir", label: "Noir", paper: "#0d0d10", paper2: "#1b1b21", ink: "#f2efe8", inkSoft: "#a5a2a0", accent: "#c1121f", accent2: "#f4c95d", foil: "gold", surface: "#000000", surface2: "#1a0508", envelope: "#efe9df", envelope2: "#0d0d10", wax: "#c1121f" }),
      P({ id: "technicolor", label: "Technicolor", paper: "#0f2a33", paper2: "#0a1d24", ink: "#fff6e5", inkSoft: "#a9c3c6", accent: "#ff7b00", accent2: "#ffd166", foil: "gold", surface: "#031014", surface2: "#0f2a33", envelope: "#fff6e5", envelope2: "#0f2a33", wax: "#ff7b00" }),
      P({ id: "velvet", label: "Red Carpet", paper: "#3a0a12", paper2: "#26060c", ink: "#fbeee0", inkSoft: "#d8a9a5", accent: "#b8860b", accent2: "#f4c95d", foil: "gold", surface: "#120205", surface2: "#3a0a12", envelope: "#f6e9d8", envelope2: "#3a0a12", wax: "#b8860b" }),
      P({ id: "silver", label: "Silver Screen", paper: "#ece8df", paper2: "#ddd7ca", ink: "#141414", inkSoft: "#5c5a55", accent: "#b71c1c", accent2: "#8a6d1d", foil: "silver", surface: "#2b2b2b", surface2: "#444", envelope: "#ece8df", envelope2: "#141414", wax: "#b71c1c" }),
    ],
    styles: ["Signature", "Cinematic", "Fun"],
    effects: ["Countdown leader", "Movie poster", "Showtimes", "Credits roll", "Reel turn"],
    wed: { design: "premiere", intro: "leader", turn: "reel", reveal: "credits" },
    sample: sample("noir", {
      eyebrow: "A Love Story",
      blessingLine: "With the blessings of our families and a script written in the stars",
      hosts: "The Malhotra & Sen Families",
      hostSide: "both",
      inviteText: "invite you to the world premiere of the wedding of",
      primary: { name: "Yash", subtitle: "Son of Mr. Rakesh & Mrs. Nisha Malhotra" },
      secondary: { name: "Anika", subtitle: "Daughter of Mr. Arindam & Mrs. Paromita Sen" },
      quote: "Two leads. One love story. No intermission.",
      mainDateTime: "2027-02-20T19:30",
      mainEventId: "pm3",
      events: [
        ev("pm1", "mehendi", "Mehendi Matinee", "2027-02-19", "14:00", "Juhu Beach House", "Juhu Tara Road, Mumbai", { dressCode: "Florals" }),
        ev("pm2", "sangeet", "Sangeet: The Musical", "2027-02-19", "20:00", "Royal Opera House", "Girgaon, Mumbai", { dressCode: "Red carpet" }),
        ev("pm3", "wedding", "The Wedding Premiere", "2027-02-20", "19:30", "Royal Opera House", "Girgaon, Mumbai", { note: "Doors open at 7:00 PM" }),
        ev("pm4", "cocktail", "After-party Screening", "2027-02-20", "23:00", "The Opera House Lounge", "Girgaon, Mumbai", { dressCode: "Dance-ready" }),
      ],
      family: { enabled: true, title: "Supporting Cast", names: ["Mrs. Asha Malhotra · Dadi", "Mr. Sunil & Mrs. Rina Malhotra", "Mr. Debu & Mrs. Mou Sen"], kidsTitle: "Introducing", kids: ["Aryan", "Pihu", "Rohan"], kidsLine: "Popcorn's on us at Chachu's premiere!" },
      rsvp: { enabled: true, deadline: "2027-02-05", contacts: [{ name: "Yash", phone: "+91 98201 11223" }, { name: "Anika", phone: "+91 98300 44556" }] },
      closing: { title: "Produced With Love By", names: ["The Malhotra & Sen Families", "Friends & Well-wishers"] },
      hashtag: "#YashAnikaThePremiere",
      info: [
        { label: "Dress code", value: "Red carpet glamour, every night" },
        { label: "Stay", value: "Rooms at Trident Nariman Point for outstation guests" },
      ],
    }),
  },
  {
    id: "cover-story",
    name: "Cover Story",
    category: "wedding",
    signature: true,
    tagline: "A luxury magazine's wedding issue, with you on the cover",
    paper: "pearl",
    ornament: "none",
    backdrop: "studio",
    petals: "rose",
    photo: true,
    fonts: { display: "var(--f-bodoni)", script: "var(--f-bodoni)", body: "var(--f-montserrat)" },
    palettes: [
      P({ id: "rouge", label: "Rouge", paper: "#f4efe8", paper2: "#e9e0d4", ink: "#141210", inkSoft: "#6b625a", accent: "#c8102e", accent2: "#f2c6b4", foil: "gold", surface: "#d8d2c9", surface2: "#bdb5aa", envelope: "#f4efe8", envelope2: "#c8102e", wax: "#c8102e" }),
      P({ id: "noir", label: "Noir", paper: "#121212", paper2: "#1d1d1d", ink: "#f5f1ea", inkSoft: "#a9a39a", accent: "#d4af37", accent2: "#3b3b3b", foil: "gold", surface: "#000", surface2: "#222", envelope: "#f5f1ea", envelope2: "#121212", wax: "#d4af37" }),
      P({ id: "blush", label: "Blush", paper: "#f7e4e1", paper2: "#efd0cc", ink: "#3e1019", inkSoft: "#8a5a62", accent: "#8e1b3a", accent2: "#f6b8bd", foil: "rosegold", surface: "#e9d3cf", surface2: "#d3b8b3", envelope: "#f7e4e1", envelope2: "#8e1b3a", wax: "#8e1b3a" }),
      P({ id: "cobalt", label: "Cobalt", paper: "#eef1f8", paper2: "#dfe5f1", ink: "#0d1b3d", inkSoft: "#56658a", accent: "#1d3fbb", accent2: "#f2b134", foil: "gold", surface: "#d6dbe6", surface2: "#b9c0d0", envelope: "#eef1f8", envelope2: "#1d3fbb", wax: "#1d3fbb" }),
    ],
    styles: ["Signature", "Editorial", "Luxury"],
    effects: ["Magazine cover", "Paparazzi flashes", "Contents page", "Peel turn", "Photo"],
    wed: { design: "coverstory", intro: "paparazzi", turn: "peel", reveal: "unveil" },
    sample: sample("rouge", {
      eyebrow: "The Wedding Issue",
      blessingLine: "With the blessings of their families",
      hosts: "The Khanna & Mehra families",
      hostSide: "both",
      inviteText: "invite you to celebrate the wedding of",
      primary: { name: "Dev", subtitle: "Son of Mr. Ashok & Mrs. Simran Khanna" },
      secondary: { name: "Alia", subtitle: "Daughter of Mr. Vikram & Mrs. Tanya Mehra" },
      quote: "We didn't fall in love. We walked into it, together.",
      mainDateTime: "2026-11-28T19:00",
      mainEventId: "cs4",
      events: [
        ev("cs1", "cocktail", "Cocktails & Couture", "2026-11-26", "20:00", "The Leela Palace", "Chanakyapuri, New Delhi", { dressCode: "Black tie" }),
        ev("cs2", "mehendi", "Mehendi Brunch", "2026-11-27", "12:00", "The Lodhi Lawns", "Lodhi Road, New Delhi", { dressCode: "Botanical prints" }),
        ev("cs3", "sangeet", "Sangeet Soirée", "2026-11-27", "20:00", "The Lodhi Lawns", "Lodhi Road, New Delhi", { dressCode: "Sequins & shine" }),
        ev("cs4", "wedding", "The Wedding", "2026-11-28", "19:00", "The Oberoi Lawns", "Dr. Zakir Hussain Marg, New Delhi", { note: "Pheras at 9:15 PM" }),
        ev("cs5", "reception", "Reception", "2026-11-29", "20:00", "The Oberoi Ballroom", "Dr. Zakir Hussain Marg, New Delhi", { dressCode: "Evening formal" }),
      ],
      family: { enabled: true, title: "Contributors", names: ["Mrs. Kamini Khanna", "Mr. Rajiv & Mrs. Anjali Khanna", "Mr. Sameer & Mrs. Pooja Mehra", "Mr. Kabir & Mrs. Nisha Oberoi"], kidsTitle: "Junior Editors", kids: ["Advik", "Inaya", "Aarush"], kidsLine: "Front row seats at Chachu's wedding, please!" },
      rsvp: { enabled: true, deadline: "2026-11-10", contacts: [{ name: "Alia", phone: "+91 98100 11122" }, { name: "Dev", phone: "+91 98110 33344" }] },
      closing: { title: "With Love From", names: ["The Khanna & Mehra Families"] },
      hashtag: "#DevAliaCoverStory",
      info: [
        { label: "Stay", value: "Rooms at The Oberoi, New Delhi" },
        { label: "Gifts", value: "Your presence is the only present" },
      ],
    }),
  },
  {
    id: "glasshouse",
    name: "Glasshouse",
    category: "wedding",
    signature: true,
    tagline: "A Victorian conservatory: wipe the misted glass to see inside",
    paper: "linen",
    ornament: "none",
    backdrop: "linen",
    petals: "jasmine",
    fonts: { display: "var(--f-cinzel)", script: "var(--f-pinyon)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "verdant", label: "Verdant", paper: "#10221a", paper2: "#183527", ink: "#f4efe2", inkSoft: "#b7c9b9", accent: "#c9a24a", accent2: "#7fb08a", foil: "gold", surface: "#06110c", surface2: "#14291f", envelope: "#f1ede2", envelope2: "#10221a", wax: "#c9a24a" }),
      P({ id: "morning", label: "Morning Light", paper: "#eef2ea", paper2: "#dfe7d9", ink: "#24372b", inkSoft: "#6f8572", accent: "#b48a3c", accent2: "#9cc39a", foil: "gold", surface: "#d7ddd2", surface2: "#bcc5b5", envelope: "#f4f6f1", envelope2: "#5e8a57", wax: "#5e8a57" }),
      P({ id: "terracotta", label: "Terracotta Dusk", paper: "#2a1c16", paper2: "#3b281f", ink: "#f6e9dc", inkSoft: "#c9ad98", accent: "#d08c60", accent2: "#e3a76f", foil: "copper", surface: "#120b08", surface2: "#2a1c16", envelope: "#f3e6d9", envelope2: "#2a1c16", wax: "#d08c60" }),
    ],
    styles: ["Signature", "Botanical", "Luxury"],
    effects: ["Wipe the glass", "Misted intro", "Tilt parallax", "Frost turn"],
    wed: { design: "glasshouse", intro: "mist", turn: "frost", reveal: "condense" },
    sample: sample("verdant", {
      eyebrow: "Together with their families",
      blessingLine: "With love from both our families",
      hosts: "The Nair & Banerjee Families",
      hostSide: "both",
      inviteText: "invite you into the glasshouse to celebrate the wedding of",
      primary: { name: "Neel", subtitle: "Son of Mr. Suresh & Mrs. Latha Nair" },
      secondary: { name: "Ira", subtitle: "Daughter of Mr. Abhijit & Mrs. Rumki Banerjee" },
      quote: "Love grows best in little houses, with fewer walls to separate.",
      effects: { petals: true },
      mainDateTime: "2027-01-23T17:30",
      mainEventId: "gh3",
      events: [
        ev("gh1", "mehendi", "Mehendi in the Orangery", "2027-01-22", "12:00", "The Orangery, Lalbagh", "Lalbagh Botanical Garden, Bengaluru", { dressCode: "Garden whites" }),
        ev("gh2", "sangeet", "Sangeet Among the Palms", "2027-01-22", "19:30", "The Palm House", "Lalbagh Botanical Garden, Bengaluru", { dressCode: "Jewel tones" }),
        ev("gh3", "wedding", "The Glasshouse Wedding", "2027-01-23", "17:30", "The Glass House, Lalbagh", "Lalbagh Botanical Garden, Bengaluru", { note: "Golden-hour vows · dinner to follow" }),
      ],
      family: { enabled: true, title: "With Love", names: ["Mrs. Saraswathi Nair", "Mr. Mohan & Mrs. Deepa Nair", "Mr. Sourav & Mrs. Rimi Banerjee"], kidsTitle: "Little Sprouts", kids: ["Ved", "Tara", "Rishaan"], kidsLine: "Come find the butterflies at Mama's wedding!" },
      rsvp: { enabled: true, deadline: "2027-01-05", contacts: [{ name: "Ira", phone: "+91 98450 55667" }, { name: "Neel", phone: "+91 98860 88990" }] },
      closing: { title: "With Love From", names: ["Neel & Ira", "The Nair & Banerjee Families"] },
      hashtag: "#NeelIraInBloom",
      info: [
        { label: "Stay", value: "Rooms at The Oberoi, MG Road" },
        { label: "Note", value: "The garden is plastic-free: refill stations everywhere" },
      ],
    }),
  },
  {
    id: "snow-globe",
    name: "Snow Globe",
    category: "wedding",
    signature: true,
    tagline: "A tiny alpine chalet in a glass dome. Tap it and the snow swirls",
    paper: "matte",
    ornament: "none",
    backdrop: "wood",
    petals: "jasmine",
    fonts: { display: "var(--f-josefin)", script: "var(--f-great-vibes)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "alpine", label: "Alpine Night", paper: "#0f1d33", paper2: "#22406b", ink: "#f3f6fb", inkSoft: "#b7c6dc", accent: "#c8102e", accent2: "#8ec5ff", foil: "silver", surface: "#050b14", surface2: "#14243d", envelope: "#eef3f8", envelope2: "#0f1d33", wax: "#ffcf6b" }),
      P({ id: "frost", label: "Frost", paper: "#e9f1f7", paper2: "#9fbcd6", ink: "#1d3557", inkSoft: "#5f7a99", accent: "#c8102e", accent2: "#7fb3e0", foil: "silver", surface: "#cdd9e3", surface2: "#a9bccb", envelope: "#f4f8fb", envelope2: "#1d3557", wax: "#ffc14d" }),
      P({ id: "cranberry", label: "Cranberry", paper: "#3a0d18", paper2: "#5c2a3e", ink: "#fbefe8", inkSoft: "#e3b9bf", accent: "#f2c14e", accent2: "#e8a0a8", foil: "gold", surface: "#150307", surface2: "#3a0d18", envelope: "#f6e8e2", envelope2: "#3a0d18", wax: "#ffcf6b" }),
    ],
    styles: ["Signature", "Winter", "Whimsical"],
    effects: ["Live snow", "Shake to swirl", "Snow globe intro", "Drift turn"],
    wed: { design: "snowglobe", intro: "shake", turn: "drift", reveal: "flurry" },
    sample: sample("alpine", {
      eyebrow: "A winter wonderland wedding",
      blessingLine: "With warm hearts on a snowy day",
      hosts: "The Kaul & Ahuja Families",
      hostSide: "both",
      inviteText: "invite you to the mountains to celebrate the wedding of",
      primary: { name: "Arnav", subtitle: "Son of Mr. Sanjay & Mrs. Rashmi Kaul" },
      secondary: { name: "Mehr", subtitle: "Daughter of Mr. Gaurav & Mrs. Shalini Ahuja" },
      quote: "Cold hands, warm hearts, forever.",
      effects: { petals: false },
      mainDateTime: "2027-01-09T18:00",
      mainEventId: "sn3",
      events: [
        ev("sn1", "mehendi", "Mehendi by the Fireplace", "2027-01-08", "13:00", "The Khyber Lodge", "Gulmarg, Kashmir", { dressCode: "Cosy knits & pastels" }),
        ev("sn2", "sangeet", "Sangeet in the Snow", "2027-01-08", "19:30", "The Khyber Himalayan Resort", "Gulmarg, Kashmir", { dressCode: "Velvet & warm layers" }),
        ev("sn3", "wedding", "The Wedding", "2027-01-09", "18:00", "The Khyber Himalayan Resort", "Gulmarg, Kashmir", { note: "Kahwa and blankets at every seat" }),
        ev("sn4", "other", "Farewell Brunch", "2027-01-10", "11:00", "The Khyber Lodge", "Gulmarg, Kashmir"),
      ],
      family: { enabled: true, title: "With Love", names: ["Mrs. Raj Dulari Kaul", "Mr. Vinod & Mrs. Meena Kaul", "Mr. Rakesh & Mrs. Pooja Ahuja"], kidsTitle: "Snow Angels", kids: ["Ahaan", "Navya", "Reyansh"], kidsLine: "Snowball fight at Chachu's wedding!" },
      rsvp: { enabled: true, deadline: "2026-12-15", contacts: [{ name: "Mehr", phone: "+91 98110 22446" }, { name: "Arnav", phone: "+91 98189 66880" }] },
      closing: { title: "Warmly, From", names: ["Arnav & Mehr", "The Kaul & Ahuja Families"] },
      hashtag: "#ArnavMehrLetItSnow",
      info: [
        { label: "Weather", value: "Around −5°C at night: pack your warmest" },
        { label: "Travel", value: "Cars from Srinagar airport on 7 & 8 Jan" },
        { label: "Stay", value: "Rooms at The Khyber for all guests" },
      ],
    }),
  },
  {
    id: "kintsugi",
    name: "Kintsugi",
    category: "wedding",
    signature: true,
    tagline: "Dark ceramic mended with rivers of gold: broken, mended, more beautiful",
    paper: "matte",
    ornament: "none",
    backdrop: "slate",
    petals: "gold",
    fonts: { display: "var(--f-cormorant)", script: "var(--f-italiana)", body: "var(--f-tenor)" },
    palettes: [
      P({ id: "sumi", label: "Sumi Black", paper: "#151515", paper2: "#222", ink: "#f3ede2", inkSoft: "#a59e92", accent: "#b33a2b", accent2: "#3a3a3a", foil: "gold", surface: "#050505", surface2: "#1b1b1b", envelope: "#efe9dd", envelope2: "#151515", wax: "#b33a2b" }),
      P({ id: "indigo", label: "Indigo Raku", paper: "#16223f", paper2: "#22305a", ink: "#f1ead8", inkSoft: "#a8afc6", accent: "#c0392b", accent2: "#2c3c6a", foil: "gold", surface: "#070b16", surface2: "#16223f", envelope: "#efe9dd", envelope2: "#16223f", wax: "#c0392b" }),
      P({ id: "porcelain", label: "Porcelain", paper: "#f2eee6", paper2: "#e4ddd0", ink: "#2a2622", inkSoft: "#7d756b", accent: "#b33a2b", accent2: "#d6cfc2", foil: "gold", surface: "#cfc8bb", surface2: "#b3ab9c", envelope: "#f6f3ec", envelope2: "#2a2622", wax: "#b33a2b" }),
      P({ id: "celadon", label: "Celadon", paper: "#b7cbbd", paper2: "#a3baa9", ink: "#1f2d25", inkSoft: "#4d6155", accent: "#9e2a2b", accent2: "#c9d8cd", foil: "gold", surface: "#8fa596", surface2: "#748c7c", envelope: "#e8efe9", envelope2: "#1f2d25", wax: "#9e2a2b" }),
    ],
    styles: ["Signature", "Minimal", "Luxury"],
    effects: ["Gold seams", "Shards assemble", "Crack turn", "Hanko seal"],
    wed: { design: "kintsugi", intro: "mend", turn: "crack", reveal: "gild" },
    sample: sample("sumi", {
      eyebrow: "Broken, mended, more beautiful",
      blessingLine: "With the blessings of our families",
      hosts: "The Sehgal & Iyer Families",
      hostSide: "both",
      inviteText: "invite you to celebrate the joining of",
      primary: { name: "Kian", subtitle: "Son of Mr. Arun & Mrs. Payal Sehgal" },
      secondary: { name: "Avni", subtitle: "Daughter of Mr. Ramesh & Mrs. Lakshmi Iyer" },
      quote: "Every crack is where the gold goes in.",
      mainDateTime: "2027-02-13T18:30",
      mainEventId: "kt3",
      events: [
        ev("kt1", "mehendi", "Mehendi & Tea", "2027-02-12", "13:00", "The Courtyard", "Sector 28, Gurugram", { dressCode: "Ivory & sage" }),
        ev("kt2", "sangeet", "Sangeet", "2027-02-12", "20:00", "The Leela Ambience", "Gurugram", { dressCode: "Black & gold" }),
        ev("kt3", "wedding", "The Wedding", "2027-02-13", "18:30", "The Leela Ambience Lawns", "Gurugram", { note: "Pheras at 8:40 PM · dinner to follow" }),
      ],
      family: { enabled: true, title: "With Gratitude", names: ["Mrs. Kamla Sehgal", "Mr. Vikas & Mrs. Ritu Sehgal", "Mr. Mahesh & Mrs. Uma Iyer"], kidsTitle: "Little Ones", kids: ["Aarya", "Shiv", "Meera"], kidsLine: "We'll be the loudest at Chachu's wedding!" },
      rsvp: { enabled: true, deadline: "2027-01-25", contacts: [{ name: "Avni", phone: "+91 98111 23456" }, { name: "Kian", phone: "+91 98999 65432" }] },
      closing: { title: "With Love From", names: ["Kian & Avni", "The Sehgal & Iyer Families"] },
      hashtag: "#KianAvniGoldenSeams",
      info: [
        { label: "Stay", value: "Rooms at The Leela Ambience for outstation guests" },
        { label: "Gifts", value: "Your blessings are gold enough" },
      ],
    }),
  },
  {
    id: "origami",
    name: "Origami",
    category: "wedding",
    signature: true,
    tagline: "Folded paper and a thousand cranes for a long, happy life",
    paper: "handmade",
    ornament: "none",
    backdrop: "paper",
    petals: "rose",
    fonts: { display: "var(--f-shippori)", script: "var(--f-shippori)", body: "var(--f-jost)" },
    palettes: [
      P({ id: "washi", label: "Washi", paper: "#f6f1e7", paper2: "#ece3d2", ink: "#2d2a26", inkSoft: "#7a7268", accent: "#e76f51", accent2: "#2a9d8f", foil: "gold", surface: "#e2dacb", surface2: "#c9bfad", envelope: "#f8f4ec", envelope2: "#e76f51", wax: "#e9c46a" }),
      P({ id: "indigo", label: "Indigo", paper: "#1b2a4a", paper2: "#24365c", ink: "#f4efe6", inkSoft: "#aab5cc", accent: "#f4f1ea", accent2: "#e9b44c", foil: "gold", surface: "#0b1222", surface2: "#1b2a4a", envelope: "#f4efe6", envelope2: "#1b2a4a", wax: "#7fb7e6" }),
      P({ id: "blush", label: "Blush", paper: "#f8ece8", paper2: "#f0dcd6", ink: "#4a2b33", inkSoft: "#8f6b72", accent: "#c9476a", accent2: "#7a3b69", foil: "rosegold", surface: "#ead8d2", surface2: "#d4bdb6", envelope: "#faf1ee", envelope2: "#c9476a", wax: "#e9a36b" }),
      P({ id: "mint", label: "Mint", paper: "#eef6f1", paper2: "#dbece2", ink: "#23392f", inkSoft: "#6b8a7b", accent: "#3a8f6e", accent2: "#f28e5c", foil: "gold", surface: "#d9e6de", surface2: "#bccfc3", envelope: "#f3f9f5", envelope2: "#3a8f6e", wax: "#f2c14e" }),
    ],
    styles: ["Signature", "Modern", "Playful"],
    effects: ["Paper cranes", "Flock intro", "Paper-plane turn", "Fold reveal"],
    wed: { design: "origami", intro: "flock", turn: "plane", reveal: "unfold" },
    sample: sample("washi", {
      eyebrow: "A thousand cranes, one wish",
      blessingLine: "With the blessings of our families",
      hosts: "The Reddy & Shetty Families",
      hostSide: "both",
      inviteText: "invite you to celebrate the wedding of",
      primary: { name: "Aryan", subtitle: "Son of Mr. Srinivas & Mrs. Padma Reddy" },
      secondary: { name: "Riya", subtitle: "Daughter of Mr. Prakash & Mrs. Nalini Shetty" },
      quote: "Fold by fold, we made something beautiful.",
      mainDateTime: "2027-03-06T18:00",
      mainEventId: "or3",
      events: [
        ev("or1", "haldi", "Haldi in the Garden", "2027-03-05", "10:30", "The Tamarind Tree", "Kanakapura Road, Bengaluru", { dressCode: "Sunshine yellow" }),
        ev("or2", "sangeet", "Sangeet", "2027-03-05", "19:30", "The Tamarind Tree", "Kanakapura Road, Bengaluru", { dressCode: "Bright & paper-light" }),
        ev("or3", "wedding", "The Wedding", "2027-03-06", "18:00", "Taj West End Gardens", "Race Course Road, Bengaluru", { note: "Fold a crane for us at the welcome table" }),
      ],
      family: { enabled: true, title: "With Love", names: ["Mrs. Saroja Reddy", "Mr. Venkat & Mrs. Latha Reddy", "Mr. Suresh & Mrs. Asha Shetty"], kidsTitle: "Little Folders", kids: ["Ishaan", "Diya", "Kabir"], kidsLine: "Come fold paper cranes with us at Mama's wedding!" },
      rsvp: { enabled: true, deadline: "2027-02-15", contacts: [{ name: "Riya", phone: "+91 98450 13579" }, { name: "Aryan", phone: "+91 99000 24680" }] },
      closing: { title: "With Love From", names: ["Aryan & Riya", "The Reddy & Shetty Families"] },
      hashtag: "#AryanRiyaFoldedTogether",
      info: [
        { label: "A wish", value: "We're folding 1,000 cranes before the big day: bring yours" },
        { label: "Stay", value: "Rooms at Taj West End for outstation guests" },
      ],
    }),
  },
  {
    id: "wanderlust",
    name: "Wanderlust",
    category: "wedding",
    signature: true,
    tagline: "An illustrated map of two journeys that meet at your wedding",
    paper: "handmade",
    ornament: "none",
    backdrop: "wood",
    petals: "marigold",
    fonts: { display: "var(--f-playfair)", script: "var(--f-great-vibes)", body: "var(--f-garamond)" },
    palettes: [
      P({ id: "atlas", label: "Atlas", paper: "#f4ecdc", paper2: "#ead9b3", ink: "#3b2f22", inkSoft: "#7a6a55", accent: "#c0392b", accent2: "#a9cfd4", foil: "gold", surface: "#3a2a1c", surface2: "#5a432e", envelope: "#f4ecdc", envelope2: "#c0392b", wax: "#c0392b" }),
      P({ id: "nautical", label: "Nautical", paper: "#10243e", paper2: "#e9dcc0", ink: "#f1e6cf", inkSoft: "#b7c2d0", accent: "#e4572e", accent2: "#2d5a7b", foil: "gold", surface: "#060f1c", surface2: "#10243e", envelope: "#f1e6cf", envelope2: "#10243e", wax: "#e4572e" }),
      P({ id: "pastel", label: "Pastel", paper: "#fbf4ef", paper2: "#f6d8c9", ink: "#4b3b47", inkSoft: "#8e7a86", accent: "#e5677a", accent2: "#bfe3dc", foil: "rosegold", surface: "#ecdcd3", surface2: "#d6c1b5", envelope: "#fbf4ef", envelope2: "#e5677a", wax: "#e5677a" }),
    ],
    styles: ["Signature", "Travel", "Illustrated"],
    effects: ["Illustrated map", "Folded map intro", "Pan turn", "Compass rose"],
    wed: { design: "wanderlust", intro: "unfoldmap", turn: "pan", reveal: "pin" },
    sample: sample("atlas", {
      eyebrow: "The journey of",
      blessingLine: "Two roads, one destination",
      hosts: "The Chopra & Pillai Families",
      hostSide: "both",
      inviteText: "invite you to the end of one journey and the start of another: the wedding of",
      primary: { name: "Samar", subtitle: "Son of Mr. Rajan & Mrs. Neeru Chopra" },
      secondary: { name: "Rhea", subtitle: "Daughter of Mr. Mohan & Mrs. Anitha Pillai" },
      quote: "Of all the places we've been, you are my favourite.",
      mainDateTime: "2027-11-13T17:00",
      mainEventId: "wl3",
      events: [
        ev("wl1", "cocktail", "Welcome Dinner on the Houseboat", "2027-11-12", "19:30", "Spice Coast Cruises", "Punnamada, Alleppey", { dressCode: "Linen & florals" }),
        ev("wl2", "haldi", "Haldi by the Backwaters", "2027-11-13", "10:00", "Kumarakom Lake Resort", "Kumarakom, Kerala", { dressCode: "Yellow & white" }),
        ev("wl3", "wedding", "The Wedding", "2027-11-13", "17:00", "Kumarakom Lake Resort Lawns", "Kumarakom, Kerala", { note: "Sunset vows by the lake" }),
        ev("wl4", "other", "Farewell Brunch", "2027-11-14", "10:30", "Kumarakom Lake Resort", "Kumarakom, Kerala"),
      ],
      family: { enabled: true, title: "Fellow Travellers", names: ["Mrs. Santosh Chopra", "Mr. Vivek & Mrs. Shruti Chopra", "Mr. Ajith & Mrs. Divya Pillai"], kidsTitle: "Little Explorers", kids: ["Kabir", "Ananya", "Dev"], kidsLine: "Come on an adventure to Chachu's wedding!" },
      rsvp: { enabled: true, deadline: "2027-10-20", contacts: [{ name: "Rhea", phone: "+91 98450 77665" }, { name: "Samar", phone: "+91 98100 55443" }] },
      closing: { title: "See You There", names: ["Samar & Rhea", "The Chopra & Pillai Families"] },
      hashtag: "#SamarRheaJourney",
      info: [
        { label: "Travel", value: "Fly into Kochi (COK); cars to Kumarakom on the 12th" },
        { label: "Stay", value: "Lake-view cottages at Kumarakom Lake Resort" },
      ],
    }),
  },
  {
    id: "firefly",
    name: "Firefly",
    category: "wedding",
    signature: true,
    tagline: "A layered papercut forest at night, alive with fireflies",
    paper: "matte",
    ornament: "none",
    backdrop: "felt",
    petals: "gold",
    fonts: { display: "var(--f-cormorant)", script: "var(--f-pinyon)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "teal", label: "Midnight Teal", paper: "#05161b", paper2: "#1f5f6b", ink: "#f4f0e2", inkSoft: "#b9d3cf", accent: "#ffd76a", accent2: "#fdf3c8", foil: "gold", surface: "#020809", surface2: "#0a2a30", envelope: "#f1ede0", envelope2: "#05161b", wax: "#ffd76a" }),
      P({ id: "violet", label: "Twilight Violet", paper: "#100820", paper2: "#5a3f8c", ink: "#f6f0ff", inkSoft: "#cbbfe3", accent: "#ffe08a", accent2: "#fff2d8", foil: "gold", surface: "#05020b", surface2: "#1f1238", envelope: "#f3eefa", envelope2: "#100820", wax: "#ffe08a" }),
      P({ id: "dawn", label: "Dawn Rose", paper: "#2c1621", paper2: "#e7a993", ink: "#fff6f0", inkSoft: "#f6d6cb", accent: "#fff1a8", accent2: "#fff7ea", foil: "rosegold", surface: "#140a0f", surface2: "#2c1621", envelope: "#fbefea", envelope2: "#2c1621", wax: "#f6c37a" }),
      P({ id: "forest", label: "Deep Forest", paper: "#06120a", paper2: "#2f5d3a", ink: "#f2f5e8", inkSoft: "#bcd2b8", accent: "#f6e27a", accent2: "#f6f1d6", foil: "gold", surface: "#020603", surface2: "#0e2414", envelope: "#eef2e6", envelope2: "#06120a", wax: "#f6e27a" }),
    ],
    styles: ["Signature", "Romantic", "Illustrated"],
    effects: ["Live fireflies", "Papercut layers", "Tilt parallax", "Recede turn"],
    wed: { design: "firefly", intro: "fireflies", turn: "recede", reveal: "glowin" },
    sample: sample("teal", {
      eyebrow: "Under the moon, among the fireflies",
      blessingLine: "With the blessings of our families",
      hosts: "The Rathore & Menon Families",
      hostSide: "both",
      inviteText: "invite you into the forest to celebrate the wedding of",
      primary: { name: "Shaurya", subtitle: "Son of Mr. Vikram & Mrs. Anuradha Rathore" },
      secondary: { name: "Kavya", subtitle: "Daughter of Mr. Sunil & Mrs. Geetha Menon" },
      quote: "You light up my world, like fireflies on a summer night.",
      effects: { petals: false },
      mainDateTime: "2027-04-24T19:30",
      mainEventId: "ff3",
      events: [
        ev("ff1", "mehendi", "Mehendi in the Coffee Estate", "2027-04-23", "13:00", "Evolve Back", "Kabinakad Estate, Coorg", { dressCode: "Earthy & floral" }),
        ev("ff2", "sangeet", "Sangeet by the Bonfire", "2027-04-23", "20:00", "Evolve Back", "Kabinakad Estate, Coorg", { dressCode: "Lantern glow" }),
        ev("ff3", "wedding", "Moonlight Wedding", "2027-04-24", "19:30", "Evolve Back Forest Lawns", "Kabinakad Estate, Coorg", { note: "Lanterns light the path from 7:00 PM" }),
      ],
      family: { enabled: true, title: "With Love", names: ["Mrs. Shanta Rathore", "Mr. Ajay & Mrs. Sneha Rathore", "Mr. Ravi & Mrs. Priya Menon"], kidsTitle: "Firefly Catchers", kids: ["Advik", "Myra", "Ved"], kidsLine: "Come chase fireflies at Chachu's wedding!" },
      rsvp: { enabled: true, deadline: "2027-04-01", contacts: [{ name: "Kavya", phone: "+91 98450 31415" }, { name: "Shaurya", phone: "+91 98290 27182" }] },
      closing: { title: "With Love From", names: ["Shaurya & Kavya", "The Rathore & Menon Families"] },
      hashtag: "#ShauryaKavyaFireflies",
      info: [
        { label: "Stay", value: "Pool villas at Evolve Back for outstation guests" },
        { label: "Note", value: "Paths are lantern-lit and gravel: comfortable shoes!" },
      ],
    }),
  },
];
