import type { EventItem, InviteData, Palette, Template } from "./types";
import { weddingSample } from "./samples";

/** Wedding collection, batch 1: each design has its own art, intro, page turn and reveal. */

const P = (p: Palette) => p;

const ev = (id: string, kind: EventItem["kind"], name: string, date: string, time: string, venue: string, address: string, extra: Partial<EventItem> = {}): EventItem => ({ id, kind, name, date, time, venue, address, ...extra });

const sample = (palette: string, over: Partial<InviteData>): InviteData => ({ ...weddingSample(palette), ...over });

export const WEDDING_TEMPLATES: Template[] = [
  {
    id: "kovil",
    name: "Kovil",
    category: "wedding",
    tagline: "Kanjivaram zari border, temple gopuram & brass lamps",
    paper: "silk",
    ornament: "none",
    backdrop: "wood",
    petals: "jasmine",
    fonts: { display: "var(--f-yeseva)", script: "var(--f-great-vibes)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "maroon", label: "Maroon & Green", paper: "#6b0f1a", paper2: "#4a0811", ink: "#f7e7c4", inkSoft: "#e0c48e", accent: "#d4a017", accent2: "#0f5a3c", foil: "gold", surface: "#2a0a0c", surface2: "#4d1016", envelope: "#f2e4c4", envelope2: "#6b0f1a", wax: "#8d1320" }),
      P({ id: "peacock", label: "Peacock & Rani", paper: "#0d4f4a", paper2: "#073330", ink: "#f6e9c8", inkSoft: "#d9c391", accent: "#e14b7b", accent2: "#a81c4a", foil: "gold", surface: "#06211f", surface2: "#0f3f3b", envelope: "#f3e6cc", envelope2: "#0d4f4a", wax: "#9b1b45" }),
      P({ id: "kasavu", label: "Kasavu Ivory", paper: "#f7f0de", paper2: "#ece0c2", ink: "#4a2e12", inkSoft: "#7d5f3a", accent: "#b8860b", accent2: "#7a1c1c", foil: "gold", surface: "#3b2414", surface2: "#5a3a20", envelope: "#fbf6ea", envelope2: "#c9a24a", wax: "#8a5a12" }),
    ],
    styles: ["Traditional", "South Indian", "Luxury"],
    effects: ["Temple doors", "Palm-leaf flip", "Zari border", "Hot foil", "Petals"],
    wed: { design: "kovil", intro: "doors", turn: "lift", reveal: "glow" },
    sample: sample("maroon", {
      music: "tanpura",
      hosts: "Mr. S. Venkatesh & Mrs. Lakshmi Venkatesh",
      inviteText: "request the pleasure of your company at the wedding of their son",
      primary: { name: "Karthik", subtitle: "Son of Mr. S. Venkatesh & Mrs. Lakshmi Venkatesh" },
      secondary: { name: "Meenakshi", subtitle: "Daughter of Mr. R. Sundaram & Mrs. Kamala Sundaram" },
      quote: "Like the lamp and its flame, may we light each other's way.",
      mainDateTime: "2027-01-24T07:30",
      mainEventId: "k3",
      events: [
        ev("k1", "puja", "Vratham & Nalangu", "2027-01-23", "10:00", "Sundaram Residence", "12, Lake View Road, T. Nagar, Chennai", { audience: "family" }),
        ev("k2", "reception", "Reception", "2027-01-23", "18:30", "Sri Mahal Kalyana Mandapam", "Cathedral Road, Gopalapuram, Chennai", { dressCode: "Festive silks" }),
        ev("k3", "wedding", "Muhurtham", "2027-01-24", "07:30", "Sri Mahal Kalyana Mandapam", "Cathedral Road, Gopalapuram, Chennai", { note: "Muhurtham between 7:30 and 9:00 AM · breakfast to follow" }),
      ],
      family: { enabled: true, title: "With Best Compliments", names: ["Smt. Saraswathi Ammal", "Mr. S. Raman & Mrs. Gowri Raman", "Mr. V. Prakash & Mrs. Divya Prakash"], kidsTitle: "Eagerly Waiting", kids: ["Aadhya", "Vishnu", "Diya"], kidsLine: "Come, let's eat payasam at Chithappa's wedding!" },
      rsvp: { enabled: true, deadline: "2027-01-10", contacts: [{ name: "S. Venkatesh", phone: "+91 98400 12345" }] },
      closing: { title: "With Best Compliments From", names: ["The Venkatesh & Sundaram Families", "Relatives & Friends"] },
      hashtag: "#KarthikWedsMeenakshi",
      info: [{ label: "Stay", value: "Rooms at Hotel Savera for outstation guests" }],
    }),
  },
  {
    id: "rajwada",
    name: "Rajwada",
    category: "wedding",
    tagline: "Royal parchment scroll, Mewar sun & caparisoned elephants",
    paper: "handmade",
    ornament: "none",
    backdrop: "velvet",
    petals: "marigold",
    fonts: { display: "var(--f-rozha)", script: "var(--f-pinyon)", body: "var(--f-garamond)" },
    palettes: [
      P({ id: "parchment", label: "Parchment", paper: "#f1e2bf", paper2: "#e3cb98", ink: "#5a1a0c", inkSoft: "#8a4c2c", accent: "#c0392b", accent2: "#1f5c4a", foil: "gold", surface: "#4a1010", surface2: "#6e1a1a", envelope: "#f3e4c3", envelope2: "#c0392b", wax: "#9c1c12" }),
      P({ id: "saffron", label: "Kesariya", paper: "#f5d08a", paper2: "#eab45a", ink: "#5a1f06", inkSoft: "#87461c", accent: "#b8321e", accent2: "#2b5a8a", foil: "gold", surface: "#3d1a08", surface2: "#6a2e0e", envelope: "#fbe7b8", envelope2: "#b8321e", wax: "#8c1b0e" }),
      P({ id: "indigo", label: "Raat Indigo", paper: "#1f2754", paper2: "#141a3c", ink: "#f3e3c0", inkSoft: "#cbb88d", accent: "#d9442f", accent2: "#e8b23a", foil: "gold", surface: "#0b0f26", surface2: "#1d2550", envelope: "#efe3c8", envelope2: "#1f2754", wax: "#a8231a" }),
    ],
    styles: ["Royal", "Traditional", "Rajasthani"],
    effects: ["Scroll unroll", "Scroll pages", "Block print", "Hot foil", "Petals"],
    wed: { design: "rajwada", intro: "scroll", turn: "rise", reveal: "stamp" },
    sample: sample("parchment", {
      symbol: "ganesha-riddhi",
      hosts: "Thakur Raghuveer Singh & Thakurani Padmini Kanwar",
      inviteText: "solicit your gracious presence at the wedding of their son",
      primary: { name: "Vikramaditya", subtitle: "Son of Thakur Raghuveer Singh & Thakurani Padmini Kanwar", parents: "Grandson of Late Thakur Bhawani Singh" },
      secondary: { name: "Gayatri", subtitle: "Daughter of Rawat Jaswant Singh & Rani Indira Kumari" },
      quote: "Two royal houses, one celebration.",
      mainDateTime: "2027-02-14T20:00",
      mainEventId: "r5",
      events: [
        ev("r1", "ganesh", "Ganesh Puja", "2027-02-12", "10:00", "Haveli Raghuveer Niwas", "Chandpole, Jaipur", { audience: "family" }),
        ev("r2", "mehendi", "Mehendi", "2027-02-13", "12:00", "Samode Bagh", "Samode, Jaipur", { dressCode: "Leheriya & florals" }),
        ev("r3", "sangeet", "Sangeet & Ghoomar", "2027-02-13", "19:30", "Samode Bagh", "Samode, Jaipur", { dressCode: "Rajputi poshak / bandhgala" }),
        ev("r4", "baraat", "Baraat", "2027-02-14", "18:30", "Haveli Raghuveer Niwas", "Chandpole, Jaipur", { dressCode: "Safa will be provided" }),
        ev("r5", "wedding", "Paanigrahan", "2027-02-14", "20:00", "Rambagh Palace", "Bhawani Singh Road, Jaipur", { note: "Pheras at the auspicious hour of 11:40 PM" }),
        ev("r6", "reception", "Reception", "2027-02-15", "19:30", "Rambagh Palace", "Bhawani Singh Road, Jaipur", { dressCode: "Royal formal" }),
      ],
      closing: { title: "With Warm Regards From", names: ["The Rathore & Chundawat Families", "Kith & Kin"] },
      hashtag: "#VikramKiGayatri",
      family: { enabled: true, title: "With Warm Regards", names: ["Rajmata Saroj Kanwar", "Thakur Mahendra Singh & Thakurani Kusum Kanwar", "Kunwar Ajay Singh & Kunwarani Neha Kanwar"], kidsTitle: "Eagerly Awaiting", kids: ["Baisa Diya", "Kunwar Aditya", "Baisa Myra"], kidsLine: "Come join our Kaka-sa's baraat!" },
      rsvp: { enabled: true, deadline: "2027-01-31", contacts: [{ name: "Thakur Raghuveer Singh", phone: "+91 94140 12345" }, { name: "Kunwar Ajay Singh", phone: "+91 98290 67890" }] },
      info: [
        { label: "Stay", value: "Guest suites at Samode Bagh from 12 Feb" },
        { label: "Travel", value: "Cars from Jaipur airport on all three days" },
      ],
    }),
  },
  {
    id: "gulmohar",
    name: "Gulmohar",
    category: "wedding",
    tagline: "Watercolour flame-tree blossoms around a soft arch",
    paper: "cotton",
    ornament: "none",
    backdrop: "linen",
    petals: "rose",
    fonts: { display: "var(--f-dm-serif)", script: "var(--f-allura)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "flame", label: "Gulmohar", paper: "#fbf5ea", paper2: "#f3e6d2", ink: "#4b3226", inkSoft: "#85695a", accent: "#e8572a", accent2: "#7d9a5a", foil: "gold", surface: "#ecdfcf", surface2: "#d9c6b0", envelope: "#f8efe2", envelope2: "#e8a07f", wax: "#b8321e" }),
      P({ id: "blush", label: "Blush", paper: "#fcf4f1", paper2: "#f4e1dc", ink: "#5a3a3c", inkSoft: "#8f6f70", accent: "#e48b9b", accent2: "#94a888", foil: "rosegold", surface: "#eedfdb", surface2: "#dcc5bf", envelope: "#f9ece8", envelope2: "#e7b4bd", wax: "#b5576b" }),
      P({ id: "lilac", label: "Jacaranda", paper: "#f7f4fa", paper2: "#e9e1f0", ink: "#43385a", inkSoft: "#75698c", accent: "#a68bd6", accent2: "#8fa58a", foil: "silver", surface: "#e6e0ed", surface2: "#cfc5db", envelope: "#f2edf6", envelope2: "#b39ddb", wax: "#6d5a91" }),
    ],
    styles: ["Floral", "Modern", "Pastel"],
    effects: ["Flowers part", "Dissolve", "Watercolour", "Petals"],
    wed: { design: "gulmohar", intro: "bloom", turn: "dissolve", reveal: "bloom" },
    sample: sample("flame", {
      symbol: "lotus",
      mantra: "",
      joiner: "&",
      hosts: "The Deshpande & Kulkarni Families",
      inviteText: "joyfully invite you to celebrate the wedding of",
      hostSide: "both",
      primary: { name: "Arjun", subtitle: "Son of Mr. Milind & Mrs. Varsha Deshpande" },
      secondary: { name: "Ishita", subtitle: "Daughter of Mr. Sameer & Mrs. Anjali Kulkarni" },
      quote: "And in the season of gulmohar, we found our forever.",
      mainDateTime: "2027-04-18T18:00",
      mainEventId: "g3",
      events: [
        ev("g1", "haldi", "Haldi", "2027-04-17", "10:00", "The Orchard Lawns", "Koregaon Park, Pune", { dressCode: "Shades of yellow" }),
        ev("g2", "sangeet", "Sangeet", "2027-04-17", "19:00", "The Orchard Lawns", "Koregaon Park, Pune", { dressCode: "Pastels & sparkle" }),
        ev("g3", "wedding", "Wedding", "2027-04-18", "18:00", "Gulmohar Gardens", "Baner Road, Pune", { note: "Sunset vows followed by dinner" }),
      ],
      hashtag: "#ArjunIshitaInBloom",
      family: { enabled: false, title: "With Love", names: [], kidsTitle: "", kids: [] },
      rsvp: { enabled: true, deadline: "2027-04-01", contacts: [{ name: "Ishita", phone: "+91 98220 12345" }, { name: "Arjun", phone: "+91 98500 67890" }] },
      info: [{ label: "Stay", value: "A block of rooms at The Westin, Koregaon Park" }, { label: "Gifts", value: "Your blessings are all we wish for" }],
      story: { enabled: false, title: "Our Story", text: "", photos: [] },
    }),
  },
  {
    id: "ink-ivory",
    name: "Ink & Ivory",
    category: "wedding",
    tagline: "Letterpress monogram on cotton stock, quietly elegant",
    paper: "cotton",
    ornament: "none",
    backdrop: "studio",
    petals: "gold",
    fonts: { display: "var(--f-bodoni)", script: "var(--f-bodoni)", body: "var(--f-tenor)" },
    palettes: [
      P({ id: "ivory", label: "Ivory & Ink", paper: "#f6f1e7", paper2: "#ebe3d3", ink: "#1d1b19", inkSoft: "#6b645a", accent: "#e8dcc4", accent2: "#b9a88a", foil: "gold", surface: "#d8d2c6", surface2: "#bfb7a8", envelope: "#1d1b19", envelope2: "#f6f1e7", wax: "#1d1b19" }),
      P({ id: "sand", label: "Sand", paper: "#efe4d2", paper2: "#e1d1b8", ink: "#3b2a1e", inkSoft: "#7d6650", accent: "#8c6a4a", accent2: "#c4a882", foil: "copper", surface: "#cbbba4", surface2: "#b09d83", envelope: "#f4ece0", envelope2: "#8c6a4a", wax: "#5e432c" }),
      P({ id: "slate", label: "Slate", paper: "#2b2e33", paper2: "#1e2125", ink: "#f2ede4", inkSoft: "#a9a399", accent: "#c9b38a", accent2: "#5b6068", foil: "silver", surface: "#121417", surface2: "#2a2d32", envelope: "#e9e4da", envelope2: "#2b2e33", wax: "#2b2e33" }),
      P({ id: "bordeaux", label: "Bordeaux", paper: "#f8efec", paper2: "#ecdcd7", ink: "#5b1a26", inkSoft: "#8e5a62", accent: "#f8efec", accent2: "#d8b4b4", foil: "rosegold", surface: "#e8d8d3", surface2: "#d2bcb6", envelope: "#5b1a26", envelope2: "#f8efec", wax: "#5b1a26" }),
    ],
    styles: ["Minimal", "Modern", "Luxury"],
    effects: ["Keepsake box", "Card stack", "Letterpress", "Monogram"],
    wed: { design: "ink", intro: "box", turn: "stack", reveal: "type" },
    sample: sample("ivory", {
      tradition: "civil",
      symbol: "none",
      mantra: "",
      eyebrow: "Together with their families",
      blessingLine: "Together with their families",
      hosts: "The Mehra & Iyer Families",
      inviteText: "invite you to celebrate the marriage of",
      hostSide: "both",
      joiner: "&",
      primary: { name: "Neil", subtitle: "Son of Rohit & Sheetal Mehra" },
      secondary: { name: "Tara", subtitle: "Daughter of Arvind & Meera Iyer" },
      quote: "",
      effects: { petals: false },
      mainDateTime: "2026-12-05T17:30",
      mainEventId: "i2",
      events: [
        ev("i1", "cocktail", "Welcome Drinks", "2026-12-04", "20:00", "The Library Bar, Taj Lands End", "Bandstand, Bandra West, Mumbai", { dressCode: "Black tie" }),
        ev("i2", "wedding", "The Ceremony", "2026-12-05", "17:30", "The Sea Lawn, Taj Lands End", "Bandstand, Bandra West, Mumbai"),
        ev("i3", "reception", "Dinner & Dancing", "2026-12-05", "20:00", "Ballroom, Taj Lands End", "Bandstand, Bandra West, Mumbai", { dressCode: "Formal" }),
      ],
      family: { enabled: false, title: "With Love", names: [], kidsTitle: "", kids: [] },
      closing: { title: "With Love", names: ["Neil & Tara"] },
      hashtag: "#NeilAndTaraSayYes",
      rsvp: { enabled: true, deadline: "2026-11-15", contacts: [{ name: "Tara", phone: "+91 98200 12345" }, { name: "Neil", phone: "+91 98190 67890" }] },
      info: [{ label: "Gifts", value: "Your presence is the only present we need" }],
    }),
  },
  {
    id: "pichwai",
    name: "Pichwai",
    category: "wedding",
    tagline: "Nathdwara folk art: lotus pond, jasmine & gentle cows",
    paper: "matte",
    ornament: "none",
    backdrop: "silk",
    petals: "marigold",
    fonts: { display: "var(--f-yatra)", script: "var(--f-great-vibes)", body: "var(--f-marcellus)" },
    palettes: [
      P({ id: "teal", label: "Kamal Teal", paper: "#0e3f3c", paper2: "#0a2e2c", ink: "#f6ead0", inkSoft: "#d6c497", accent: "#c2185b", accent2: "#e98aa5", foil: "gold", surface: "#061b1a", surface2: "#0e3a37", envelope: "#f3e7cf", envelope2: "#0e3f3c", wax: "#9c1650" }),
      P({ id: "night", label: "Sharad Purnima", paper: "#141c3d", paper2: "#0c1230", ink: "#f5ecd6", inkSoft: "#c9bc98", accent: "#b0346a", accent2: "#f0a3bd", foil: "gold", surface: "#070b1c", surface2: "#151d3e", envelope: "#efe6d2", envelope2: "#141c3d", wax: "#8a1f4c" }),
      P({ id: "vermilion", label: "Sindoor", paper: "#8e1b1b", paper2: "#6a1010", ink: "#f8ecd2", inkSoft: "#e5c99a", accent: "#0f5a4a", accent2: "#f6b0c4", foil: "gold", surface: "#2c0707", surface2: "#5a1010", envelope: "#f6e8cf", envelope2: "#8e1b1b", wax: "#5a0c0c" }),
    ],
    styles: ["Folk art", "Traditional", "Pichwai"],
    effects: ["Curtain rise", "Swipe", "Folk art", "Hot foil", "Petals"],
    wed: { design: "pichwai", intro: "curtain", turn: "swipe", reveal: "float" },
    sample: sample("teal", {
      symbol: "lotus",
      mantra: "|| Jai Shri Krishna ||",
      blessingLine: "With the blessings of Shrinathji and the love of our elders",
      hosts: "Mr. Govind Paliwal & Mrs. Sushila Paliwal",
      primary: { name: "Madhav", subtitle: "Son of Mr. Govind & Mrs. Sushila Paliwal" },
      secondary: { name: "Radhika", subtitle: "Daughter of Mr. Hariprasad & Mrs. Usha Sanadhya" },
      quote: "As the lotus belongs to the water, so do we belong to each other.",
      mainDateTime: "2027-03-07T19:00",
      mainEventId: "p4",
      events: [
        ev("p1", "puja", "Shrinathji Darshan & Puja", "2027-03-06", "08:00", "Nathdwara Temple", "Nathdwara, Rajsamand", { audience: "family" }),
        ev("p2", "mehendi", "Mehendi", "2027-03-06", "13:00", "Lake Pichola Ghat Garden", "Lal Ghat, Udaipur", { dressCode: "Greens & florals" }),
        ev("p3", "sangeet", "Raas & Sangeet", "2027-03-06", "19:30", "Lake Pichola Ghat Garden", "Lal Ghat, Udaipur", { dressCode: "Chaniya choli & kediyu" }),
        ev("p4", "wedding", "Shubh Vivah", "2027-03-07", "19:00", "Jagmandir Island Palace", "Lake Pichola, Udaipur", { note: "Boats from Rameshwar Ghat from 6:00 PM" }),
      ],
      closing: { title: "With Love & Blessings From", names: ["The Paliwal & Sanadhya Families", "Friends & Well-wishers"] },
      hashtag: "#MadhavKiRadhika",
      family: { enabled: true, title: "With Warm Regards", names: ["Smt. Kamla Paliwal", "Mr. Mohan & Mrs. Geeta Paliwal", "Mr. Kishore & Mrs. Rekha Paliwal"], kidsTitle: "Eagerly Awaiting", kids: ["Kanha", "Meera", "Gopal"], kidsLine: "Come see our Bhaiya become a groom!" },
      rsvp: { enabled: true, deadline: "2027-02-20", contacts: [{ name: "Govind Paliwal", phone: "+91 94141 12345" }] },
      info: [{ label: "Stay", value: "Rooms at Hotel Lakend, Udaipur for outstation guests" }, { label: "Travel", value: "Cars from Udaipur airport and to Nathdwara on 6 March" }],
    }),
  },
  /* ---------------- batch 2 ---------------- */
  {
    id: "alpona",
    name: "Alpona",
    category: "wedding",
    tagline: "Bengali red & white: alpona, Prajapati, topor and the fish pair",
    paper: "handmade",
    ornament: "none",
    backdrop: "paper",
    petals: "jasmine",
    fonts: { display: "var(--f-fraunces)", script: "var(--f-parisienne)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "lalpaar", label: "Lal Paar", paper: "#fbf6ee", paper2: "#f1e6d6", ink: "#5a1414", inkSoft: "#8c4a40", accent: "#c8102e", accent2: "#c8102e", foil: "gold", surface: "#e9dccb", surface2: "#d3c0a8", envelope: "#fbf3e6", envelope2: "#c8102e", wax: "#a00d24" }),
      P({ id: "sindoor", label: "Sindoor", paper: "#9e1020", paper2: "#7a0a17", ink: "#fbefd8", inkSoft: "#f0cfa3", accent: "#fffaf0", accent2: "#f6ead2", foil: "gold", surface: "#3a0609", surface2: "#650b14", envelope: "#f6ead2", envelope2: "#9e1020", wax: "#7a0a17" }),
      P({ id: "dhakai", label: "Dhakai Green", paper: "#1e4a37", paper2: "#143427", ink: "#f8eed6", inkSoft: "#d8c79c", accent: "#fffaf0", accent2: "#c8102e", foil: "gold", surface: "#0b1f17", surface2: "#1b4232", envelope: "#f4e9d2", envelope2: "#c8102e", wax: "#a00d24" }),
    ],
    styles: ["Traditional", "Bengali", "Minimal"],
    effects: ["Alpona painting", "Fan turn", "Folk art", "Hot foil", "Petals"],
    wed: { design: "alpona", intro: "alpona", turn: "fan", reveal: "sweep" },
    sample: sample("lalpaar", {
      symbol: "none",
      mantra: "|| Sri Sri Prajapataye Namah ||",
      eyebrow: "Shubho Bibaho",
      blessingLine: "With the blessings of our elders and the grace of Prajapati",
      hosts: "Mr. Subhasis Chatterjee & Mrs. Rina Chatterjee",
      inviteText: "solicit your gracious presence at the wedding of their son",
      primary: { name: "Arnab", subtitle: "Son of Mr. Subhasis & Mrs. Rina Chatterjee" },
      secondary: { name: "Paromita", subtitle: "Daughter of Mr. Debashis & Mrs. Sharmila Banerjee" },
      quote: "Ei poth jodi na sesh hoy… may this road never end.",
      mainDateTime: "2027-02-05T20:00",
      mainEventId: "b3",
      events: [
        ev("b1", "puja", "Ashirbad", "2027-02-04", "11:00", "Chatterjee Bari", "17/2, Hindustan Park, Kolkata", { audience: "family" }),
        ev("b2", "haldi", "Gaye Holud", "2027-02-05", "09:00", "Chatterjee Bari", "17/2, Hindustan Park, Kolkata", { dressCode: "Yellow & white" }),
        ev("b3", "wedding", "Biye", "2027-02-05", "20:00", "Monohar Das Bhavan", "Ballygunge Circular Road, Kolkata", { note: "Lagna at 9:42 PM" }),
        ev("b4", "reception", "Bou Bhaat", "2027-02-07", "19:30", "The Conclave", "EM Bypass, Kolkata", { dressCode: "Festive" }),
      ],
      closing: { title: "With Best Compliments From", names: ["The Chatterjee & Banerjee Families", "Relatives & Friends"] },
      hashtag: "#ArnabParomitarBiye",
      family: { enabled: true, title: "With Warm Regards", names: ["Smt. Bela Chatterjee", "Mr. Tapas & Mrs. Mitali Chatterjee", "Mr. Amitava & Mrs. Sudeshna Ghosh"], kidsTitle: "Eagerly Waiting", kids: ["Tuktuki", "Bumba", "Mishti"], kidsLine: "Come eat rosogolla at our Kaku's biye!" },
      rsvp: { enabled: true, deadline: "2027-01-25", contacts: [{ name: "Subhasis Chatterjee", phone: "+91 98300 12345" }, { name: "Tapas Chatterjee", phone: "+91 98310 67890" }] },
      info: [{ label: "Stay", value: "Rooms at The Peerless Inn for guests from out of town" }, { label: "Gifts", value: "Your ashirbad is all we ask for" }],
    }),
  },
  {
    id: "phulkari",
    name: "Phulkari",
    category: "wedding",
    tagline: "Punjabi satin-stitch embroidery with golden kaleere",
    paper: "linen",
    ornament: "none",
    backdrop: "felt",
    petals: "marigold",
    fonts: { display: "var(--f-shrikhand)", script: "var(--f-great-vibes)", body: "var(--f-jost)" },
    palettes: [
      P({ id: "rust", label: "Khaddar Rust", paper: "#8e2f1c", paper2: "#6a2112", ink: "#fbe9c8", inkSoft: "#f2c98a", accent: "#f5a623", accent2: "#e91e63", foil: "gold", surface: "#2c0e06", surface2: "#5a1d0f", envelope: "#f7e6c8", envelope2: "#8e2f1c", wax: "#ffd23f" }),
      P({ id: "kaala", label: "Kaala", paper: "#1f1a1a", paper2: "#120f0f", ink: "#fbeed8", inkSoft: "#e5c79a", accent: "#ff8f1f", accent2: "#e0218a", foil: "gold", surface: "#0a0808", surface2: "#2a2222", envelope: "#f3e5cc", envelope2: "#1f1a1a", wax: "#ffd23f" }),
      P({ id: "hara", label: "Hara", paper: "#1d4a2f", paper2: "#123520", ink: "#fbf0d8", inkSoft: "#e4d19f", accent: "#ff9f1c", accent2: "#f72585", foil: "gold", surface: "#0a1e12", surface2: "#1b3f28", envelope: "#f4e8cf", envelope2: "#1d4a2f", wax: "#ffd23f" }),
    ],
    styles: ["Traditional", "Punjabi", "Colourful"],
    effects: ["Cloth unfold", "Calendar flip", "Embroidery", "Hot foil", "Petals"],
    wed: { design: "phulkari", intro: "unfold", turn: "flipdown", reveal: "drop" },
    sample: sample("rust", {
      tradition: "sikh",
      symbol: "khanda",
      mantra: "Ik Onkar",
      eyebrow: "Anand Karaj",
      blessingLine: "With the blessings of Waheguru and the grace of our elders",
      joiner: "&",
      hosts: "S. Gurpreet Singh Sandhu & Sardarni Manjit Kaur",
      inviteText: "request the pleasure of your company at the Anand Karaj of their son",
      primary: { name: "Harjot", subtitle: "Son of S. Gurpreet Singh & Sardarni Manjit Kaur" },
      secondary: { name: "Simran", subtitle: "Daughter of S. Kulwant Singh & Sardarni Harleen Kaur" },
      quote: "Ek jot doye moorti: one soul in two bodies.",
      mainDateTime: "2027-11-20T10:00",
      mainEventId: "s4",
      events: [
        ev("s1", "chooda", "Chooda & Kaleere", "2027-11-19", "10:00", "Sandhu Farmhouse", "GT Road, Amritsar", { audience: "family" }),
        ev("s2", "mehendi", "Mehendi", "2027-11-19", "15:00", "Sandhu Farmhouse", "GT Road, Amritsar", { dressCode: "Phulkari dupattas" }),
        ev("s3", "sangeet", "Jaago & Sangeet", "2027-11-19", "20:00", "Sandhu Farmhouse", "GT Road, Amritsar", { dressCode: "Bright & bold" }),
        ev("s4", "anand-karaj", "Anand Karaj", "2027-11-20", "10:00", "Gurdwara Shaheedan Sahib", "Chowk Chabutra, Amritsar", { dressCode: "Heads covered in the Gurdwara", note: "Langar to follow" }),
        ev("s5", "reception", "Reception", "2027-11-20", "19:30", "Radisson Blu", "Airport Road, Amritsar", { dressCode: "Formal" }),
      ],
      closing: { title: "With Love & Regards From", names: ["The Sandhu & Gill Families", "Rishtedaar & Friends"] },
      hashtag: "#HarjotDiSimran",
      family: { enabled: true, title: "With Love & Regards", names: ["Bebe Surjit Kaur", "S. Harpal Singh & Sardarni Rajinder Kaur", "S. Jaspal Singh & Sardarni Navneet Kaur"], kidsTitle: "Eagerly Waiting", kids: ["Gurnoor", "Fateh", "Jasleen"], kidsLine: "Come do bhangra at our Chachu's wedding!" },
      rsvp: { enabled: true, deadline: "2027-11-05", contacts: [{ name: "S. Gurpreet Singh", phone: "+91 98140 12345" }, { name: "S. Harpal Singh", phone: "+91 98720 67890" }] },
      info: [{ label: "Stay", value: "Rooms at Radisson Blu, Amritsar from 18 Nov" }, { label: "Darshan", value: "A visit to Sri Harmandir Sahib on 21 Nov" }],
    }),
  },
  {
    id: "bandhej",
    name: "Bandhej",
    category: "wedding",
    tagline: "Gujarati bandhani dots, mirror work, garbo & dandiya",
    paper: "matte",
    ornament: "none",
    backdrop: "silk",
    petals: "rose",
    fonts: { display: "var(--f-playfair)", script: "var(--f-allura)", body: "var(--f-montserrat)" },
    palettes: [
      P({ id: "laal", label: "Laal Lila", paper: "#b3121f", paper2: "#8a0c17", ink: "#fff3d6", inkSoft: "#f6d79a", accent: "#f6c343", accent2: "#1f8a46", foil: "gold", surface: "#3b0509", surface2: "#6e0a12", envelope: "#fbecc9", envelope2: "#b3121f", wax: "#1f8a46" }),
      P({ id: "rani", label: "Rani", paper: "#b0136b", paper2: "#860d51", ink: "#fff3dc", inkSoft: "#f8d4a0", accent: "#ff7a1a", accent2: "#f4c430", foil: "gold", surface: "#3a0623", surface2: "#6d0c42", envelope: "#fdeccf", envelope2: "#b0136b", wax: "#ff7a1a" }),
      P({ id: "mor", label: "Mor Peacock", paper: "#0b4f6c", paper2: "#073a50", ink: "#fff2d6", inkSoft: "#f0d39a", accent: "#e8366b", accent2: "#f28c28", foil: "gold", surface: "#03202d", surface2: "#0a4560", envelope: "#fbecd0", envelope2: "#0b4f6c", wax: "#f28c28" }),
    ],
    styles: ["Traditional", "Gujarati", "Colourful"],
    effects: ["Garba twirl", "Twirl turn", "Tie-dye dots", "Mirror work", "Petals"],
    wed: { design: "bandhej", intro: "twirl", turn: "twirl", reveal: "pop" },
    sample: sample("laal", {
      mantra: "|| Shree Ganeshaya Namah ||",
      eyebrow: "Shubh Lagna",
      hosts: "Shri Nilesh Patel & Smt. Hetal Patel",
      primary: { name: "Parth", subtitle: "Son of Shri Nilesh & Smt. Hetal Patel" },
      secondary: { name: "Khushi", subtitle: "Daughter of Shri Jignesh & Smt. Falguni Shah" },
      quote: "Rangeela re, two hearts in one garba circle.",
      mainDateTime: "2027-01-31T19:00",
      mainEventId: "j5",
      events: [
        ev("j1", "ganesh", "Ganesh Sthapana", "2027-01-29", "09:00", "Patel Niwas", "Satellite Road, Ahmedabad", { audience: "family" }),
        ev("j2", "mandap", "Mandap Muhurat", "2027-01-30", "10:00", "Patel Niwas", "Satellite Road, Ahmedabad", { audience: "family" }),
        ev("j3", "mehendi", "Mehendi & Pithi", "2027-01-30", "15:00", "Karnavati Club", "SG Highway, Ahmedabad", { dressCode: "Shades of green & yellow" }),
        ev("j4", "sangeet", "Dandiya Raas", "2027-01-30", "20:00", "Karnavati Club", "SG Highway, Ahmedabad", { dressCode: "Chaniya choli & kediyu" }),
        ev("j5", "wedding", "Hast Melap", "2027-01-31", "19:00", "Sankalp Party Plot", "Sindhu Bhavan Road, Ahmedabad", { note: "Jaan arrives at 6:00 PM" }),
      ],
      closing: { title: "Sneh Sahit", names: ["The Patel & Shah Families", "Sagaa Sambandhi"] },
      hashtag: "#ParthNiKhushi",
      family: { enabled: true, title: "Sneh Sahit", names: ["Smt. Savitaben Patel", "Shri Mukesh & Smt. Daksha Patel", "Shri Rajesh & Smt. Bhavna Patel"], kidsTitle: "Aatur Nayane", kids: ["Dhruv", "Riya", "Krish"], kidsLine: "Come play garba at our Kaka's lagna!" },
      rsvp: { enabled: true, deadline: "2027-01-15", contacts: [{ name: "Nilesh Patel", phone: "+91 98250 12345" }, { name: "Mukesh Patel", phone: "+91 98790 67890" }] },
      info: [{ label: "Stay", value: "Rooms at Hyatt Regency, Ashram Road" }, { label: "Food", value: "Pure vegetarian; Jain food on request" }],
    }),
  },
  {
    id: "noor",
    name: "Noor",
    category: "wedding",
    tagline: "Nikah invitation: girih stars, pointed arch & lanterns",
    paper: "silk",
    ornament: "none",
    backdrop: "marble",
    petals: "rose",
    fonts: { display: "var(--f-cinzel)", script: "var(--f-great-vibes)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "emerald", label: "Emerald", paper: "#0b3d2e", paper2: "#072a20", ink: "#f3e7c8", inkSoft: "#c9b47e", accent: "#c9a24a", accent2: "#1b6b52", foil: "gold", surface: "#04170f", surface2: "#0d3a2b", envelope: "#f2e8d0", envelope2: "#0b3d2e", wax: "#7a5a1a" }),
      P({ id: "midnight", label: "Midnight", paper: "#111a3a", paper2: "#0a1028", ink: "#f2e6c6", inkSoft: "#bfae82", accent: "#c9a24a", accent2: "#24347a", foil: "gold", surface: "#05081a", surface2: "#111a3a", envelope: "#efe6d0", envelope2: "#111a3a", wax: "#7a5a1a" }),
      P({ id: "ivory", label: "Ivory & Teal", paper: "#f7f1e3", paper2: "#ece2cc", ink: "#0f4c45", inkSoft: "#5f857f", accent: "#0f4c45", accent2: "#b48a3c", foil: "gold", surface: "#e3d9c5", surface2: "#cbbd9f", envelope: "#f7f1e3", envelope2: "#0f4c45", wax: "#0f4c45" }),
      P({ id: "rose", label: "Dusty Rose", paper: "#f3e3e0", paper2: "#e7cfca", ink: "#5b2333", inkSoft: "#8f5d68", accent: "#5b2333", accent2: "#c48f86", foil: "rosegold", surface: "#e6d3cf", surface2: "#cfb5af", envelope: "#f6ebe8", envelope2: "#5b2333", wax: "#5b2333" }),
    ],
    styles: ["Elegant", "Nikah", "Luxury"],
    effects: ["Lattice screens", "Zoom turn", "Geometric", "Hot foil", "Petals"],
    wed: { design: "noor", intro: "jaali", turn: "zoom", reveal: "spin" },
    sample: sample("emerald", {
      tradition: "muslim",
      symbol: "crescent",
      mantra: "Bismillah ir-Rahman ir-Rahim",
      eyebrow: "Nikah Invitation",
      blessingLine: "With the blessings of Allah and the duas of our elders",
      joiner: "&",
      hosts: "Mr. Imran Qureshi & Mrs. Nazia Qureshi",
      inviteText: "request the honour of your presence at the Nikah of their son",
      primary: { name: "Ayaan", subtitle: "Son of Mr. Imran & Mrs. Nazia Qureshi" },
      secondary: { name: "Zoya", subtitle: "Daughter of Mr. Faisal & Mrs. Rukhsana Siddiqui" },
      quote: "And We created you in pairs. (Qur'an 78:8)",
      mainDateTime: "2027-03-19T13:30",
      mainEventId: "n3",
      events: [
        ev("n1", "haldi", "Manjha", "2027-03-17", "16:00", "Qureshi Manzil", "Hazratganj, Lucknow", { audience: "family", dressCode: "Yellow" }),
        ev("n2", "mehendi", "Mehendi Night", "2027-03-18", "19:00", "Qureshi Manzil", "Hazratganj, Lucknow", { dressCode: "Greens & florals" }),
        ev("n3", "nikah", "Nikah", "2027-03-19", "13:30", "Taj Mahal Lucknow", "Gomti Nagar, Lucknow", { note: "Followed by lunch" }),
        ev("n4", "walima", "Walima", "2027-03-20", "20:00", "Taj Mahal Lucknow", "Gomti Nagar, Lucknow", { dressCode: "Formal" }),
      ],
      family: { enabled: true, title: "With Warm Regards", names: ["Mrs. Shabana Qureshi", "Mr. Arif & Mrs. Sana Qureshi", "Mr. Adil & Mrs. Huma Khan"], kidsTitle: "Eagerly Waiting", kids: ["Aryan", "Inaya", "Rehan"], kidsLine: "Come dance at our Chachu's mehendi!" },
      closing: { title: "With Best Compliments From", names: ["The Qureshi & Siddiqui Families", "Friends & Well-wishers"] },
      hashtag: "#AyaanKiZoya",
      rsvp: { enabled: true, deadline: "2027-03-05", contacts: [{ name: "Imran Qureshi", phone: "+91 98390 12345" }, { name: "Arif Qureshi", phone: "+91 94150 67890" }] },
      info: [{ label: "Stay", value: "Rooms at Taj Mahal Lucknow for outstation guests" }, { label: "Gifts", value: "Your duas are the only gift we ask for" }],
    }),
  },
  {
    id: "jaali-lace",
    name: "Jaali Lace",
    category: "wedding",
    tagline: "Metallic laser-cut lace over soft card, opens like a gatefold",
    paper: "pearl",
    ornament: "none",
    backdrop: "slate",
    petals: "gold",
    fonts: { display: "var(--f-italiana)", script: "var(--f-pinyon)", body: "var(--f-tenor)" },
    palettes: [
      P({ id: "gold", label: "Gold on Ivory", paper: "#fbf7ee", paper2: "#f0e7d6", ink: "#4a3b22", inkSoft: "#86734f", accent: "#c9a45a", accent2: "#7a1f2b", foil: "gold", surface: "#2a2622", surface2: "#46403a", envelope: "#f6efe0", envelope2: "#c9a45a", wax: "#7a1f2b" }),
      P({ id: "rose", label: "Rose Gold Blush", paper: "#fbefeb", paper2: "#f2dcd6", ink: "#5b3a3a", inkSoft: "#94706c", accent: "#d39a8c", accent2: "#5b3a3a", foil: "rosegold", surface: "#2c2224", surface2: "#4a3a3c", envelope: "#f8ebe6", envelope2: "#d39a8c", wax: "#8c4f55" }),
      P({ id: "navy", label: "Silver on Navy", paper: "#1b2546", paper2: "#131a33", ink: "#eef0f5", inkSoft: "#aeb6c8", accent: "#c0c6d2", accent2: "#c0c6d2", foil: "silver", surface: "#0a0e1c", surface2: "#1b2546", envelope: "#e9ecf2", envelope2: "#1b2546", wax: "#4a5578" }),
      P({ id: "emerald", label: "Gold on Emerald", paper: "#0f3b30", paper2: "#0a2b23", ink: "#f4ead0", inkSoft: "#cdbb8c", accent: "#c9a45a", accent2: "#c9a45a", foil: "gold", surface: "#05160f", surface2: "#0f3b30", envelope: "#f2e8d0", envelope2: "#0f3b30", wax: "#7a5a1a" }),
    ],
    styles: ["Modern", "Luxury", "Laser-cut"],
    effects: ["Gatefold", "Drop turn", "Laser-cut", "Hot foil", "Petals"],
    wed: { design: "lace", intro: "gatefold", turn: "drop", reveal: "zoom" },
    sample: sample("gold", {
      hosts: "Mr. Sanjay Kapoor & Mrs. Ritu Kapoor",
      primary: { name: "Aarav", subtitle: "Son of Mr. Sanjay & Mrs. Ritu Kapoor" },
      secondary: { name: "Naina", subtitle: "Daughter of Mr. Ashok & Mrs. Geeta Malhotra" },
      quote: "Woven together, thread by golden thread.",
      hashtag: "#AaravWedsNaina",
      family: { enabled: true, title: "With Warm Regards", names: ["Smt. Kanta Kapoor", "Mr. Vinod & Mrs. Anju Kapoor", "Mr. Rakesh & Mrs. Pooja Mehra"], kidsTitle: "Eagerly Awaiting", kids: ["Advik", "Saanvi", "Kabir"], kidsLine: "Come dance at our Chachu's wedding!" },
      rsvp: { enabled: true, deadline: "2026-11-25", contacts: [{ name: "Sanjay Kapoor", phone: "+91 98110 12345" }, { name: "Vinod Kapoor", phone: "+91 98100 67890" }] },
      info: [{ label: "Stay", value: "Rooms at The Leela Palace, Chanakyapuri" }, { label: "Parking", value: "Valet at all venues" }],
    }),
  },
  /* ---------------- batch 3 ---------------- */
  {
    id: "paithani",
    name: "Paithani",
    category: "wedding",
    tagline: "Maharashtrian silk: peacocks, lotus zari border & pearl mundavalya",
    paper: "silk",
    ornament: "none",
    backdrop: "velvet",
    petals: "jasmine",
    fonts: { display: "var(--f-shippori)", script: "var(--f-great-vibes)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "jambhla", label: "Jambhla Purple", paper: "#4a1650", paper2: "#320c37", ink: "#f8ead0", inkSoft: "#dcc29a", accent: "#d4a72c", accent2: "#1f7a45", foil: "gold", surface: "#1c0620", surface2: "#3e1244", envelope: "#f4e6cc", envelope2: "#4a1650", wax: "#b8136b" }),
      P({ id: "rani", label: "Rani Pink", paper: "#a3124f", paper2: "#7c0c3b", ink: "#fff0d8", inkSoft: "#f3cfa0", accent: "#e0b43a", accent2: "#1f6b45", foil: "gold", surface: "#3a0619", surface2: "#6d0c35", envelope: "#fbeccf", envelope2: "#a3124f", wax: "#1f6b45" }),
      P({ id: "popat", label: "Popat Green", paper: "#165c3a", paper2: "#0e4128", ink: "#fbf0d6", inkSoft: "#e2d09e", accent: "#d4a72c", accent2: "#7b1fa2", foil: "gold", surface: "#062014", surface2: "#124d31", envelope: "#f4e8cf", envelope2: "#165c3a", wax: "#7b1fa2" }),
    ],
    styles: ["Traditional", "Maharashtrian", "Luxury"],
    effects: ["Silk pallu", "Diagonal flip", "Zari border", "Hot foil", "Petals"],
    wed: { design: "paithani", intro: "pallu", turn: "diagonal", reveal: "rise" },
    sample: sample("jambhla", {
      mantra: "|| Shree Ganeshaya Namah ||",
      eyebrow: "Shubh Vivah",
      blessingLine: "With the blessings of Shree Ganesha and Kuldaivat Khandoba",
      hosts: "Shri Vinayak Deshmukh & Sau. Madhuri Deshmukh",
      inviteText: "request the honour of your presence at the wedding of their son",
      primary: { name: "Aditya", subtitle: "Son of Shri Vinayak & Sau. Madhuri Deshmukh" },
      secondary: { name: "Gauri", subtitle: "Daughter of Shri Prakash & Sau. Sunanda Joshi" },
      quote: "Saat janmanchi saath: together for seven lifetimes.",
      mainDateTime: "2027-05-09T12:35",
      mainEventId: "m4",
      events: [
        ev("m1", "haldi", "Halad", "2027-05-08", "09:00", "Deshmukh Wada", "Sadashiv Peth, Pune", { audience: "family", dressCode: "Yellow" }),
        ev("m2", "mehendi", "Mehendi & Sangeet", "2027-05-08", "17:00", "Pandit Farms", "Karve Nagar, Pune", { dressCode: "Nauvari & kurta" }),
        ev("m3", "baraat", "Simant Pujan", "2027-05-08", "20:30", "Pandit Farms", "Karve Nagar, Pune"),
        ev("m4", "wedding", "Vivah Sohala", "2027-05-09", "12:35", "Pandit Farms", "Karve Nagar, Pune", { note: "Shubh muhurat 12:35 PM · Mangalashtak & Antarpat" }),
        ev("m5", "reception", "Reception", "2027-05-09", "19:30", "Hotel Pride", "Shivajinagar, Pune", { dressCode: "Festive" }),
      ],
      family: { enabled: true, title: "Snehankit", names: ["Smt. Sushila Deshmukh", "Shri Mohan & Sau. Vaishali Deshmukh", "Shri Sandeep & Sau. Rupali Patil"], kidsTitle: "Aaturtene Vaat Pahnare", kids: ["Aarya", "Shlok", "Ira"], kidsLine: "Come for our Kaka's lagna, we'll be waiting!" },
      rsvp: { enabled: true, deadline: "2027-04-25", contacts: [{ name: "Vinayak Deshmukh", phone: "+91 98220 12345" }, { name: "Mohan Deshmukh", phone: "+91 98230 67890" }] },
      closing: { title: "Aaple Namra", names: ["The Deshmukh & Joshi Families", "Aapte Ishta Mitra"] },
      hashtag: "#AdityaGauriChaLagna",
      info: [{ label: "Stay", value: "Rooms at Hotel Pride, Shivajinagar" }, { label: "Food", value: "Traditional Maharashtrian pangat at lunch" }],
    }),
  },
  {
    id: "grace",
    name: "Grace",
    category: "wedding",
    tagline: "Stained-glass window, doves, bells & lily of the valley",
    paper: "pearl",
    ornament: "none",
    backdrop: "marble",
    petals: "rose",
    fonts: { display: "var(--f-playfair)", script: "var(--f-pinyon)", body: "var(--f-garamond)" },
    palettes: [
      P({ id: "ivory", label: "Ivory & Silver", paper: "#fbf8f2", paper2: "#efe9df", ink: "#3b3a44", inkSoft: "#7a7886", accent: "#b9c7e6", accent2: "#8fa58a", foil: "silver", surface: "#e6e2dc", surface2: "#cbc5bc", envelope: "#fbf8f2", envelope2: "#b9c7e6", wax: "#6c7aa0" }),
      P({ id: "blush", label: "Blush & Gold", paper: "#fbf1ee", paper2: "#f1dfda", ink: "#5a3b3e", inkSoft: "#8f6c6f", accent: "#e8b4b8", accent2: "#9cae8c", foil: "gold", surface: "#eadbd6", surface2: "#d5c0ba", envelope: "#fbf1ee", envelope2: "#e8b4b8", wax: "#a8636c" }),
      P({ id: "navy", label: "Midnight Navy", paper: "#17233f", paper2: "#0f182e", ink: "#f2efe8", inkSoft: "#b8bccb", accent: "#5b7fc7", accent2: "#a3b899", foil: "silver", surface: "#080d1a", surface2: "#17233f", envelope: "#ece9e2", envelope2: "#17233f", wax: "#3e5a96" }),
    ],
    styles: ["Elegant", "Christian", "Minimal"],
    effects: ["Lace veil", "Iris turn", "Stained glass", "Hot foil", "Petals"],
    wed: { design: "grace", intro: "veil", turn: "iris", reveal: "blur" },
    sample: sample("ivory", {
      tradition: "christian",
      symbol: "cross",
      mantra: "What God has joined together, let no one separate",
      eyebrow: "Wedding Invitation",
      blessingLine: "By the grace of God and with the blessings of our families",
      joiner: "&",
      hosts: "Mr. Peter D'Souza & Mrs. Lavina D'Souza",
      inviteText: "request the pleasure of your company at the marriage of their son",
      primary: { name: "Joel", subtitle: "Son of Mr. Peter & Mrs. Lavina D'Souza" },
      secondary: { name: "Anita", subtitle: "Daughter of Mr. Francis & Mrs. Maria Fernandes" },
      quote: "Love is patient, love is kind. (1 Corinthians 13:4)",
      mainDateTime: "2027-01-16T16:00",
      mainEventId: "c2",
      events: [
        ev("c1", "haldi", "Ross Ceremony", "2027-01-15", "17:00", "D'Souza Residence", "Aldona, Bardez, Goa", { audience: "family", dressCode: "Whites" }),
        ev("c2", "church", "Nuptial Mass", "2027-01-16", "16:00", "St. Thomas Church", "Aldona, Bardez, Goa"),
        ev("c3", "reception", "Reception & Dinner Dance", "2027-01-16", "19:30", "Casa Aldona Gardens", "Aldona, Goa", { dressCode: "Formal" }),
      ],
      family: { enabled: true, title: "With Love", names: ["Mrs. Philomena D'Souza", "Mr. Anthony & Mrs. Rita D'Souza", "Mr. Joseph & Mrs. Clara Pereira"], kidsTitle: "Flower Girls & Page Boys", kids: ["Ava", "Liam", "Maya"], kidsLine: "Come dance with us at Uncle Joel's wedding!" },
      rsvp: { enabled: true, deadline: "2027-01-02", contacts: [{ name: "Peter D'Souza", phone: "+91 98220 11223" }, { name: "Anita", phone: "+91 98221 44556" }] },
      closing: { title: "With Love From", names: ["The D'Souza & Fernandes Families"] },
      hashtag: "#JoelAndAnitaSayIDo",
      info: [{ label: "Stay", value: "Rooms at Casa Aldona for outstation guests" }, { label: "Gifts", value: "Your prayers and presence mean the most" }],
    }),
  },
  {
    id: "mithila",
    name: "Madhubani",
    category: "wedding",
    tagline: "Mithila folk art: sun, fish pair & lotus in bold black line",
    paper: "handmade",
    ornament: "none",
    backdrop: "paper",
    petals: "marigold",
    fonts: { display: "var(--f-kalam)", script: "var(--f-kalam)", body: "var(--f-cormorant)" },
    palettes: [
      P({ id: "cream", label: "Mithila Cream", paper: "#f6ecd6", paper2: "#eedfc0", ink: "#1a1a1a", inkSoft: "#5b4a3a", accent: "#c62828", accent2: "#2e7d32", foil: "gold", surface: "#e2d2b0", surface2: "#c9b48c", envelope: "#f6ecd6", envelope2: "#c62828", wax: "#c62828" }),
      P({ id: "ochre", label: "Gobar Ochre", paper: "#e8c48a", paper2: "#ddb06c", ink: "#1a1a1a", inkSoft: "#5a3b1a", accent: "#b71c1c", accent2: "#1b5e20", foil: "copper", surface: "#c99a5c", surface2: "#a87b42", envelope: "#f1d9ab", envelope2: "#b71c1c", wax: "#b71c1c" }),
      P({ id: "kohbar", label: "Kohbar Red", paper: "#9e1b1b", paper2: "#7a1212", ink: "#fff6e0", inkSoft: "#f3d8a6", accent: "#f9a825", accent2: "#2e7d32", foil: "gold", surface: "#3a0808", surface2: "#6a1010", envelope: "#f6e6c4", envelope2: "#9e1b1b", wax: "#f9a825" }),
    ],
    styles: ["Folk art", "Bihari", "Colourful"],
    effects: ["Brush reveal", "Wipe turn", "Folk art", "Petals"],
    wed: { design: "madhubani", intro: "brush", turn: "wipe", reveal: "ink" },
    sample: sample("cream", {
      mantra: "|| Shri Ganeshaya Namah ||",
      eyebrow: "Shubh Vivah",
      blessingLine: "With the blessings of Maa Janaki and the grace of our elders",
      hosts: "Shri Ramakant Jha & Smt. Kusum Jha",
      primary: { name: "Abhishek", subtitle: "Son of Shri Ramakant & Smt. Kusum Jha" },
      secondary: { name: "Sneha", subtitle: "Daughter of Shri Umakant & Smt. Rekha Mishra" },
      quote: "Like Ram and Sita in the land of Mithila.",
      mainDateTime: "2027-06-12T21:00",
      mainEventId: "h3",
      events: [
        ev("h1", "tilak", "Tilak", "2027-06-10", "11:00", "Jha Niwas", "Laheriasarai, Darbhanga", { audience: "family" }),
        ev("h2", "haldi", "Haldi & Matkor", "2027-06-11", "10:00", "Jha Niwas", "Laheriasarai, Darbhanga", { dressCode: "Yellow" }),
        ev("h3", "wedding", "Vivah", "2027-06-12", "21:00", "Mithila Vivah Bhawan", "Donar Chowk, Darbhanga", { note: "Kanyadaan at the auspicious hour" }),
        ev("h4", "reception", "Reception", "2027-06-14", "19:30", "Hotel Ganga Vihar", "Darbhanga"),
      ],
      family: { enabled: true, title: "Darshanabhilashi", names: ["Smt. Shanti Devi", "Shri Shashikant & Smt. Asha Jha", "Shri Navin & Smt. Puja Thakur"], kidsTitle: "Eagerly Waiting", kids: ["Anshu", "Gudiya", "Bittu"], kidsLine: "Come to our Chacha's biyah!" },
      rsvp: { enabled: true, deadline: "2027-05-30", contacts: [{ name: "Ramakant Jha", phone: "+91 94311 12345" }] },
      closing: { title: "With Regards From", names: ["The Jha & Mishra Families", "Friends & Well-wishers"] },
      hashtag: "#AbhiWedsSneha",
      info: [{ label: "Stay", value: "Rooms at Hotel Ganga Vihar, Darbhanga" }, { label: "Travel", value: "Darbhanga airport is 15 minutes away" }],
    }),
  },
  {
    id: "saath",
    name: "Saath",
    category: "wedding",
    tagline: "Illustrated couple under a floral arch, pops up like a book",
    paper: "cotton",
    ornament: "none",
    backdrop: "linen",
    petals: "rose",
    fonts: { display: "var(--f-josefin)", script: "var(--f-allura)", body: "var(--f-outfit)" },
    palettes: [
      P({ id: "peach", label: "Peach", paper: "#fdf3ea", paper2: "#f6e2d0", ink: "#4a3a3a", inkSoft: "#8a9a7a", accent: "#e8738a", accent2: "#a7c4b5", foil: "rosegold", surface: "#f0e1d3", surface2: "#dcc5b0", envelope: "#fdf3ea", envelope2: "#e8738a", wax: "#f4a261" }),
      P({ id: "mint", label: "Mint", paper: "#f2f8f4", paper2: "#dfeee5", ink: "#2f4a40", inkSoft: "#7fa38f", accent: "#d64f6b", accent2: "#f2c6a0", foil: "gold", surface: "#e2ece6", surface2: "#c6d8cc", envelope: "#f2f8f4", envelope2: "#7fa38f", wax: "#e9a23b" }),
      P({ id: "lavender", label: "Lavender", paper: "#f6f2fb", paper2: "#e8e0f3", ink: "#3d3456", inkSoft: "#8f9ab8", accent: "#c2185b", accent2: "#f8bbd0", foil: "silver", surface: "#e7e1ef", surface2: "#cfc5dd", envelope: "#f6f2fb", envelope2: "#9a8cc2", wax: "#7e57c2" }),
    ],
    styles: ["Modern", "Illustrated", "Pastel"],
    effects: ["Pop-up", "Turnover", "Illustration", "Petals"],
    wed: { design: "saath", intro: "popup", turn: "turnover", reveal: "slide" },
    sample: sample("peach", {
      symbol: "none",
      mantra: "",
      eyebrow: "We're getting married!",
      blessingLine: "With love and the blessings of our families",
      joiner: "&",
      hostSide: "both",
      hosts: "The Malhotra & Rao Families",
      inviteText: "joyfully invite you to celebrate the wedding of",
      primary: { name: "Kabir", subtitle: "Son of Mr. Rajiv & Mrs. Neelam Malhotra" },
      secondary: { name: "Meher", subtitle: "Daughter of Mr. Srinivas & Mrs. Lata Rao" },
      quote: "Found my favourite person, and kept them.",
      mainDateTime: "2027-02-27T18:30",
      mainEventId: "a3",
      events: [
        ev("a1", "haldi", "Haldi Brunch", "2027-02-26", "11:00", "The Courtyard Garden", "Indiranagar, Bengaluru", { dressCode: "Yellows & whites" }),
        ev("a2", "sangeet", "Sangeet Night", "2027-02-26", "19:30", "The Courtyard Garden", "Indiranagar, Bengaluru", { dressCode: "Glam it up" }),
        ev("a3", "wedding", "The Wedding", "2027-02-27", "18:30", "Taj West End Lawns", "Race Course Road, Bengaluru", { note: "Pheras at sunset · dinner to follow" }),
        ev("a4", "cocktail", "After-party", "2027-02-27", "22:00", "Taj West End Lawns", "Race Course Road, Bengaluru", { dressCode: "Dancing shoes" }),
      ],
      family: { enabled: false, title: "With Love", names: [], kidsTitle: "", kids: [] },
      rsvp: { enabled: true, deadline: "2027-02-10", contacts: [{ name: "Meher", phone: "+91 98450 12345" }, { name: "Kabir", phone: "+91 98860 67890" }] },
      closing: { title: "See You There!", names: ["Kabir & Meher"] },
      hashtag: "#KabirMeetsMeher",
      info: [{ label: "Stay", value: "Room block at Taj West End until 15 Feb" }, { label: "Gifts", value: "No gifts please, just good vibes" }],
    }),
  },
  {
    id: "jet-set",
    name: "Jet Set",
    category: "wedding",
    tagline: "Boarding-pass save-the-date with your guest as the passenger",
    paper: "matte",
    ornament: "none",
    backdrop: "concrete",
    petals: "gold",
    fonts: { display: "var(--f-archivo)", script: "var(--f-archivo)", body: "var(--f-space-mono)" },
    palettes: [
      P({ id: "sky", label: "Sky Blue", paper: "#fbfaf7", paper2: "#eef2f6", ink: "#1b2a3a", inkSoft: "#6b7c8f", accent: "#1f5fae", accent2: "#f2a541", foil: "gold", surface: "#d9dde2", surface2: "#b8bfc8", envelope: "#fbfaf7", envelope2: "#1f5fae", wax: "#1f5fae" }),
      P({ id: "sunset", label: "Sunset", paper: "#fff8f0", paper2: "#fbe9d8", ink: "#3a2018", inkSoft: "#8f6a5a", accent: "#e8603c", accent2: "#2a9d8f", foil: "copper", surface: "#eadbd0", surface2: "#cdb8a8", envelope: "#fff8f0", envelope2: "#e8603c", wax: "#e8603c" }),
      P({ id: "night", label: "Night Flight", paper: "#1a1f2e", paper2: "#232a3d", ink: "#f2f2f2", inkSoft: "#9aa3b8", accent: "#f2c14e", accent2: "#5ec2b7", foil: "gold", surface: "#0b0e16", surface2: "#1a1f2e", envelope: "#e9e9e9", envelope2: "#1a1f2e", wax: "#f2c14e" }),
    ],
    styles: ["Modern", "Fun", "Save the date"],
    effects: ["Ticket printer", "Edge turn", "Barcode", "Ticket"],
    wed: { design: "jetset", intro: "printer", turn: "edge", reveal: "flap" },
    sample: sample("sky", {
      symbol: "none",
      mantra: "",
      eyebrow: "Boarding Pass to Forever",
      blessingLine: "With love from both our families",
      joiner: "&",
      hostSide: "both",
      hosts: "The Sethi & Menon Families",
      inviteText: "invite you to fly away with us to the wedding of",
      primary: { name: "Vivaan", subtitle: "Son of Mr. Harish & Mrs. Anjali Sethi" },
      secondary: { name: "Tanya", subtitle: "Daughter of Mr. Suresh & Mrs. Deepa Menon" },
      quote: "Window seat for life, reserved.",
      effects: { petals: false },
      mainDateTime: "2027-12-11T16:30",
      mainEventId: "t2",
      events: [
        ev("t1", "cocktail", "Welcome Sundowner", "2027-12-10", "18:00", "Radhanagar Beach Deck", "Havelock Island, Andaman", { dressCode: "Beach chic" }),
        ev("t2", "wedding", "Beach Wedding", "2027-12-11", "16:30", "Taj Exotica Lawns", "Havelock Island, Andaman", { note: "Barefoot vows at sunset" }),
        ev("t3", "reception", "Dinner Under the Stars", "2027-12-11", "20:00", "Taj Exotica", "Havelock Island, Andaman", { dressCode: "Island formal" }),
      ],
      family: { enabled: false, title: "With Love", names: [], kidsTitle: "", kids: [] },
      rsvp: { enabled: true, deadline: "2027-10-31", contacts: [{ name: "Tanya", phone: "+91 98200 22334" }, { name: "Vivaan", phone: "+91 98110 55667" }] },
      closing: { title: "Fasten Your Seatbelts", names: ["Vivaan & Tanya"] },
      hashtag: "VT2027",
      info: [
        { label: "Flights", value: "Fly into Port Blair (IXZ); ferries to Havelock are on us" },
        { label: "Stay", value: "Rooms at Taj Exotica, 9–12 Dec" },
      ],
    }),
  },
];
